/-
Copyright (c) 2026 the pasta-asm contributors.
Released under the Apache License, Version 2.0, as described in the file LICENSE.
-/
import PastaAsm.AArch64.Compositions
import PastaAsm.Fields

/-!
# Mathematical reference vectors for the inversion composition

GENERATED by `lean/scripts/gen.py` from the distinct canonical operands in
`test-vectors/pasta_mul-armv8-vectors.txt`; do not edit by hand. Each example asks the
Lean kernel to evaluate the actual AArch64 `invert` composition, including all generated
assembly-block transcriptions used by the Rust driver.

Only the operands come from the AArch64 hardware corpus. The expected values are derived
independently by modular arithmetic, not captured from inversion hardware: zero maps to zero;
for nonzero Montgomery residues `input * result = R^2 (mod p)`, where `R = 2^256`. Thus these
concrete examples supplement, but do not replace, a universal inversion correctness proof.

The modulus limbs and `inv` are `pallasBase` and `vestaBase` from `Fields.lean`, the crate's
constants for its `Fp` (the Pallas base field) and `Fq` (the Vesta base field).
-/

namespace PastaAsm.AArch64

example :
    invert
      (Limbs.ofNat 0x0000000000000000000000000000000000000000000000000000000000000000)
      pallasBase.modulus pallasBase.inv =
    (Limbs.ofNat 0x0000000000000000000000000000000000000000000000000000000000000000) := by
  decide +kernel

example :
    invert
      (Limbs.ofNat 0x0000000000000000000000000000000000000000000000000000000000000001)
      pallasBase.modulus pallasBase.inv =
    (Limbs.ofNat 0x096d41af7b9cb7147797a99bc3c95d18d7d30dbd8b0de0e78c78ecb30000000f) := by
  decide +kernel

example :
    invert
      (Limbs.ofNat 0x3fffffffffffffffffffffffffffffff992c350be41914ad34786d38fffffffd)
      pallasBase.modulus pallasBase.inv =
    (Limbs.ofNat 0x3fffffffffffffffffffffffffffffff992c350be41914ad34786d38fffffffd) := by
  decide +kernel

example :
    invert
      (Limbs.ofNat 0x096d41af7b9cb7147797a99bc3c95d18d7d30dbd8b0de0e78c78ecb30000000f)
      pallasBase.modulus pallasBase.inv =
    (Limbs.ofNat 0x0000000000000000000000000000000000000000000000000000000000000001) := by
  decide +kernel

example :
    invert
      (Limbs.ofNat 0x2ae309222d2d9910df8d1014353fd42cf6a68f3b6ac5b1d1f185a5993a9e10f9)
      pallasBase.modulus pallasBase.inv =
    (Limbs.ofNat 0x21f1c4ff1e2278d570cb2996efc89a65ac9fba6a4077fc57cf3f8e8753a769a9) := by
  decide +kernel

example :
    invert
      (Limbs.ofNat 0x40000000000000000000000000000000224698fc094cf91b992d30ed00000000)
      pallasBase.modulus pallasBase.inv =
    (Limbs.ofNat 0x3692be50846348eb886856643c36a2e74a738b3e7e3f18340cb44439fffffff2) := by
  decide +kernel

example :
    invert
      (Limbs.ofNat 0x000000000000000000000000000000000000000000000000ffffffffffffffff)
      pallasBase.modulus pallasBase.inv =
    (Limbs.ofNat 0x35d6a58f34c5e5907f43e73eb0629ca513b0fc456b09c51680bd32e32ce869b0) := by
  decide +kernel

example :
    invert
      (Limbs.ofNat 0x4000000000000000000000000000000000000000000000000000000000000000)
      pallasBase.modulus pallasBase.inv =
    (Limbs.ofNat 0x3ffffffffffffffffffffffffffffffdfddd093b747d6762065a221cfffffff1) := by
  decide +kernel

example :
    invert
      (Limbs.ofNat 0x00000000000000000000000000000000ffffffffffffffffffffffffffffffff)
      pallasBase.modulus pallasBase.inv =
    (Limbs.ofNat 0x0175fd6f284413073460a8200c81d2894bab8a4cdd8d3d6ccddcde8bcdf8b5cc) := by
  decide +kernel

example :
    invert
      (Limbs.ofNat 0x3fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff)
      pallasBase.modulus pallasBase.inv =
    (Limbs.ofNat 0x0f7860ec4b69b2d874f4d7ff72d7ba780cee202c3f3c17cfb825d59aba23153d) := by
  decide +kernel

example :
    invert
      (Limbs.ofNat 0x00000000000000000000000000000000224698fc094cf91b992d30ed00000001)
      pallasBase.modulus pallasBase.inv =
    (Limbs.ofNat 0x0000000000000000000000000000000224698fc094cf91b992d30ed000000010) := by
  decide +kernel

example :
    invert
      (Limbs.ofNat 0x3c3c3c27e13c21e0e10ff7c33cd237023c3c3c3ce13c21fb3c3c279ce13c3a5b)
      pallasBase.modulus pallasBase.inv =
    (Limbs.ofNat 0x0b11a43f71c44791dea9689cb9dd114ccd658401254152d065cb99e30a682fa9) := by
  decide +kernel

example :
    invert
      (Limbs.ofNat 0x2d5183d900d08ed0364c63f598e2faf5d2e7f1720fe729ad0fd43a9691fb7685)
      pallasBase.modulus pallasBase.inv =
    (Limbs.ofNat 0x2df63bc1ee593b716e2c56d938cf23eb9a764e2c65064b829f8bd6ace3802112) := by
  decide +kernel

example :
    invert
      (Limbs.ofNat 0x228d15317e3b59a0b325ff33eff9b7aed2e1d17fb3cfc39437ed6db762ebf9d4)
      pallasBase.modulus pallasBase.inv =
    (Limbs.ofNat 0x24321cadaecf7780c2639acde5c0411342b21958398552c827c5e22dfb027d73) := by
  decide +kernel

example :
    invert
      (Limbs.ofNat 0x14b06aa09f30e10aeb94c9b1ae30141e72172b9fb8f9852c1cab294080eb8209)
      pallasBase.modulus pallasBase.inv =
    (Limbs.ofNat 0x34918a242688d9c3a81e4b0d8a1058eb750d0e7422d550f3c9357b4dcd321740) := by
  decide +kernel

example :
    invert
      (Limbs.ofNat 0x1268af49ee6ccc4a1148b1f2f22a45a1f88886082fba0c35379a837d7a0e14cc)
      pallasBase.modulus pallasBase.inv =
    (Limbs.ofNat 0x22640428fe61607140171b3ad724993bf7c18599696176350c314c4b6a109d7f) := by
  decide +kernel

example :
    invert
      (Limbs.ofNat 0x0afd4ef708e8a9d1f2438f8fb4e2797639df610a2eda917fa65c1762f2cfefe8)
      pallasBase.modulus pallasBase.inv =
    (Limbs.ofNat 0x1507b8e8e2c820372258a17034c0a5a3d920c18fee41b8c290f3681b17b1d0c5) := by
  decide +kernel

example :
    invert
      (Limbs.ofNat 0x0000000000000000000000000000000000000000000000000000000000000000)
      vestaBase.modulus vestaBase.inv =
    (Limbs.ofNat 0x0000000000000000000000000000000000000000000000000000000000000000) := by
  decide +kernel

example :
    invert
      (Limbs.ofNat 0x0000000000000000000000000000000000000000000000000000000000000001)
      vestaBase.modulus vestaBase.inv =
    (Limbs.ofNat 0x096d41af7ccfdaa97fae231004ccf59067bb433d891a16e3fc9678ff0000000f) := by
  decide +kernel

example :
    invert
      (Limbs.ofNat 0x3fffffffffffffffffffffffffffffff992c350be34205675b2b3e9cfffffffd)
      vestaBase.modulus vestaBase.inv =
    (Limbs.ofNat 0x3fffffffffffffffffffffffffffffff992c350be34205675b2b3e9cfffffffd) := by
  decide +kernel

example :
    invert
      (Limbs.ofNat 0x096d41af7ccfdaa97fae231004ccf59067bb433d891a16e3fc9678ff0000000f)
      vestaBase.modulus vestaBase.inv =
    (Limbs.ofNat 0x0000000000000000000000000000000000000000000000000000000000000001) := by
  decide +kernel

example :
    invert
      (Limbs.ofNat 0x07dd97a06e6792c888fececb8e15cb63e13bda50dba41326008b421c249dae4c)
      vestaBase.modulus vestaBase.inv =
    (Limbs.ofNat 0x1f7a89dd176479535790be58c050df13c68de1279dc601eb6119a3dd8e1a6f7f) := by
  decide +kernel

example :
    invert
      (Limbs.ofNat 0x40000000000000000000000000000000224698fc0994a8dd8c46eb2100000000)
      vestaBase.modulus vestaBase.inv =
    (Limbs.ofNat 0x3692be50833025568051dceffb330a6fba8b55be807a91f98fb07221fffffff2) := by
  decide +kernel

example :
    invert
      (Limbs.ofNat 0x000000000000000000000000000000000000000000000000ffffffffffffffff)
      vestaBase.modulus vestaBase.inv =
    (Limbs.ofNat 0x11d0a8b5ae08c1de1b3dea652ad89c87a4768de3f3c3149d2cf7c5b247dcf879) := by
  decide +kernel

example :
    invert
      (Limbs.ofNat 0x4000000000000000000000000000000000000000000000000000000000000000)
      vestaBase.modulus vestaBase.inv =
    (Limbs.ofNat 0x3ffffffffffffffffffffffffffffffdfddd093b704a1b04c7d83910fffffff1) := by
  decide +kernel

example :
    invert
      (Limbs.ofNat 0x00000000000000000000000000000000ffffffffffffffffffffffffffffffff)
      vestaBase.modulus vestaBase.inv =
    (Limbs.ofNat 0x1cace8582889f5d47523c05d857ecc09b575a720303e9991d1e26ea4ea04cfcb) := by
  decide +kernel

example :
    invert
      (Limbs.ofNat 0x3fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff)
      vestaBase.modulus vestaBase.inv =
    (Limbs.ofNat 0x0686645fbe6a61b8c1a6a18daa1cbf6cab250734883001213ab794200149eff9) := by
  decide +kernel

example :
    invert
      (Limbs.ofNat 0x00000000000000000000000000000000224698fc0994a8dd8c46eb2100000001)
      vestaBase.modulus vestaBase.inv =
    (Limbs.ofNat 0x0000000000000000000000000000000224698fc0994a8dd8c46eb21000000010) := by
  decide +kernel

example :
    invert
      (Limbs.ofNat 0x3c3c3c27e13c21e0e10ff7c33cd237023c3c3c3ce13c21fb3c3c279ce13c3a5b)
      vestaBase.modulus vestaBase.inv =
    (Limbs.ofNat 0x3ad2325167231caf6fdfd8c39aeb0479e026c269fefa0a8a0336dbc1f4ce7137) := by
  decide +kernel

example :
    invert
      (Limbs.ofNat 0x2d5183d900d08ed0364c63f598e2faf5d2e7f1720fe729ad0fd43a9691fb7685)
      vestaBase.modulus vestaBase.inv =
    (Limbs.ofNat 0x0db7185705b3a78bac635404ffe337d63e9036fa0b8f925387334b547405a754) := by
  decide +kernel

example :
    invert
      (Limbs.ofNat 0x228d15317e3b59a0b325ff33eff9b7aed2e1d17fb3cfc39437ed6db762ebf9d4)
      vestaBase.modulus vestaBase.inv =
    (Limbs.ofNat 0x04201347ed521c5e6df93c91ae3d804400e2acc0cfc2cf96b9dd8fbd3a1069a2) := by
  decide +kernel

example :
    invert
      (Limbs.ofNat 0x14b06aa09f30e10aeb94c9b1ae30141e72172b9fb8f9852c1cab294080eb8209)
      vestaBase.modulus vestaBase.inv =
    (Limbs.ofNat 0x1d685ed4f19beeb323b02747e96c25384104b3238aa59fff5b87522e54169231) := by
  decide +kernel

example :
    invert
      (Limbs.ofNat 0x1268af49ee6ccc4a1148b1f2f22a45a1f88886082fba0c35379a837d7a0e14cc)
      vestaBase.modulus vestaBase.inv =
    (Limbs.ofNat 0x3f80b399dbc993893d72eca28276db2b1d85156d6dc2309efe32bea93fa3d1ba) := by
  decide +kernel

example :
    invert
      (Limbs.ofNat 0x0afd4ef708e8a9d1f2438f8fb4e2797639df610a2eda917fa65c1762f2cfefe8)
      vestaBase.modulus vestaBase.inv =
    (Limbs.ofNat 0x0c17eeb99dd21d9f4cae5a01658a8419833302a3948da49c41b8c71e252b752f) := by
  decide +kernel


-- 34 vectors; every distinct canonical corpus operand is included.

end PastaAsm.AArch64
