/-
Copyright Supranational LLC (the routines, transcribed from Semolina v0.1.4).
Copyright (c) 2026 the pasta-asm contributors (the transcription).
Released under the Apache License, Version 2.0, as described in the file LICENSE.
-/
import PastaAsm.Semantics.Inversion
import PastaAsm.AArch64.Semantics

/-!
# The crate's inline Pasta field blocks, transcribed

GENERATED by `lean/scripts/gen.py` from the `asm!` blocks of `mul`, `square`, `add`, and `sub`
in `src/aarch64.rs`; do not edit by hand. Each definition follows its block instruction by
instruction (the instruction is the trailing comment; the two lines that unpack an
instruction's (result, carry) pair are marked as its continuation), over the semantics of
`PastaAsm.AArch64.Semantics`. Registers are rebound by the instructions that write them, `c`
is the carry flag, `s` is the (result, carry) pair of the instruction that last set both,
argument limbs are read where the block's operands bind them, and the output limbs are bound
where the block's output operands hold them. Bindings that nothing reads are left as
comments. See the generator's docstring for what it checks.
-/

namespace PastaAsm.AArch64

/-- The registers that `mulMont` carries from one round to the next. -/
structure MulMontAcc where
  /-- accumulator limb 0 -/
  r0 : Nat
  /-- accumulator limb 1 -/
  r1 : Nat
  /-- accumulator limb 2 -/
  r2 : Nat
  /-- accumulator limb 3 -/
  r3 : Nat
  /-- accumulator limb 4 -/
  r4 : Nat
  /-- the round's Montgomery quotient `q` -/
  q : Nat
  /-- `low(p1 * q)`, the first term of the round's reduction -/
  t1 : Nat
  /-- `low(q * 2^62)`, the third term of the round's reduction -/
  t3 : Nat
  deriving DecidableEq, Repr

namespace MulMontAcc

/-- Every field is below `2^64`. -/
def Bounded (s : MulMontAcc) : Prop :=
   s.r0 < 2^64 ∧ s.r1 < 2^64 ∧ s.r2 < 2^64 ∧ s.r3 < 2^64 ∧ s.r4 < 2^64 ∧ s.q < 2^64 ∧ s.t1 < 2^64 ∧
      s.t3 < 2^64

/-- The accumulator's value: limbs `r0`, `r1`, `r2`, `r3`, `r4` with weights `2^0` to `2^256`. -/
def toNat (s : MulMontAcc) : Nat :=
   s.r0 + 2^64 * s.r1 + 2^128 * s.r2 + 2^192 * s.r3 + 2^256 * s.r4

end MulMontAcc

/-- One round of `mulMont`: the instructions between one `lsl t3,q,#62` and the next in each of its
3 rounds, on the round's `rhs` limb `b` and the registers `acc` carried from the previous round. -/
def mulMontRound (lhs modulus : Limbs) (inv b : Nat) (acc : MulMontAcc) : MulMontAcc :=
  let a0 := lhs.l0              -- argument
  let a1 := lhs.l1              -- argument
  let a2 := lhs.l2              -- argument
  let a3 := lhs.l3              -- argument
  let p0 := modulus.l0          -- argument
  let p1 := modulus.l1          -- argument
  let inv := inv                -- argument
  let b1 := b                   -- argument
  let r0 := acc.r0              -- argument
  let r1 := acc.r1              -- argument
  let r2 := acc.r2              -- argument
  let r3 := acc.r3              -- argument
  let r4 := acc.r4              -- argument
  let q := acc.q                -- argument
  let t1 := acc.t1              -- argument
  let t3 := acc.t3              -- argument
  let c := (subc r0 1 1).2      -- subs xzr,r0,#1
  let t0 := umulh p0 q          -- umulh t0,p0,q
  let s := addc r1 t1 c         -- adcs r1,r1,t1
  let r1 := s.1                 --   `-> r1
  let c := s.2                  --   `-> carry
  let t1 := umulh p1 q          -- umulh t1,p1,q
  let s := addc r2 0 c          -- adcs r2,r2,xzr
  let r2 := s.1                 --   `-> r2
  let c := s.2                  --   `-> carry
  let s := addc r3 t3 c         -- adcs r3,r3,t3
  let r3 := s.1                 --   `-> r3
  let c := s.2                  --   `-> carry
  let t3 := lsr q 2             -- lsr t3,q,#2
  let r4 := (addc r4 0 c).1     -- adc r4,r4,xzr
  let s := addc r1 t0 0         -- adds r0,r1,t0
  let r0 := s.1                 --   `-> r0
  let c := s.2                  --   `-> carry
  let t0 := mulLo a0 b1         -- mul t0,a0,b1
  let s := addc r2 t1 c         -- adcs r1,r2,t1
  let r1 := s.1                 --   `-> r1
  let c := s.2                  --   `-> carry
  let t1 := mulLo a1 b1         -- mul t1,a1,b1
  let s := addc r3 0 c          -- adcs r2,r3,xzr
  let r2 := s.1                 --   `-> r2
  let c := s.2                  --   `-> carry
  let t2 := mulLo a2 b1         -- mul t2,a2,b1
  let s := addc r4 t3 c         -- adcs r3,r4,t3
  let r3 := s.1                 --   `-> r3
  let c := s.2                  --   `-> carry
  let t3 := mulLo a3 b1         -- mul t3,a3,b1
  let r4 := (addc 0 0 c).1      -- adc r4,xzr,xzr
  let s := addc r0 t0 0         -- adds r0,r0,t0
  let r0 := s.1                 --   `-> r0
  let c := s.2                  --   `-> carry
  let t0 := umulh a0 b1         -- umulh t0,a0,b1
  let s := addc r1 t1 c         -- adcs r1,r1,t1
  let r1 := s.1                 --   `-> r1
  let c := s.2                  --   `-> carry
  let t1 := umulh a1 b1         -- umulh t1,a1,b1
  let s := addc r2 t2 c         -- adcs r2,r2,t2
  let r2 := s.1                 --   `-> r2
  let c := s.2                  --   `-> carry
  let q := mulLo inv r0         -- mul q,inv,r0
  let t2 := umulh a2 b1         -- umulh t2,a2,b1
  let s := addc r3 t3 c         -- adcs r3,r3,t3
  let r3 := s.1                 --   `-> r3
  let c := s.2                  --   `-> carry
  let t3 := umulh a3 b1         -- umulh t3,a3,b1
  let r4 := (addc r4 0 c).1     -- adc r4,r4,xzr
  let s := addc r1 t0 0         -- adds r1,r1,t0
  let r1 := s.1                 --   `-> r1
  let c := s.2                  --   `-> carry
  let s := addc r2 t1 c         -- adcs r2,r2,t1
  let r2 := s.1                 --   `-> r2
  let c := s.2                  --   `-> carry
  let t1 := mulLo p1 q          -- mul t1,p1,q
  let s := addc r3 t2 c         -- adcs r3,r3,t2
  let r3 := s.1                 --   `-> r3
  let c := s.2                  --   `-> carry
  let r4 := (addc r4 t3 c).1    -- adc r4,r4,t3
  let t3 := lsl q 62            -- lsl t3,q,#62
  ⟨r0, r1, r2, r3, r4, q, t1, t3⟩

/-- The inline `asm!` block of `mul`: Montgomery multiplication, `lhs * rhs * 2^-256 mod p`, with
the result in the block's output operands. Its rounds are those of Semolina's `mul_mont_pasta`; its
epilogue keeps four limbs of the final candidate. -/
def mulMont (lhs rhs modulus : Limbs) (inv : Nat) : Limbs :=
  let a0 := lhs.l0              -- argument
  let a1 := lhs.l1              -- argument
  let a2 := lhs.l2              -- argument
  let a3 := lhs.l3              -- argument
  let b0 := rhs.l0              -- argument
  let b1 := rhs.l1              -- argument
  let b2 := rhs.l2              -- argument
  let b3 := rhs.l3              -- argument
  let p0 := modulus.l0          -- argument
  let p1 := modulus.l1          -- argument
  let inv := inv                -- argument
  let r0 := mulLo a0 b0         -- mul r0,a0,b0
  let r1 := mulLo a1 b0         -- mul r1,a1,b0
  let r2 := mulLo a2 b0         -- mul r2,a2,b0
  let r3 := mulLo a3 b0         -- mul r3,a3,b0
  let t0 := umulh a0 b0         -- umulh t0,a0,b0
  let t1 := umulh a1 b0         -- umulh t1,a1,b0
  let q := mulLo inv r0         -- mul q,inv,r0
  let t2 := umulh a2 b0         -- umulh t2,a2,b0
  let t3 := umulh a3 b0         -- umulh t3,a3,b0
  let s := addc r1 t0 0         -- adds r1,r1,t0
  let r1 := s.1                 --   `-> r1
  let c := s.2                  --   `-> carry
  let s := addc r2 t1 c         -- adcs r2,r2,t1
  let r2 := s.1                 --   `-> r2
  let c := s.2                  --   `-> carry
  let t1 := mulLo p1 q          -- mul t1,p1,q
  let s := addc r3 t2 c         -- adcs r3,r3,t2
  let r3 := s.1                 --   `-> r3
  let c := s.2                  --   `-> carry
  let r4 := (addc 0 t3 c).1     -- adc r4,xzr,t3
  let t3 := lsl q 62            -- lsl t3,q,#62
  let round1 := mulMontRound lhs modulus inv b1 ⟨r0, r1, r2, r3, r4, q, t1, t3⟩  -- round 1
  let r0 := round1.r0           -- round 1 output
  let r1 := round1.r1           -- round 1 output
  let r2 := round1.r2           -- round 1 output
  let r3 := round1.r3           -- round 1 output
  let r4 := round1.r4           -- round 1 output
  let q := round1.q             -- round 1 output
  let t1 := round1.t1           -- round 1 output
  let t3 := round1.t3           -- round 1 output
  let round2 := mulMontRound lhs modulus inv b2 ⟨r0, r1, r2, r3, r4, q, t1, t3⟩  -- round 2
  let r0 := round2.r0           -- round 2 output
  let r1 := round2.r1           -- round 2 output
  let r2 := round2.r2           -- round 2 output
  let r3 := round2.r3           -- round 2 output
  let r4 := round2.r4           -- round 2 output
  let q := round2.q             -- round 2 output
  let t1 := round2.t1           -- round 2 output
  let t3 := round2.t3           -- round 2 output
  let round3 := mulMontRound lhs modulus inv b3 ⟨r0, r1, r2, r3, r4, q, t1, t3⟩  -- round 3
  let r0 := round3.r0           -- round 3 output
  let r1 := round3.r1           -- round 3 output
  let r2 := round3.r2           -- round 3 output
  let r3 := round3.r3           -- round 3 output
  let r4 := round3.r4           -- round 3 output
  let q := round3.q             -- round 3 output
  let t1 := round3.t1           -- round 3 output
  let t3 := round3.t3           -- round 3 output
  let c := (subc r0 1 1).2      -- subs xzr,r0,#1
  let t0 := umulh p0 q          -- umulh t0,p0,q
  let s := addc r1 t1 c         -- adcs r1,r1,t1
  let r1 := s.1                 --   `-> r1
  let c := s.2                  --   `-> carry
  let t1 := umulh p1 q          -- umulh t1,p1,q
  let s := addc r2 0 c          -- adcs r2,r2,xzr
  let r2 := s.1                 --   `-> r2
  let c := s.2                  --   `-> carry
  let s := addc r3 t3 c         -- adcs r3,r3,t3
  let r3 := s.1                 --   `-> r3
  let c := s.2                  --   `-> carry
  let t3 := lsr q 2             -- lsr t3,q,#2
  let r4 := (addc r4 0 c).1     -- adc r4,r4,xzr
  let s := addc r1 t0 0         -- adds r0,r1,t0
  let r0 := s.1                 --   `-> r0
  let c := s.2                  --   `-> carry
  let s := addc r2 t1 c         -- adcs r1,r2,t1
  let r1 := s.1                 --   `-> r1
  let c := s.2                  --   `-> carry
  let s := addc r3 0 c          -- adcs r2,r3,xzr
  let r2 := s.1                 --   `-> r2
  let c := s.2                  --   `-> carry
  let s := addc r4 t3 c         -- adcs r3,r4,t3
  let r3 := s.1                 --   `-> r3
  let q := 4611686018427387904  -- mov q,#0x4000000000000000
  let s := subc r0 p0 1         -- subs t0,r0,p0
  let t0 := s.1                 --   `-> t0
  let c := s.2                  --   `-> carry
  let s := subc r1 p1 c         -- sbcs t1,r1,p1
  let t1 := s.1                 --   `-> t1
  let c := s.2                  --   `-> carry
  let s := subc r2 0 c          -- sbcs t2,r2,xzr
  let t2 := s.1                 --   `-> t2
  let c := s.2                  --   `-> carry
  let s := subc r3 q c          -- sbcs t3,r3,q
  let t3 := s.1                 --   `-> t3
  let c := s.2                  --   `-> carry
  let r0 := cselLo c r0 t0      -- csel r0,r0,t0,lo
  let r1 := cselLo c r1 t1      -- csel r1,r1,t1,lo
  let r2 := cselLo c r2 t2      -- csel r2,r2,t2,lo
  let r3 := cselLo c r3 t3      -- csel r3,r3,t3,lo
  ⟨r0, r1, r2, r3⟩

/-- The inline `asm!` block of `square`: Montgomery squaring, `value^2 * 2^-256 mod p`, the squaring
loop body of Semolina's `sqr_n_mul_mont_pasta` followed by a conditional subtraction, with the
result in the block's `inout` operands. -/
def sqrMont (value modulus : Limbs) (inv : Nat) : Limbs :=
  let a0 := value.l0            -- argument
  let a1 := value.l1            -- argument
  let a2 := value.l2            -- argument
  let a3 := value.l3            -- argument
  let p0 := modulus.l0          -- argument
  let p1 := modulus.l1          -- argument
  let inv := inv                -- argument
  let z1 := mulLo a1 a0         -- mul z1,a1,a0
  let w1 := umulh a1 a0         -- umulh w1,a1,a0
  let z2 := mulLo a2 a0         -- mul z2,a2,a0
  let w2 := umulh a2 a0         -- umulh w2,a2,a0
  let z3 := mulLo a3 a0         -- mul z3,a3,a0
  let z4 := umulh a3 a0         -- umulh z4,a3,a0
  let s := addc z2 w1 0         -- adds z2,z2,w1
  let z2 := s.1                 --   `-> z2
  let c := s.2                  --   `-> carry
  let w0 := mulLo a2 a1         -- mul w0,a2,a1
  let w1 := umulh a2 a1         -- umulh w1,a2,a1
  let s := addc z3 w2 c         -- adcs z3,z3,w2
  let z3 := s.1                 --   `-> z3
  let c := s.2                  --   `-> carry
  let w2 := mulLo a3 a1         -- mul w2,a3,a1
  let w3 := umulh a3 a1         -- umulh w3,a3,a1
  let z4 := (addc z4 0 c).1     -- adc z4,z4,xzr
  let z5 := mulLo a3 a2         -- mul z5,a3,a2
  let z6 := umulh a3 a2         -- umulh z6,a3,a2
  let s := addc w1 w2 0         -- adds w1,w1,w2
  let w1 := s.1                 --   `-> w1
  let c := s.2                  --   `-> carry
  let z0 := mulLo a0 a0         -- mul z0,a0,a0
  let w2 := (addc w3 0 c).1     -- adc w2,w3,xzr
  let s := addc z3 w0 0         -- adds z3,z3,w0
  let z3 := s.1                 --   `-> z3
  let c := s.2                  --   `-> carry
  let a0 := umulh a0 a0         -- umulh a0,a0,a0
  let s := addc z4 w1 c         -- adcs z4,z4,w1
  let z4 := s.1                 --   `-> z4
  let c := s.2                  --   `-> carry
  let w1 := mulLo a1 a1         -- mul w1,a1,a1
  let s := addc z5 w2 c         -- adcs z5,z5,w2
  let z5 := s.1                 --   `-> z5
  let c := s.2                  --   `-> carry
  let a1 := umulh a1 a1         -- umulh a1,a1,a1
  let z6 := (addc z6 0 c).1     -- adc z6,z6,xzr
  let s := addc z1 z1 0         -- adds z1,z1,z1
  let z1 := s.1                 --   `-> z1
  let c := s.2                  --   `-> carry
  let w2 := mulLo a2 a2         -- mul w2,a2,a2
  let s := addc z2 z2 c         -- adcs z2,z2,z2
  let z2 := s.1                 --   `-> z2
  let c := s.2                  --   `-> carry
  let a2 := umulh a2 a2         -- umulh a2,a2,a2
  let s := addc z3 z3 c         -- adcs z3,z3,z3
  let z3 := s.1                 --   `-> z3
  let c := s.2                  --   `-> carry
  let w3 := mulLo a3 a3         -- mul w3,a3,a3
  let s := addc z4 z4 c         -- adcs z4,z4,z4
  let z4 := s.1                 --   `-> z4
  let c := s.2                  --   `-> carry
  let a3 := umulh a3 a3         -- umulh a3,a3,a3
  let s := addc z5 z5 c         -- adcs z5,z5,z5
  let z5 := s.1                 --   `-> z5
  let c := s.2                  --   `-> carry
  let s := addc z6 z6 c         -- adcs z6,z6,z6
  let z6 := s.1                 --   `-> z6
  let c := s.2                  --   `-> carry
  let z7 := (addc 0 0 c).1      -- adc z7,xzr,xzr
  let q := mulLo inv z0         -- mul q,inv,z0
  let s := addc z1 a0 0         -- adds z1,z1,a0
  let z1 := s.1                 --   `-> z1
  let c := s.2                  --   `-> carry
  let s := addc z2 w1 c         -- adcs z2,z2,w1
  let z2 := s.1                 --   `-> z2
  let c := s.2                  --   `-> carry
  let s := addc z3 a1 c         -- adcs z3,z3,a1
  let z3 := s.1                 --   `-> z3
  let c := s.2                  --   `-> carry
  let s := addc z4 w2 c         -- adcs z4,z4,w2
  let z4 := s.1                 --   `-> z4
  let c := s.2                  --   `-> carry
  let s := addc z5 a2 c         -- adcs z5,z5,a2
  let z5 := s.1                 --   `-> z5
  let c := s.2                  --   `-> carry
  let s := addc z6 w3 c         -- adcs z6,z6,w3
  let z6 := s.1                 --   `-> z6
  let c := s.2                  --   `-> carry
  let z7 := (addc z7 a3 c).1    -- adc z7,z7,a3
  let w1 := mulLo p1 q          -- mul w1,p1,q
  let w3 := lsl q 62            -- lsl w3,q,#62
  let c := (subc z0 1 1).2      -- subs xzr,z0,#1
  let w0 := umulh p0 q          -- umulh w0,p0,q
  let s := addc z1 w1 c         -- adcs z1,z1,w1
  let z1 := s.1                 --   `-> z1
  let c := s.2                  --   `-> carry
  let w1 := umulh p1 q          -- umulh w1,p1,q
  let s := addc z2 0 c          -- adcs z2,z2,xzr
  let z2 := s.1                 --   `-> z2
  let c := s.2                  --   `-> carry
  let s := addc z3 w3 c         -- adcs z3,z3,w3
  let z3 := s.1                 --   `-> z3
  let c := s.2                  --   `-> carry
  let w3 := lsr q 2             -- lsr w3,q,#2
  let cy := (addc 0 0 c).1      -- adc cy,xzr,xzr
  let s := addc z1 w0 0         -- adds z0,z1,w0
  let z0 := s.1                 --   `-> z0
  let c := s.2                  --   `-> carry
  let s := addc z2 w1 c         -- adcs z1,z2,w1
  let z1 := s.1                 --   `-> z1
  let c := s.2                  --   `-> carry
  let s := addc z3 0 c          -- adcs z2,z3,xzr
  let z2 := s.1                 --   `-> z2
  let c := s.2                  --   `-> carry
  let q := mulLo inv z0         -- mul q,inv,z0
  let z3 := (addc cy w3 c).1    -- adc z3,cy,w3
  let w1 := mulLo p1 q          -- mul w1,p1,q
  let w3 := lsl q 62            -- lsl w3,q,#62
  let c := (subc z0 1 1).2      -- subs xzr,z0,#1
  let w0 := umulh p0 q          -- umulh w0,p0,q
  let s := addc z1 w1 c         -- adcs z1,z1,w1
  let z1 := s.1                 --   `-> z1
  let c := s.2                  --   `-> carry
  let w1 := umulh p1 q          -- umulh w1,p1,q
  let s := addc z2 0 c          -- adcs z2,z2,xzr
  let z2 := s.1                 --   `-> z2
  let c := s.2                  --   `-> carry
  let s := addc z3 w3 c         -- adcs z3,z3,w3
  let z3 := s.1                 --   `-> z3
  let c := s.2                  --   `-> carry
  let w3 := lsr q 2             -- lsr w3,q,#2
  let cy := (addc 0 0 c).1      -- adc cy,xzr,xzr
  let s := addc z1 w0 0         -- adds z0,z1,w0
  let z0 := s.1                 --   `-> z0
  let c := s.2                  --   `-> carry
  let s := addc z2 w1 c         -- adcs z1,z2,w1
  let z1 := s.1                 --   `-> z1
  let c := s.2                  --   `-> carry
  let s := addc z3 0 c          -- adcs z2,z3,xzr
  let z2 := s.1                 --   `-> z2
  let c := s.2                  --   `-> carry
  let q := mulLo inv z0         -- mul q,inv,z0
  let z3 := (addc cy w3 c).1    -- adc z3,cy,w3
  let w1 := mulLo p1 q          -- mul w1,p1,q
  let w3 := lsl q 62            -- lsl w3,q,#62
  let c := (subc z0 1 1).2      -- subs xzr,z0,#1
  let w0 := umulh p0 q          -- umulh w0,p0,q
  let s := addc z1 w1 c         -- adcs z1,z1,w1
  let z1 := s.1                 --   `-> z1
  let c := s.2                  --   `-> carry
  let w1 := umulh p1 q          -- umulh w1,p1,q
  let s := addc z2 0 c          -- adcs z2,z2,xzr
  let z2 := s.1                 --   `-> z2
  let c := s.2                  --   `-> carry
  let s := addc z3 w3 c         -- adcs z3,z3,w3
  let z3 := s.1                 --   `-> z3
  let c := s.2                  --   `-> carry
  let w3 := lsr q 2             -- lsr w3,q,#2
  let cy := (addc 0 0 c).1      -- adc cy,xzr,xzr
  let s := addc z1 w0 0         -- adds z0,z1,w0
  let z0 := s.1                 --   `-> z0
  let c := s.2                  --   `-> carry
  let s := addc z2 w1 c         -- adcs z1,z2,w1
  let z1 := s.1                 --   `-> z1
  let c := s.2                  --   `-> carry
  let s := addc z3 0 c          -- adcs z2,z3,xzr
  let z2 := s.1                 --   `-> z2
  let c := s.2                  --   `-> carry
  let q := mulLo inv z0         -- mul q,inv,z0
  let z3 := (addc cy w3 c).1    -- adc z3,cy,w3
  let w1 := mulLo p1 q          -- mul w1,p1,q
  let w3 := lsl q 62            -- lsl w3,q,#62
  let c := (subc z0 1 1).2      -- subs xzr,z0,#1
  let w0 := umulh p0 q          -- umulh w0,p0,q
  let s := addc z1 w1 c         -- adcs z1,z1,w1
  let z1 := s.1                 --   `-> z1
  let c := s.2                  --   `-> carry
  let w1 := umulh p1 q          -- umulh w1,p1,q
  let s := addc z2 0 c          -- adcs z2,z2,xzr
  let z2 := s.1                 --   `-> z2
  let c := s.2                  --   `-> carry
  let s := addc z3 w3 c         -- adcs z3,z3,w3
  let z3 := s.1                 --   `-> z3
  let c := s.2                  --   `-> carry
  let w3 := lsr q 2             -- lsr w3,q,#2
  let cy := (addc 0 0 c).1      -- adc cy,xzr,xzr
  let s := addc z1 w0 0         -- adds z0,z1,w0
  let z0 := s.1                 --   `-> z0
  let c := s.2                  --   `-> carry
  let s := addc z2 w1 c         -- adcs z1,z2,w1
  let z1 := s.1                 --   `-> z1
  let c := s.2                  --   `-> carry
  let s := addc z3 0 c          -- adcs z2,z3,xzr
  let z2 := s.1                 --   `-> z2
  let c := s.2                  --   `-> carry
  let z3 := (addc cy w3 c).1    -- adc z3,cy,w3
  let s := addc z0 z4 0         -- adds a0,z0,z4
  let a0 := s.1                 --   `-> a0
  let c := s.2                  --   `-> carry
  let s := addc z1 z5 c         -- adcs a1,z1,z5
  let a1 := s.1                 --   `-> a1
  let c := s.2                  --   `-> carry
  let s := addc z2 z6 c         -- adcs a2,z2,z6
  let a2 := s.1                 --   `-> a2
  let c := s.2                  --   `-> carry
  let a3 := (addc z3 z7 c).1    -- adc a3,z3,z7
  let q := 4611686018427387904  -- mov q,#0x4000000000000000
  let s := subc a0 p0 1         -- subs z0,a0,p0
  let z0 := s.1                 --   `-> z0
  let c := s.2                  --   `-> carry
  let s := subc a1 p1 c         -- sbcs z1,a1,p1
  let z1 := s.1                 --   `-> z1
  let c := s.2                  --   `-> carry
  let s := subc a2 0 c          -- sbcs z2,a2,xzr
  let z2 := s.1                 --   `-> z2
  let c := s.2                  --   `-> carry
  let s := subc a3 q c          -- sbcs z3,a3,q
  let z3 := s.1                 --   `-> z3
  let c := s.2                  --   `-> carry
  let a0 := cselLo c a0 z0      -- csel a0,a0,z0,lo
  let a1 := cselLo c a1 z1      -- csel a1,a1,z1,lo
  let a2 := cselLo c a2 z2      -- csel a2,a2,z2,lo
  let a3 := cselLo c a3 z3      -- csel a3,a3,z3,lo
  ⟨a0, a1, a2, a3⟩

/-- The inline `asm!` block of `add`: modular addition, `lhs + rhs mod p`, as a full-width addition,
a subtraction of the modulus, and the selection of the reduced sum when that subtraction did not
borrow, with the result in the block's `inout` operands. -/
def addMod (lhs rhs modulus : Limbs) : Limbs :=
  let r0 := lhs.l0              -- argument
  let r1 := lhs.l1              -- argument
  let r2 := lhs.l2              -- argument
  let r3 := lhs.l3              -- argument
  let b0 := rhs.l0              -- argument
  let b1 := rhs.l1              -- argument
  let b2 := rhs.l2              -- argument
  let b3 := rhs.l3              -- argument
  let p0 := modulus.l0          -- argument
  let p1 := modulus.l1          -- argument
  let p3 := modulus.l3          -- argument
  let s := addc r0 b0 0         -- adds r0,r0,b0
  let r0 := s.1                 --   `-> r0
  let c := s.2                  --   `-> carry
  let s := addc r1 b1 c         -- adcs r1,r1,b1
  let r1 := s.1                 --   `-> r1
  let c := s.2                  --   `-> carry
  let s := addc r2 b2 c         -- adcs r2,r2,b2
  let r2 := s.1                 --   `-> r2
  let c := s.2                  --   `-> carry
  let r3 := (addc r3 b3 c).1    -- adc r3,r3,b3
  let s := subc r0 p0 1         -- subs t0,r0,p0
  let t0 := s.1                 --   `-> t0
  let c := s.2                  --   `-> carry
  let s := subc r1 p1 c         -- sbcs t1,r1,p1
  let t1 := s.1                 --   `-> t1
  let c := s.2                  --   `-> carry
  let s := subc r2 0 c          -- sbcs t2,r2,xzr
  let t2 := s.1                 --   `-> t2
  let c := s.2                  --   `-> carry
  let s := subc r3 p3 c         -- sbcs t3,r3,p3
  let t3 := s.1                 --   `-> t3
  let c := s.2                  --   `-> carry
  let r0 := cselCs c t0 r0      -- csel r0,t0,r0,cs
  let r1 := cselCs c t1 r1      -- csel r1,t1,r1,cs
  let r2 := cselCs c t2 r2      -- csel r2,t2,r2,cs
  let r3 := cselCs c t3 r3      -- csel r3,t3,r3,cs
  ⟨r0, r1, r2, r3⟩

/-- The inline `asm!` block of `sub`: modular subtraction, `lhs - rhs mod p`, as a full-width
subtraction and the addition of the modulus when it borrowed, with the result in the block's `inout`
operands. -/
def subMod (lhs rhs modulus : Limbs) : Limbs :=
  let r0 := lhs.l0              -- argument
  let r1 := lhs.l1              -- argument
  let r2 := lhs.l2              -- argument
  let r3 := lhs.l3              -- argument
  let b0 := rhs.l0              -- argument
  let b1 := rhs.l1              -- argument
  let b2 := rhs.l2              -- argument
  let b3 := rhs.l3              -- argument
  let p0 := modulus.l0          -- argument
  let p1 := modulus.l1          -- argument
  let p3 := modulus.l3          -- argument
  let s := subc r0 b0 1         -- subs r0,r0,b0
  let r0 := s.1                 --   `-> r0
  let c := s.2                  --   `-> carry
  let s := subc r1 b1 c         -- sbcs r1,r1,b1
  let r1 := s.1                 --   `-> r1
  let c := s.2                  --   `-> carry
  let s := subc r2 b2 c         -- sbcs r2,r2,b2
  let r2 := s.1                 --   `-> r2
  let c := s.2                  --   `-> carry
  let s := subc r3 b3 c         -- sbcs r3,r3,b3
  let r3 := s.1                 --   `-> r3
  let c := s.2                  --   `-> carry
  let t0 := cselLo c p0 0       -- csel t0,p0,xzr,cc
  let t1 := cselLo c p1 0       -- csel t1,p1,xzr,cc
  let t3 := cselLo c p3 0       -- csel t3,p3,xzr,cc
  let s := addc r0 t0 0         -- adds r0,r0,t0
  let r0 := s.1                 --   `-> r0
  let c := s.2                  --   `-> carry
  let s := addc r1 t1 c         -- adcs r1,r1,t1
  let r1 := s.1                 --   `-> r1
  let c := s.2                  --   `-> carry
  let s := addc r2 0 c          -- adcs r2,r2,xzr
  let r2 := s.1                 --   `-> r2
  let c := s.2                  --   `-> carry
  let r3 := (addc r3 t3 c).1    -- adc r3,r3,t3
  ⟨r0, r1, r2, r3⟩

/-- The updated GCD value and sign-corrected matrix-row coefficients. -/
structure UpdateABResult where
  value : Limbs
  f : Nat
  g : Nat
  deriving DecidableEq, Repr

/-- The second row returned by the final low-limb divsteps. -/
structure InvertRow where
  f1 : Nat
  g1 : Nat
  deriving DecidableEq, Repr

/-- The low half and adjusted high half of the final coefficient. -/
structure CoefficientSplit where
  low : Limbs
  high : Limbs
  deriving DecidableEq, Repr

/-- Registers carried by one checked iteration of `divsteps31`. -/
structure Divsteps31State where
  a3 : Nat
  cnt : Nat
  b3 : Nat
  fg1 : Nat
  fg0 : Nat
  deriving DecidableEq, Repr
/-- One source loop iteration of `divsteps31`. The wrapper validates and calls it exactly 31 times.
-/
def divsteps31Round (bias : Nat) (acc : Divsteps31State) : Divsteps31State :=
  let bias := bias                  -- invariant argument
  let a3 := acc.a3                  -- loop state argument
  let cnt := acc.cnt                -- loop state argument
  let b3 := acc.b3                  -- loop state argument
  let fg1 := acc.fg1                -- loop state argument
  let fg0 := acc.fg0                -- loop state argument
  let t3 := sbfx a3 0 1             -- sbfx t3,a3,#0,#1
  let cnt := sub cnt 1              -- sub cnt,cnt,#1
  let t0 := bitAnd b3 t3            -- and t0,b3,t3
  let t1 := sub b3 a3               -- sub t1,b3,a3
  let s := subc a3 t0 1             -- subs t2,a3,t0
  let t2 := s.1                     --   `-> t2
  let c := s.2                      --   `-> carry
  let t0 := fg1                     -- mov t0,fg1
  let b3 := cselCs c b3 a3          -- csel b3,b3,a3,hs
  let a3 := cselCs c t2 t1          -- csel a3,t2,t1,hs
  let fg1 := cselCs c fg1 fg0       -- csel fg1,fg1,fg0,hs
  let fg0 := cselCs c fg0 t0        -- csel fg0,fg0,t0,hs
  let a3 := lsr a3 1                -- lsr a3,a3,#1
  let t0 := bitAnd fg1 t3           -- and t0,fg1,t3
  let t1 := bitAnd bias t3          -- and t1,bias,t3
  let fg0 := sub fg0 t0             -- sub fg0,fg0,t0
  let fg1 := add fg1 fg1            -- add fg1,fg1,fg1
  let fg0 := add fg0 t1             -- add fg0,fg0,t1
  let fg1 := sub fg1 bias           -- sub fg1,fg1,bias
  ⟨a3, cnt, b3, fg1, fg0⟩

/-- The 31-step approximation helper, including its checked fixed-count inner loop. Signed matrix
entries are represented by their 64-bit register bitpatterns. -/
def divsteps31 (a b : Limbs) : InvertMatrix :=
  let a0 := a.l0                    -- argument
  let a1 := a.l1                    -- argument
  let a2 := a.l2                    -- argument
  let a3 := a.l3                    -- argument
  let b0 := b.l0                    -- argument
  let b1 := b.l1                    -- argument
  let b2 := b.l2                    -- argument
  let b3 := b.l3                    -- argument
  let fg0 := 9223372034707292160    -- argument
  let fg1 := 9223372039002259455    -- argument
  let bias := 9223372034707292159   -- argument
  let cnt := 31                     -- argument
  let t0 := orr a3 b3               -- orr t0,a3,b3
  let z := (cmp t0 0).z             -- cmp t0,#0
  let a3 := cselNe z a3 a2          -- csel a3,a3,a2,ne
  let b3 := cselNe z b3 b2          -- csel b3,b3,b2,ne
  let a2 := cselNe z a2 a1          -- csel a2,a2,a1,ne
  let t0 := orr a3 b3               -- orr t0,a3,b3
  let b2 := cselNe z b2 b1          -- csel b2,b2,b1,ne
  let z := (cmp t0 0).z             -- cmp t0,#0
  let a3 := cselNe z a3 a2          -- csel a3,a3,a2,ne
  let b3 := cselNe z b3 b2          -- csel b3,b3,b2,ne
  let a2 := cselNe z a2 a0          -- csel a2,a2,a0,ne
  let t0 := orr a3 b3               -- orr t0,a3,b3
  let b2 := cselNe z b2 b0          -- csel b2,b2,b0,ne
  let t0 := clz t0                  -- clz t0,t0
  let z := (cmp t0 64).z            -- cmp t0,#64
  let t0 := cselNe z t0 0           -- csel t0,t0,xzr,ne
  let a3 := cselNe z a3 a2          -- csel a3,a3,a2,ne
  let b3 := cselNe z b3 b2          -- csel b3,b3,b2,ne
  let t1 := neg t0                  -- neg t1,t0
  let a3 := lslv a3 t0              -- lslv a3,a3,t0
  let b3 := lslv b3 t0              -- lslv b3,b3,t0
  let a2 := lsrv a2 t1              -- lsrv a2,a2,t1
  let b2 := lsrv b2 t1              -- lsrv b2,b2,t1
  let a2 := bitAnd a2 (asr t1 6)    -- and a2,a2,t1,asr #6
  let b2 := bitAnd b2 (asr t1 6)    -- and b2,b2,t1,asr #6
  let a3 := orr a3 a2               -- orr a3,a3,a2
  let b3 := orr b3 b2               -- orr b3,b3,b2
  let a3 := bfxil a3 a0 0 31        -- bfxil a3,a0,#0,#31
  let b3 := bfxil b3 b0 0 31        -- bfxil b3,b0,#0,#31
  let round1 := divsteps31Round bias ⟨a3, cnt, b3, fg1, fg0⟩  -- loop iteration 1
  let a3 := round1.a3               -- loop iteration 1 output
  let cnt := round1.cnt             -- loop iteration 1 output
  let b3 := round1.b3               -- loop iteration 1 output
  let fg1 := round1.fg1             -- loop iteration 1 output
  let fg0 := round1.fg0             -- loop iteration 1 output
  let round2 := divsteps31Round bias ⟨a3, cnt, b3, fg1, fg0⟩  -- loop iteration 2
  let a3 := round2.a3               -- loop iteration 2 output
  let cnt := round2.cnt             -- loop iteration 2 output
  let b3 := round2.b3               -- loop iteration 2 output
  let fg1 := round2.fg1             -- loop iteration 2 output
  let fg0 := round2.fg0             -- loop iteration 2 output
  let round3 := divsteps31Round bias ⟨a3, cnt, b3, fg1, fg0⟩  -- loop iteration 3
  let a3 := round3.a3               -- loop iteration 3 output
  let cnt := round3.cnt             -- loop iteration 3 output
  let b3 := round3.b3               -- loop iteration 3 output
  let fg1 := round3.fg1             -- loop iteration 3 output
  let fg0 := round3.fg0             -- loop iteration 3 output
  let round4 := divsteps31Round bias ⟨a3, cnt, b3, fg1, fg0⟩  -- loop iteration 4
  let a3 := round4.a3               -- loop iteration 4 output
  let cnt := round4.cnt             -- loop iteration 4 output
  let b3 := round4.b3               -- loop iteration 4 output
  let fg1 := round4.fg1             -- loop iteration 4 output
  let fg0 := round4.fg0             -- loop iteration 4 output
  let round5 := divsteps31Round bias ⟨a3, cnt, b3, fg1, fg0⟩  -- loop iteration 5
  let a3 := round5.a3               -- loop iteration 5 output
  let cnt := round5.cnt             -- loop iteration 5 output
  let b3 := round5.b3               -- loop iteration 5 output
  let fg1 := round5.fg1             -- loop iteration 5 output
  let fg0 := round5.fg0             -- loop iteration 5 output
  let round6 := divsteps31Round bias ⟨a3, cnt, b3, fg1, fg0⟩  -- loop iteration 6
  let a3 := round6.a3               -- loop iteration 6 output
  let cnt := round6.cnt             -- loop iteration 6 output
  let b3 := round6.b3               -- loop iteration 6 output
  let fg1 := round6.fg1             -- loop iteration 6 output
  let fg0 := round6.fg0             -- loop iteration 6 output
  let round7 := divsteps31Round bias ⟨a3, cnt, b3, fg1, fg0⟩  -- loop iteration 7
  let a3 := round7.a3               -- loop iteration 7 output
  let cnt := round7.cnt             -- loop iteration 7 output
  let b3 := round7.b3               -- loop iteration 7 output
  let fg1 := round7.fg1             -- loop iteration 7 output
  let fg0 := round7.fg0             -- loop iteration 7 output
  let round8 := divsteps31Round bias ⟨a3, cnt, b3, fg1, fg0⟩  -- loop iteration 8
  let a3 := round8.a3               -- loop iteration 8 output
  let cnt := round8.cnt             -- loop iteration 8 output
  let b3 := round8.b3               -- loop iteration 8 output
  let fg1 := round8.fg1             -- loop iteration 8 output
  let fg0 := round8.fg0             -- loop iteration 8 output
  let round9 := divsteps31Round bias ⟨a3, cnt, b3, fg1, fg0⟩  -- loop iteration 9
  let a3 := round9.a3               -- loop iteration 9 output
  let cnt := round9.cnt             -- loop iteration 9 output
  let b3 := round9.b3               -- loop iteration 9 output
  let fg1 := round9.fg1             -- loop iteration 9 output
  let fg0 := round9.fg0             -- loop iteration 9 output
  let round10 := divsteps31Round bias ⟨a3, cnt, b3, fg1, fg0⟩  -- loop iteration 10
  let a3 := round10.a3              -- loop iteration 10 output
  let cnt := round10.cnt            -- loop iteration 10 output
  let b3 := round10.b3              -- loop iteration 10 output
  let fg1 := round10.fg1            -- loop iteration 10 output
  let fg0 := round10.fg0            -- loop iteration 10 output
  let round11 := divsteps31Round bias ⟨a3, cnt, b3, fg1, fg0⟩  -- loop iteration 11
  let a3 := round11.a3              -- loop iteration 11 output
  let cnt := round11.cnt            -- loop iteration 11 output
  let b3 := round11.b3              -- loop iteration 11 output
  let fg1 := round11.fg1            -- loop iteration 11 output
  let fg0 := round11.fg0            -- loop iteration 11 output
  let round12 := divsteps31Round bias ⟨a3, cnt, b3, fg1, fg0⟩  -- loop iteration 12
  let a3 := round12.a3              -- loop iteration 12 output
  let cnt := round12.cnt            -- loop iteration 12 output
  let b3 := round12.b3              -- loop iteration 12 output
  let fg1 := round12.fg1            -- loop iteration 12 output
  let fg0 := round12.fg0            -- loop iteration 12 output
  let round13 := divsteps31Round bias ⟨a3, cnt, b3, fg1, fg0⟩  -- loop iteration 13
  let a3 := round13.a3              -- loop iteration 13 output
  let cnt := round13.cnt            -- loop iteration 13 output
  let b3 := round13.b3              -- loop iteration 13 output
  let fg1 := round13.fg1            -- loop iteration 13 output
  let fg0 := round13.fg0            -- loop iteration 13 output
  let round14 := divsteps31Round bias ⟨a3, cnt, b3, fg1, fg0⟩  -- loop iteration 14
  let a3 := round14.a3              -- loop iteration 14 output
  let cnt := round14.cnt            -- loop iteration 14 output
  let b3 := round14.b3              -- loop iteration 14 output
  let fg1 := round14.fg1            -- loop iteration 14 output
  let fg0 := round14.fg0            -- loop iteration 14 output
  let round15 := divsteps31Round bias ⟨a3, cnt, b3, fg1, fg0⟩  -- loop iteration 15
  let a3 := round15.a3              -- loop iteration 15 output
  let cnt := round15.cnt            -- loop iteration 15 output
  let b3 := round15.b3              -- loop iteration 15 output
  let fg1 := round15.fg1            -- loop iteration 15 output
  let fg0 := round15.fg0            -- loop iteration 15 output
  let round16 := divsteps31Round bias ⟨a3, cnt, b3, fg1, fg0⟩  -- loop iteration 16
  let a3 := round16.a3              -- loop iteration 16 output
  let cnt := round16.cnt            -- loop iteration 16 output
  let b3 := round16.b3              -- loop iteration 16 output
  let fg1 := round16.fg1            -- loop iteration 16 output
  let fg0 := round16.fg0            -- loop iteration 16 output
  let round17 := divsteps31Round bias ⟨a3, cnt, b3, fg1, fg0⟩  -- loop iteration 17
  let a3 := round17.a3              -- loop iteration 17 output
  let cnt := round17.cnt            -- loop iteration 17 output
  let b3 := round17.b3              -- loop iteration 17 output
  let fg1 := round17.fg1            -- loop iteration 17 output
  let fg0 := round17.fg0            -- loop iteration 17 output
  let round18 := divsteps31Round bias ⟨a3, cnt, b3, fg1, fg0⟩  -- loop iteration 18
  let a3 := round18.a3              -- loop iteration 18 output
  let cnt := round18.cnt            -- loop iteration 18 output
  let b3 := round18.b3              -- loop iteration 18 output
  let fg1 := round18.fg1            -- loop iteration 18 output
  let fg0 := round18.fg0            -- loop iteration 18 output
  let round19 := divsteps31Round bias ⟨a3, cnt, b3, fg1, fg0⟩  -- loop iteration 19
  let a3 := round19.a3              -- loop iteration 19 output
  let cnt := round19.cnt            -- loop iteration 19 output
  let b3 := round19.b3              -- loop iteration 19 output
  let fg1 := round19.fg1            -- loop iteration 19 output
  let fg0 := round19.fg0            -- loop iteration 19 output
  let round20 := divsteps31Round bias ⟨a3, cnt, b3, fg1, fg0⟩  -- loop iteration 20
  let a3 := round20.a3              -- loop iteration 20 output
  let cnt := round20.cnt            -- loop iteration 20 output
  let b3 := round20.b3              -- loop iteration 20 output
  let fg1 := round20.fg1            -- loop iteration 20 output
  let fg0 := round20.fg0            -- loop iteration 20 output
  let round21 := divsteps31Round bias ⟨a3, cnt, b3, fg1, fg0⟩  -- loop iteration 21
  let a3 := round21.a3              -- loop iteration 21 output
  let cnt := round21.cnt            -- loop iteration 21 output
  let b3 := round21.b3              -- loop iteration 21 output
  let fg1 := round21.fg1            -- loop iteration 21 output
  let fg0 := round21.fg0            -- loop iteration 21 output
  let round22 := divsteps31Round bias ⟨a3, cnt, b3, fg1, fg0⟩  -- loop iteration 22
  let a3 := round22.a3              -- loop iteration 22 output
  let cnt := round22.cnt            -- loop iteration 22 output
  let b3 := round22.b3              -- loop iteration 22 output
  let fg1 := round22.fg1            -- loop iteration 22 output
  let fg0 := round22.fg0            -- loop iteration 22 output
  let round23 := divsteps31Round bias ⟨a3, cnt, b3, fg1, fg0⟩  -- loop iteration 23
  let a3 := round23.a3              -- loop iteration 23 output
  let cnt := round23.cnt            -- loop iteration 23 output
  let b3 := round23.b3              -- loop iteration 23 output
  let fg1 := round23.fg1            -- loop iteration 23 output
  let fg0 := round23.fg0            -- loop iteration 23 output
  let round24 := divsteps31Round bias ⟨a3, cnt, b3, fg1, fg0⟩  -- loop iteration 24
  let a3 := round24.a3              -- loop iteration 24 output
  let cnt := round24.cnt            -- loop iteration 24 output
  let b3 := round24.b3              -- loop iteration 24 output
  let fg1 := round24.fg1            -- loop iteration 24 output
  let fg0 := round24.fg0            -- loop iteration 24 output
  let round25 := divsteps31Round bias ⟨a3, cnt, b3, fg1, fg0⟩  -- loop iteration 25
  let a3 := round25.a3              -- loop iteration 25 output
  let cnt := round25.cnt            -- loop iteration 25 output
  let b3 := round25.b3              -- loop iteration 25 output
  let fg1 := round25.fg1            -- loop iteration 25 output
  let fg0 := round25.fg0            -- loop iteration 25 output
  let round26 := divsteps31Round bias ⟨a3, cnt, b3, fg1, fg0⟩  -- loop iteration 26
  let a3 := round26.a3              -- loop iteration 26 output
  let cnt := round26.cnt            -- loop iteration 26 output
  let b3 := round26.b3              -- loop iteration 26 output
  let fg1 := round26.fg1            -- loop iteration 26 output
  let fg0 := round26.fg0            -- loop iteration 26 output
  let round27 := divsteps31Round bias ⟨a3, cnt, b3, fg1, fg0⟩  -- loop iteration 27
  let a3 := round27.a3              -- loop iteration 27 output
  let cnt := round27.cnt            -- loop iteration 27 output
  let b3 := round27.b3              -- loop iteration 27 output
  let fg1 := round27.fg1            -- loop iteration 27 output
  let fg0 := round27.fg0            -- loop iteration 27 output
  let round28 := divsteps31Round bias ⟨a3, cnt, b3, fg1, fg0⟩  -- loop iteration 28
  let a3 := round28.a3              -- loop iteration 28 output
  let cnt := round28.cnt            -- loop iteration 28 output
  let b3 := round28.b3              -- loop iteration 28 output
  let fg1 := round28.fg1            -- loop iteration 28 output
  let fg0 := round28.fg0            -- loop iteration 28 output
  let round29 := divsteps31Round bias ⟨a3, cnt, b3, fg1, fg0⟩  -- loop iteration 29
  let a3 := round29.a3              -- loop iteration 29 output
  let cnt := round29.cnt            -- loop iteration 29 output
  let b3 := round29.b3              -- loop iteration 29 output
  let fg1 := round29.fg1            -- loop iteration 29 output
  let fg0 := round29.fg0            -- loop iteration 29 output
  let round30 := divsteps31Round bias ⟨a3, cnt, b3, fg1, fg0⟩  -- loop iteration 30
  let a3 := round30.a3              -- loop iteration 30 output
  let cnt := round30.cnt            -- loop iteration 30 output
  let b3 := round30.b3              -- loop iteration 30 output
  let fg1 := round30.fg1            -- loop iteration 30 output
  let fg0 := round30.fg0            -- loop iteration 30 output
  let round31 := divsteps31Round bias ⟨a3, cnt, b3, fg1, fg0⟩  -- loop iteration 31
  let fg1 := round31.fg1            -- loop iteration 31 output
  let fg0 := round31.fg0            -- loop iteration 31 output
  let bias := ubfx bias 0 32        -- ubfx bias,bias,#0,#32
  let f0 := ubfx fg0 0 32           -- ubfx f0,fg0,#0,#32
  let g0 := ubfx fg0 32 32          -- ubfx g0,fg0,#32,#32
  let f1 := ubfx fg1 0 32           -- ubfx f1,fg1,#0,#32
  let g1 := ubfx fg1 32 32          -- ubfx g1,fg1,#32,#32
  let f0 := sub f0 bias             -- sub f0,f0,bias
  let g0 := sub g0 bias             -- sub g0,g0,bias
  let f1 := sub f1 bias             -- sub f1,f1,bias
  let g1 := sub g1 bias             -- sub g1,g1,bias
  ⟨f0, g0, f1, g1⟩

/-- The signed fixed-width matrix-row update of one GCD state, shifted by 31 bits. -/
def updateAB (a b : Limbs) (f g : Nat) : UpdateABResult :=
  let a0 := a.l0                    -- argument
  let a1 := a.l1                    -- argument
  let a2 := a.l2                    -- argument
  let a3 := a.l3                    -- argument
  let b0 := b.l0                    -- argument
  let b1 := b.l1                    -- argument
  let b2 := b.l2                    -- argument
  let b3 := b.l3                    -- argument
  let f := f                        -- argument
  let g := g                        -- argument
  let t5 := asr f 63                -- asr t5,f,#63
  let t6 := eor f t5                -- eor t6,f,t5
  let a0 := eor a0 t5               -- eor a0,a0,t5
  let t6 := sub t6 t5               -- sub t6,t6,t5
  let a1 := eor a1 t5               -- eor a1,a1,t5
  let s := addc a0 (lsr t5 63) 0    -- adds a0,a0,t5,lsr #63
  let a0 := s.1                     --   `-> a0
  let c := s.2                      --   `-> carry
  let a2 := eor a2 t5               -- eor a2,a2,t5
  let s := addc a1 0 c              -- adcs a1,a1,xzr
  let a1 := s.1                     --   `-> a1
  let c := s.2                      --   `-> carry
  let a3 := eor a3 t5               -- eor a3,a3,t5
  let t0 := umulh a0 t6             -- umulh t0,a0,t6
  let s := addc a2 0 c              -- adcs a2,a2,xzr
  let a2 := s.1                     --   `-> a2
  let c := s.2                      --   `-> carry
  let t1 := umulh a1 t6             -- umulh t1,a1,t6
  let a3 := (addc a3 0 c).1         -- adc a3,a3,xzr
  let t2 := umulh a2 t6             -- umulh t2,a2,t6
  let t5 := bitAnd t5 t6            -- and t5,t5,t6
  let t3 := umulh a3 t6             -- umulh t3,a3,t6
  let t5 := neg t5                  -- neg t5,t5
  let a0 := mulLo a0 t6             -- mul a0,a0,t6
  let a1 := mulLo a1 t6             -- mul a1,a1,t6
  let a2 := mulLo a2 t6             -- mul a2,a2,t6
  let s := addc a1 t0 0             -- adds a1,a1,t0
  let a1 := s.1                     --   `-> a1
  let c := s.2                      --   `-> carry
  let a3 := mulLo a3 t6             -- mul a3,a3,t6
  let s := addc a2 t1 c             -- adcs a2,a2,t1
  let a2 := s.1                     --   `-> a2
  let c := s.2                      --   `-> carry
  let s := addc a3 t2 c             -- adcs a3,a3,t2
  let a3 := s.1                     --   `-> a3
  let c := s.2                      --   `-> carry
  let t3 := (addc t3 t5 c).1        -- adc t3,t3,t5
  let t5 := asr g 63                -- asr t5,g,#63
  let t6 := eor g t5                -- eor t6,g,t5
  let b0 := eor b0 t5               -- eor b0,b0,t5
  let t6 := sub t6 t5               -- sub t6,t6,t5
  let b1 := eor b1 t5               -- eor b1,b1,t5
  let s := addc b0 (lsr t5 63) 0    -- adds b0,b0,t5,lsr #63
  let b0 := s.1                     --   `-> b0
  let c := s.2                      --   `-> carry
  let b2 := eor b2 t5               -- eor b2,b2,t5
  let s := addc b1 0 c              -- adcs b1,b1,xzr
  let b1 := s.1                     --   `-> b1
  let c := s.2                      --   `-> carry
  let b3 := eor b3 t5               -- eor b3,b3,t5
  let t0 := umulh b0 t6             -- umulh t0,b0,t6
  let s := addc b2 0 c              -- adcs b2,b2,xzr
  let b2 := s.1                     --   `-> b2
  let c := s.2                      --   `-> carry
  let t1 := umulh b1 t6             -- umulh t1,b1,t6
  let b3 := (addc b3 0 c).1         -- adc b3,b3,xzr
  let t2 := umulh b2 t6             -- umulh t2,b2,t6
  let t5 := bitAnd t5 t6            -- and t5,t5,t6
  let t4 := umulh b3 t6             -- umulh t4,b3,t6
  let t5 := neg t5                  -- neg t5,t5
  let b0 := mulLo b0 t6             -- mul b0,b0,t6
  let b1 := mulLo b1 t6             -- mul b1,b1,t6
  let b2 := mulLo b2 t6             -- mul b2,b2,t6
  let s := addc b1 t0 0             -- adds b1,b1,t0
  let b1 := s.1                     --   `-> b1
  let c := s.2                      --   `-> carry
  let b3 := mulLo b3 t6             -- mul b3,b3,t6
  let s := addc b2 t1 c             -- adcs b2,b2,t1
  let b2 := s.1                     --   `-> b2
  let c := s.2                      --   `-> carry
  let s := addc b3 t2 c             -- adcs b3,b3,t2
  let b3 := s.1                     --   `-> b3
  let c := s.2                      --   `-> carry
  let t4 := (addc t4 t5 c).1        -- adc t4,t4,t5
  let s := addc a0 b0 0             -- adds a0,a0,b0
  let a0 := s.1                     --   `-> a0
  let c := s.2                      --   `-> carry
  let s := addc a1 b1 c             -- adcs a1,a1,b1
  let a1 := s.1                     --   `-> a1
  let c := s.2                      --   `-> carry
  let s := addc a2 b2 c             -- adcs a2,a2,b2
  let a2 := s.1                     --   `-> a2
  let c := s.2                      --   `-> carry
  let s := addc a3 b3 c             -- adcs a3,a3,b3
  let a3 := s.1                     --   `-> a3
  let c := s.2                      --   `-> carry
  let b0 := (addc t3 t4 c).1        -- adc b0,t3,t4
  let a0 := extr a1 a0 31           -- extr a0,a1,a0,#31
  let a1 := extr a2 a1 31           -- extr a1,a2,a1,#31
  let a2 := extr a3 a2 31           -- extr a2,a3,a2,#31
  let t4 := asr b0 63               -- asr t4,b0,#63
  let a3 := extr b0 a3 31           -- extr a3,b0,a3,#31
  let a0 := eor a0 t4               -- eor a0,a0,t4
  let a1 := eor a1 t4               -- eor a1,a1,t4
  let s := addc a0 (lsr t4 63) 0    -- adds a0,a0,t4,lsr #63
  let a0 := s.1                     --   `-> a0
  let c := s.2                      --   `-> carry
  let a2 := eor a2 t4               -- eor a2,a2,t4
  let s := addc a1 0 c              -- adcs a1,a1,xzr
  let a1 := s.1                     --   `-> a1
  let c := s.2                      --   `-> carry
  let a3 := eor a3 t4               -- eor a3,a3,t4
  let s := addc a2 0 c              -- adcs a2,a2,xzr
  let a2 := s.1                     --   `-> a2
  let c := s.2                      --   `-> carry
  let a3 := (addc a3 0 c).1         -- adc a3,a3,xzr
  let f := eor f t4                 -- eor f,f,t4
  let g := eor g t4                 -- eor g,g,t4
  let f := sub f t4                 -- sub f,f,t4
  let g := sub g t4                 -- sub g,g,t4
  ⟨⟨a0, a1, a2, a3⟩, f, g⟩

/-- Addition of two nine-word coefficient bitpatterns modulo 2^576. -/
def addWords (lhs rhs : WideLimbs) : WideLimbs :=
  let o0 := lhs.l0                  -- argument
  let o1 := lhs.l1                  -- argument
  let o2 := lhs.l2                  -- argument
  let o3 := lhs.l3                  -- argument
  let o4 := lhs.l4                  -- argument
  let o5 := lhs.l5                  -- argument
  let o6 := lhs.l6                  -- argument
  let o7 := lhs.l7                  -- argument
  let o8 := lhs.l8                  -- argument
  let r0 := rhs.l0                  -- argument
  let r1 := rhs.l1                  -- argument
  let r2 := rhs.l2                  -- argument
  let r3 := rhs.l3                  -- argument
  let r4 := rhs.l4                  -- argument
  let r5 := rhs.l5                  -- argument
  let r6 := rhs.l6                  -- argument
  let r7 := rhs.l7                  -- argument
  let r8 := rhs.l8                  -- argument
  let s := addc o0 r0 0             -- adds o0,o0,r0
  let o0 := s.1                     --   `-> o0
  let c := s.2                      --   `-> carry
  let s := addc o1 r1 c             -- adcs o1,o1,r1
  let o1 := s.1                     --   `-> o1
  let c := s.2                      --   `-> carry
  let s := addc o2 r2 c             -- adcs o2,o2,r2
  let o2 := s.1                     --   `-> o2
  let c := s.2                      --   `-> carry
  let s := addc o3 r3 c             -- adcs o3,o3,r3
  let o3 := s.1                     --   `-> o3
  let c := s.2                      --   `-> carry
  let s := addc o4 r4 c             -- adcs o4,o4,r4
  let o4 := s.1                     --   `-> o4
  let c := s.2                      --   `-> carry
  let s := addc o5 r5 c             -- adcs o5,o5,r5
  let o5 := s.1                     --   `-> o5
  let c := s.2                      --   `-> carry
  let s := addc o6 r6 c             -- adcs o6,o6,r6
  let o6 := s.1                     --   `-> o6
  let c := s.2                      --   `-> carry
  let s := addc o7 r7 c             -- adcs o7,o7,r7
  let o7 := s.1                     --   `-> o7
  let c := s.2                      --   `-> carry
  let o8 := (addc o8 r8 c).1        -- adc o8,o8,r8
  ⟨o0, o1, o2, o3, o4, o5, o6, o7, o8⟩

/-- The magnitude and conditionally negated limbs produced by the first contiguous source phase of
`mulSigned`. -/
structure MulSignedPrepared where
  l0 : Nat
  l1 : Nat
  l2 : Nat
  l3 : Nat
  l4 : Nat
  l5 : Nat
  l6 : Nat
  l7 : Nat
  l8 : Nat
  magnitude : Nat
  deriving DecidableEq, Repr

namespace MulSignedPrepared

/-- The register bounds supplied by a proof of the prepare/sign-negation phase. -/
def Bounded (s : MulSignedPrepared) : Prop :=
  s.l0 < 2^64 ∧ s.l1 < 2^64 ∧ s.l2 < 2^64 ∧ s.l3 < 2^64 ∧ s.l4 < 2^64 ∧
  s.l5 < 2^64 ∧ s.l6 < 2^64 ∧ s.l7 < 2^64 ∧ s.l8 < 2^64 ∧ s.magnitude < 2^64

end MulSignedPrepared

/-- The low product limb and carry produced by a non-final contiguous product phase of
`mulSigned`. -/
structure MulSignedProduct where
  low : Nat
  carry : Nat
  deriving DecidableEq, Repr

namespace MulSignedProduct

/-- The register bounds supplied by each non-final product-phase proof. -/
def Bounded (s : MulSignedProduct) : Prop :=
  s.low < 2^64 ∧ s.carry < 2^64

end MulSignedProduct

/-- The low limb produced by the final contiguous product phase of `mulSigned`. -/
structure MulSignedLastProduct where
  low : Nat
  deriving DecidableEq, Repr

namespace MulSignedLastProduct

/-- The register bound supplied by the final product-phase proof. -/
def Bounded (s : MulSignedLastProduct) : Prop :=
  s.low < 2^64

end MulSignedLastProduct

/-- The contiguous scalar-magnitude and conditional-negation phase of `mulSigned`, copied from
source PCs 0 through 20. -/
def mulSignedPrepare (value : WideLimbs) (scalar : Nat) : MulSignedPrepared :=
  let scalar := scalar              -- argument
  let o0 := value.l0                -- argument
  let o1 := value.l1                -- argument
  let o2 := value.l2                -- argument
  let o3 := value.l3                -- argument
  let o4 := value.l4                -- argument
  let o5 := value.l5                -- argument
  let o6 := value.l6                -- argument
  let o7 := value.l7                -- argument
  let o8 := value.l8                -- argument
  let sign := asr scalar 63         -- asr sign,scalar,#63
  let mag := eor scalar sign        -- eor mag,scalar,sign
  let mag := sub mag sign           -- sub mag,mag,sign
  let o0 := eor o0 sign             -- eor o0,o0,sign
  let o1 := eor o1 sign             -- eor o1,o1,sign
  let o2 := eor o2 sign             -- eor o2,o2,sign
  let o3 := eor o3 sign             -- eor o3,o3,sign
  let o4 := eor o4 sign             -- eor o4,o4,sign
  let o5 := eor o5 sign             -- eor o5,o5,sign
  let o6 := eor o6 sign             -- eor o6,o6,sign
  let o7 := eor o7 sign             -- eor o7,o7,sign
  let o8 := eor o8 sign             -- eor o8,o8,sign
  let s := addc o0 (lsr sign 63) 0  -- adds o0,o0,sign,lsr #63
  let o0 := s.1                     --   `-> o0
  let c := s.2                      --   `-> carry
  let s := addc o1 0 c              -- adcs o1,o1,xzr
  let o1 := s.1                     --   `-> o1
  let c := s.2                      --   `-> carry
  let s := addc o2 0 c              -- adcs o2,o2,xzr
  let o2 := s.1                     --   `-> o2
  let c := s.2                      --   `-> carry
  let s := addc o3 0 c              -- adcs o3,o3,xzr
  let o3 := s.1                     --   `-> o3
  let c := s.2                      --   `-> carry
  let s := addc o4 0 c              -- adcs o4,o4,xzr
  let o4 := s.1                     --   `-> o4
  let c := s.2                      --   `-> carry
  let s := addc o5 0 c              -- adcs o5,o5,xzr
  let o5 := s.1                     --   `-> o5
  let c := s.2                      --   `-> carry
  let s := addc o6 0 c              -- adcs o6,o6,xzr
  let o6 := s.1                     --   `-> o6
  let c := s.2                      --   `-> carry
  let s := addc o7 0 c              -- adcs o7,o7,xzr
  let o7 := s.1                     --   `-> o7
  let c := s.2                      --   `-> carry
  let o8 := (addc o8 0 c).1         -- adc o8,o8,xzr
  ⟨o0, o1, o2, o3, o4, o5, o6, o7, o8, mag⟩

/-- The first contiguous product phase of `mulSigned`: multiply limb zero and retain its high word
as the carry. -/
def mulSignedFirst (limb magnitude : Nat) : MulSignedProduct :=
  let o0 := limb                    -- phase argument
  let mag := magnitude              -- phase argument
  let carry := umulh o0 mag         -- umulh carry,o0,mag
  let o0 := mulLo o0 mag            -- mul o0,o0,mag
  ⟨o0, carry⟩

/-- One middle contiguous product phase of `mulSigned`. All seven unrolled source phases are checked
to have this binding IR after source-limb normalization. -/
def mulSignedRound (limb magnitude productCarry : Nat) : MulSignedProduct :=
  let o1 := limb                    -- phase argument
  let mag := magnitude              -- phase argument
  let carry := productCarry         -- phase argument
  let hi := umulh o1 mag            -- umulh hi,o1,mag
  let o1 := mulLo o1 mag            -- mul o1,o1,mag
  let s := addc o1 carry 0          -- adds o1,o1,carry
  let o1 := s.1                     --   `-> o1
  let c := s.2                      --   `-> carry
  let carry := (addc hi 0 c).1      -- adc carry,hi,xzr
  ⟨o1, carry⟩

/-- The final contiguous product phase of `mulSigned`, with overflow above bit 575 discarded exactly
as in the source. -/
def mulSignedLast (limb magnitude productCarry : Nat) : MulSignedLastProduct :=
  let o8 := limb                    -- phase argument
  let mag := magnitude              -- phase argument
  let carry := productCarry         -- phase argument
  let o8 := mulLo o8 mag            -- mul o8,o8,mag
  let o8 := add o8 carry            -- add o8,o8,carry
  ⟨o8⟩

/-- Multiplication of a nine-word signed bitpattern by a signed scalar bitpattern modulo 2^576. -/
def mulSigned (value : WideLimbs) (scalar : Nat) : WideLimbs :=
  let prepared := mulSignedPrepare value scalar  -- factored prepare/sign-negation phase
  let o0 := prepared.l0             -- prepare/sign-negation phase output
  let o1 := prepared.l1             -- prepare/sign-negation phase output
  let o2 := prepared.l2             -- prepare/sign-negation phase output
  let o3 := prepared.l3             -- prepare/sign-negation phase output
  let o4 := prepared.l4             -- prepare/sign-negation phase output
  let o5 := prepared.l5             -- prepare/sign-negation phase output
  let o6 := prepared.l6             -- prepare/sign-negation phase output
  let o7 := prepared.l7             -- prepare/sign-negation phase output
  let o8 := prepared.l8             -- prepare/sign-negation phase output
  let mag := prepared.magnitude     -- prepare/sign-negation phase output
  let firstProduct := mulSignedFirst o0 mag  -- factored first product phase
  let o0 := firstProduct.low        -- first product phase output
  let carry := firstProduct.carry   -- first product phase output
  let round1 := mulSignedRound o1 mag carry  -- factored product round 1
  let o1 := round1.low              -- product round 1 output
  let carry := round1.carry         -- product round 1 output
  let round2 := mulSignedRound o2 mag carry  -- factored product round 2
  let o2 := round2.low              -- product round 2 output
  let carry := round2.carry         -- product round 2 output
  let round3 := mulSignedRound o3 mag carry  -- factored product round 3
  let o3 := round3.low              -- product round 3 output
  let carry := round3.carry         -- product round 3 output
  let round4 := mulSignedRound o4 mag carry  -- factored product round 4
  let o4 := round4.low              -- product round 4 output
  let carry := round4.carry         -- product round 4 output
  let round5 := mulSignedRound o5 mag carry  -- factored product round 5
  let o5 := round5.low              -- product round 5 output
  let carry := round5.carry         -- product round 5 output
  let round6 := mulSignedRound o6 mag carry  -- factored product round 6
  let o6 := round6.low              -- product round 6 output
  let carry := round6.carry         -- product round 6 output
  let round7 := mulSignedRound o7 mag carry  -- factored product round 7
  let o7 := round7.low              -- product round 7 output
  let carry := round7.carry         -- product round 7 output
  let lastProduct := mulSignedLast o8 mag carry  -- factored final product phase
  let o8 := lastProduct.low         -- final product phase output
  ⟨o0, o1, o2, o3, o4, o5, o6, o7, o8⟩

/-- Registers carried by one checked iteration of `divsteps47`. -/
structure Divsteps47State where
  a : Nat
  cnt : Nat
  b : Nat
  f0 : Nat
  g0 : Nat
  f1 : Nat
  g1 : Nat
  deriving DecidableEq, Repr
/-- One source loop iteration of `divsteps47`. The wrapper validates and calls it exactly 47 times.
-/
def divsteps47Round (acc : Divsteps47State) : Divsteps47State :=
  let a := acc.a                    -- loop state argument
  let cnt := acc.cnt                -- loop state argument
  let b := acc.b                    -- loop state argument
  let f0 := acc.f0                  -- loop state argument
  let g0 := acc.g0                  -- loop state argument
  let f1 := acc.f1                  -- loop state argument
  let g1 := acc.g1                  -- loop state argument
  let odd := sbfx a 0 1             -- sbfx odd,a,#0,#1
  let cnt := sub cnt 1              -- sub cnt,cnt,#1
  let t0 := bitAnd b odd            -- and t0,b,odd
  let t1 := sub b a                 -- sub t1,b,a
  let s := subc a t0 1              -- subs t2,a,t0
  let t2 := s.1                     --   `-> t2
  let c := s.2                      --   `-> carry
  let t0 := f0                      -- mov t0,f0
  let b := cselCs c b a             -- csel b,b,a,hs
  let a := cselCs c t2 t1           -- csel a,t2,t1,hs
  let t1 := g0                      -- mov t1,g0
  let f0 := cselCs c f0 f1          -- csel f0,f0,f1,hs
  let f1 := cselCs c f1 t0          -- csel f1,f1,t0,hs
  let g0 := cselCs c g0 g1          -- csel g0,g0,g1,hs
  let g1 := cselCs c g1 t1          -- csel g1,g1,t1,hs
  let a := lsr a 1                  -- lsr a,a,#1
  let t0 := bitAnd f1 odd           -- and t0,f1,odd
  let t1 := bitAnd g1 odd           -- and t1,g1,odd
  let f1 := add f1 f1               -- add f1,f1,f1
  let g1 := add g1 g1               -- add g1,g1,g1
  let f0 := sub f0 t0               -- sub f0,f0,t0
  let g0 := sub g0 t1               -- sub g0,g0,t1
  ⟨a, cnt, b, f0, g0, f1, g1⟩

/-- The second transition row after the checked fixed-count final 47 low-limb steps. -/
def divsteps47 (a b : Nat) : InvertRow :=
  let a' := a                       -- argument
  let b' := b                       -- argument
  let cnt := 47                     -- argument
  let f0 := 1                       -- argument
  let g0 := 0                       -- argument
  let f1 := 0                       -- argument
  let g1 := 1                       -- argument
  let round1 := divsteps47Round ⟨a', cnt, b', f0, g0, f1, g1⟩  -- loop iteration 1
  let a_1 := round1.a               -- loop iteration 1 output
  let cnt_1 := round1.cnt           -- loop iteration 1 output
  let b_1 := round1.b               -- loop iteration 1 output
  let f0_1 := round1.f0             -- loop iteration 1 output
  let g0_1 := round1.g0             -- loop iteration 1 output
  let f1_1 := round1.f1             -- loop iteration 1 output
  let g1_1 := round1.g1             -- loop iteration 1 output
  let round2 := divsteps47Round ⟨a_1, cnt_1, b_1, f0_1, g0_1, f1_1, g1_1⟩  -- loop iteration 2
  let a_2 := round2.a               -- loop iteration 2 output
  let cnt_2 := round2.cnt           -- loop iteration 2 output
  let b_2 := round2.b               -- loop iteration 2 output
  let f0_2 := round2.f0             -- loop iteration 2 output
  let g0_2 := round2.g0             -- loop iteration 2 output
  let f1_2 := round2.f1             -- loop iteration 2 output
  let g1_2 := round2.g1             -- loop iteration 2 output
  let round3 := divsteps47Round ⟨a_2, cnt_2, b_2, f0_2, g0_2, f1_2, g1_2⟩  -- loop iteration 3
  let a_3 := round3.a               -- loop iteration 3 output
  let cnt_3 := round3.cnt           -- loop iteration 3 output
  let b_3 := round3.b               -- loop iteration 3 output
  let f0_3 := round3.f0             -- loop iteration 3 output
  let g0_3 := round3.g0             -- loop iteration 3 output
  let f1_3 := round3.f1             -- loop iteration 3 output
  let g1_3 := round3.g1             -- loop iteration 3 output
  let round4 := divsteps47Round ⟨a_3, cnt_3, b_3, f0_3, g0_3, f1_3, g1_3⟩  -- loop iteration 4
  let a_4 := round4.a               -- loop iteration 4 output
  let cnt_4 := round4.cnt           -- loop iteration 4 output
  let b_4 := round4.b               -- loop iteration 4 output
  let f0_4 := round4.f0             -- loop iteration 4 output
  let g0_4 := round4.g0             -- loop iteration 4 output
  let f1_4 := round4.f1             -- loop iteration 4 output
  let g1_4 := round4.g1             -- loop iteration 4 output
  let round5 := divsteps47Round ⟨a_4, cnt_4, b_4, f0_4, g0_4, f1_4, g1_4⟩  -- loop iteration 5
  let a_5 := round5.a               -- loop iteration 5 output
  let cnt_5 := round5.cnt           -- loop iteration 5 output
  let b_5 := round5.b               -- loop iteration 5 output
  let f0_5 := round5.f0             -- loop iteration 5 output
  let g0_5 := round5.g0             -- loop iteration 5 output
  let f1_5 := round5.f1             -- loop iteration 5 output
  let g1_5 := round5.g1             -- loop iteration 5 output
  let round6 := divsteps47Round ⟨a_5, cnt_5, b_5, f0_5, g0_5, f1_5, g1_5⟩  -- loop iteration 6
  let a_6 := round6.a               -- loop iteration 6 output
  let cnt_6 := round6.cnt           -- loop iteration 6 output
  let b_6 := round6.b               -- loop iteration 6 output
  let f0_6 := round6.f0             -- loop iteration 6 output
  let g0_6 := round6.g0             -- loop iteration 6 output
  let f1_6 := round6.f1             -- loop iteration 6 output
  let g1_6 := round6.g1             -- loop iteration 6 output
  let round7 := divsteps47Round ⟨a_6, cnt_6, b_6, f0_6, g0_6, f1_6, g1_6⟩  -- loop iteration 7
  let a_7 := round7.a               -- loop iteration 7 output
  let cnt_7 := round7.cnt           -- loop iteration 7 output
  let b_7 := round7.b               -- loop iteration 7 output
  let f0_7 := round7.f0             -- loop iteration 7 output
  let g0_7 := round7.g0             -- loop iteration 7 output
  let f1_7 := round7.f1             -- loop iteration 7 output
  let g1_7 := round7.g1             -- loop iteration 7 output
  let round8 := divsteps47Round ⟨a_7, cnt_7, b_7, f0_7, g0_7, f1_7, g1_7⟩  -- loop iteration 8
  let a_8 := round8.a               -- loop iteration 8 output
  let cnt_8 := round8.cnt           -- loop iteration 8 output
  let b_8 := round8.b               -- loop iteration 8 output
  let f0_8 := round8.f0             -- loop iteration 8 output
  let g0_8 := round8.g0             -- loop iteration 8 output
  let f1_8 := round8.f1             -- loop iteration 8 output
  let g1_8 := round8.g1             -- loop iteration 8 output
  let round9 := divsteps47Round ⟨a_8, cnt_8, b_8, f0_8, g0_8, f1_8, g1_8⟩  -- loop iteration 9
  let a_9 := round9.a               -- loop iteration 9 output
  let cnt_9 := round9.cnt           -- loop iteration 9 output
  let b_9 := round9.b               -- loop iteration 9 output
  let f0_9 := round9.f0             -- loop iteration 9 output
  let g0_9 := round9.g0             -- loop iteration 9 output
  let f1_9 := round9.f1             -- loop iteration 9 output
  let g1_9 := round9.g1             -- loop iteration 9 output
  let round10 := divsteps47Round ⟨a_9, cnt_9, b_9, f0_9, g0_9, f1_9, g1_9⟩  -- loop iteration 10
  let a_10 := round10.a             -- loop iteration 10 output
  let cnt_10 := round10.cnt         -- loop iteration 10 output
  let b_10 := round10.b             -- loop iteration 10 output
  let f0_10 := round10.f0           -- loop iteration 10 output
  let g0_10 := round10.g0           -- loop iteration 10 output
  let f1_10 := round10.f1           -- loop iteration 10 output
  let g1_10 := round10.g1           -- loop iteration 10 output
  let round11 := divsteps47Round ⟨a_10, cnt_10, b_10, f0_10, g0_10, f1_10, g1_10⟩  -- loop iteration 11
  let a_11 := round11.a             -- loop iteration 11 output
  let cnt_11 := round11.cnt         -- loop iteration 11 output
  let b_11 := round11.b             -- loop iteration 11 output
  let f0_11 := round11.f0           -- loop iteration 11 output
  let g0_11 := round11.g0           -- loop iteration 11 output
  let f1_11 := round11.f1           -- loop iteration 11 output
  let g1_11 := round11.g1           -- loop iteration 11 output
  let round12 := divsteps47Round ⟨a_11, cnt_11, b_11, f0_11, g0_11, f1_11, g1_11⟩  -- loop iteration 12
  let a_12 := round12.a             -- loop iteration 12 output
  let cnt_12 := round12.cnt         -- loop iteration 12 output
  let b_12 := round12.b             -- loop iteration 12 output
  let f0_12 := round12.f0           -- loop iteration 12 output
  let g0_12 := round12.g0           -- loop iteration 12 output
  let f1_12 := round12.f1           -- loop iteration 12 output
  let g1_12 := round12.g1           -- loop iteration 12 output
  let round13 := divsteps47Round ⟨a_12, cnt_12, b_12, f0_12, g0_12, f1_12, g1_12⟩  -- loop iteration 13
  let a_13 := round13.a             -- loop iteration 13 output
  let cnt_13 := round13.cnt         -- loop iteration 13 output
  let b_13 := round13.b             -- loop iteration 13 output
  let f0_13 := round13.f0           -- loop iteration 13 output
  let g0_13 := round13.g0           -- loop iteration 13 output
  let f1_13 := round13.f1           -- loop iteration 13 output
  let g1_13 := round13.g1           -- loop iteration 13 output
  let round14 := divsteps47Round ⟨a_13, cnt_13, b_13, f0_13, g0_13, f1_13, g1_13⟩  -- loop iteration 14
  let a_14 := round14.a             -- loop iteration 14 output
  let cnt_14 := round14.cnt         -- loop iteration 14 output
  let b_14 := round14.b             -- loop iteration 14 output
  let f0_14 := round14.f0           -- loop iteration 14 output
  let g0_14 := round14.g0           -- loop iteration 14 output
  let f1_14 := round14.f1           -- loop iteration 14 output
  let g1_14 := round14.g1           -- loop iteration 14 output
  let round15 := divsteps47Round ⟨a_14, cnt_14, b_14, f0_14, g0_14, f1_14, g1_14⟩  -- loop iteration 15
  let a_15 := round15.a             -- loop iteration 15 output
  let cnt_15 := round15.cnt         -- loop iteration 15 output
  let b_15 := round15.b             -- loop iteration 15 output
  let f0_15 := round15.f0           -- loop iteration 15 output
  let g0_15 := round15.g0           -- loop iteration 15 output
  let f1_15 := round15.f1           -- loop iteration 15 output
  let g1_15 := round15.g1           -- loop iteration 15 output
  let round16 := divsteps47Round ⟨a_15, cnt_15, b_15, f0_15, g0_15, f1_15, g1_15⟩  -- loop iteration 16
  let a_16 := round16.a             -- loop iteration 16 output
  let cnt_16 := round16.cnt         -- loop iteration 16 output
  let b_16 := round16.b             -- loop iteration 16 output
  let f0_16 := round16.f0           -- loop iteration 16 output
  let g0_16 := round16.g0           -- loop iteration 16 output
  let f1_16 := round16.f1           -- loop iteration 16 output
  let g1_16 := round16.g1           -- loop iteration 16 output
  let round17 := divsteps47Round ⟨a_16, cnt_16, b_16, f0_16, g0_16, f1_16, g1_16⟩  -- loop iteration 17
  let a_17 := round17.a             -- loop iteration 17 output
  let cnt_17 := round17.cnt         -- loop iteration 17 output
  let b_17 := round17.b             -- loop iteration 17 output
  let f0_17 := round17.f0           -- loop iteration 17 output
  let g0_17 := round17.g0           -- loop iteration 17 output
  let f1_17 := round17.f1           -- loop iteration 17 output
  let g1_17 := round17.g1           -- loop iteration 17 output
  let round18 := divsteps47Round ⟨a_17, cnt_17, b_17, f0_17, g0_17, f1_17, g1_17⟩  -- loop iteration 18
  let a_18 := round18.a             -- loop iteration 18 output
  let cnt_18 := round18.cnt         -- loop iteration 18 output
  let b_18 := round18.b             -- loop iteration 18 output
  let f0_18 := round18.f0           -- loop iteration 18 output
  let g0_18 := round18.g0           -- loop iteration 18 output
  let f1_18 := round18.f1           -- loop iteration 18 output
  let g1_18 := round18.g1           -- loop iteration 18 output
  let round19 := divsteps47Round ⟨a_18, cnt_18, b_18, f0_18, g0_18, f1_18, g1_18⟩  -- loop iteration 19
  let a_19 := round19.a             -- loop iteration 19 output
  let cnt_19 := round19.cnt         -- loop iteration 19 output
  let b_19 := round19.b             -- loop iteration 19 output
  let f0_19 := round19.f0           -- loop iteration 19 output
  let g0_19 := round19.g0           -- loop iteration 19 output
  let f1_19 := round19.f1           -- loop iteration 19 output
  let g1_19 := round19.g1           -- loop iteration 19 output
  let round20 := divsteps47Round ⟨a_19, cnt_19, b_19, f0_19, g0_19, f1_19, g1_19⟩  -- loop iteration 20
  let a_20 := round20.a             -- loop iteration 20 output
  let cnt_20 := round20.cnt         -- loop iteration 20 output
  let b_20 := round20.b             -- loop iteration 20 output
  let f0_20 := round20.f0           -- loop iteration 20 output
  let g0_20 := round20.g0           -- loop iteration 20 output
  let f1_20 := round20.f1           -- loop iteration 20 output
  let g1_20 := round20.g1           -- loop iteration 20 output
  let round21 := divsteps47Round ⟨a_20, cnt_20, b_20, f0_20, g0_20, f1_20, g1_20⟩  -- loop iteration 21
  let a_21 := round21.a             -- loop iteration 21 output
  let cnt_21 := round21.cnt         -- loop iteration 21 output
  let b_21 := round21.b             -- loop iteration 21 output
  let f0_21 := round21.f0           -- loop iteration 21 output
  let g0_21 := round21.g0           -- loop iteration 21 output
  let f1_21 := round21.f1           -- loop iteration 21 output
  let g1_21 := round21.g1           -- loop iteration 21 output
  let round22 := divsteps47Round ⟨a_21, cnt_21, b_21, f0_21, g0_21, f1_21, g1_21⟩  -- loop iteration 22
  let a_22 := round22.a             -- loop iteration 22 output
  let cnt_22 := round22.cnt         -- loop iteration 22 output
  let b_22 := round22.b             -- loop iteration 22 output
  let f0_22 := round22.f0           -- loop iteration 22 output
  let g0_22 := round22.g0           -- loop iteration 22 output
  let f1_22 := round22.f1           -- loop iteration 22 output
  let g1_22 := round22.g1           -- loop iteration 22 output
  let round23 := divsteps47Round ⟨a_22, cnt_22, b_22, f0_22, g0_22, f1_22, g1_22⟩  -- loop iteration 23
  let a_23 := round23.a             -- loop iteration 23 output
  let cnt_23 := round23.cnt         -- loop iteration 23 output
  let b_23 := round23.b             -- loop iteration 23 output
  let f0_23 := round23.f0           -- loop iteration 23 output
  let g0_23 := round23.g0           -- loop iteration 23 output
  let f1_23 := round23.f1           -- loop iteration 23 output
  let g1_23 := round23.g1           -- loop iteration 23 output
  let round24 := divsteps47Round ⟨a_23, cnt_23, b_23, f0_23, g0_23, f1_23, g1_23⟩  -- loop iteration 24
  let a_24 := round24.a             -- loop iteration 24 output
  let cnt_24 := round24.cnt         -- loop iteration 24 output
  let b_24 := round24.b             -- loop iteration 24 output
  let f0_24 := round24.f0           -- loop iteration 24 output
  let g0_24 := round24.g0           -- loop iteration 24 output
  let f1_24 := round24.f1           -- loop iteration 24 output
  let g1_24 := round24.g1           -- loop iteration 24 output
  let round25 := divsteps47Round ⟨a_24, cnt_24, b_24, f0_24, g0_24, f1_24, g1_24⟩  -- loop iteration 25
  let a_25 := round25.a             -- loop iteration 25 output
  let cnt_25 := round25.cnt         -- loop iteration 25 output
  let b_25 := round25.b             -- loop iteration 25 output
  let f0_25 := round25.f0           -- loop iteration 25 output
  let g0_25 := round25.g0           -- loop iteration 25 output
  let f1_25 := round25.f1           -- loop iteration 25 output
  let g1_25 := round25.g1           -- loop iteration 25 output
  let round26 := divsteps47Round ⟨a_25, cnt_25, b_25, f0_25, g0_25, f1_25, g1_25⟩  -- loop iteration 26
  let a_26 := round26.a             -- loop iteration 26 output
  let cnt_26 := round26.cnt         -- loop iteration 26 output
  let b_26 := round26.b             -- loop iteration 26 output
  let f0_26 := round26.f0           -- loop iteration 26 output
  let g0_26 := round26.g0           -- loop iteration 26 output
  let f1_26 := round26.f1           -- loop iteration 26 output
  let g1_26 := round26.g1           -- loop iteration 26 output
  let round27 := divsteps47Round ⟨a_26, cnt_26, b_26, f0_26, g0_26, f1_26, g1_26⟩  -- loop iteration 27
  let a_27 := round27.a             -- loop iteration 27 output
  let cnt_27 := round27.cnt         -- loop iteration 27 output
  let b_27 := round27.b             -- loop iteration 27 output
  let f0_27 := round27.f0           -- loop iteration 27 output
  let g0_27 := round27.g0           -- loop iteration 27 output
  let f1_27 := round27.f1           -- loop iteration 27 output
  let g1_27 := round27.g1           -- loop iteration 27 output
  let round28 := divsteps47Round ⟨a_27, cnt_27, b_27, f0_27, g0_27, f1_27, g1_27⟩  -- loop iteration 28
  let a_28 := round28.a             -- loop iteration 28 output
  let cnt_28 := round28.cnt         -- loop iteration 28 output
  let b_28 := round28.b             -- loop iteration 28 output
  let f0_28 := round28.f0           -- loop iteration 28 output
  let g0_28 := round28.g0           -- loop iteration 28 output
  let f1_28 := round28.f1           -- loop iteration 28 output
  let g1_28 := round28.g1           -- loop iteration 28 output
  let round29 := divsteps47Round ⟨a_28, cnt_28, b_28, f0_28, g0_28, f1_28, g1_28⟩  -- loop iteration 29
  let a_29 := round29.a             -- loop iteration 29 output
  let cnt_29 := round29.cnt         -- loop iteration 29 output
  let b_29 := round29.b             -- loop iteration 29 output
  let f0_29 := round29.f0           -- loop iteration 29 output
  let g0_29 := round29.g0           -- loop iteration 29 output
  let f1_29 := round29.f1           -- loop iteration 29 output
  let g1_29 := round29.g1           -- loop iteration 29 output
  let round30 := divsteps47Round ⟨a_29, cnt_29, b_29, f0_29, g0_29, f1_29, g1_29⟩  -- loop iteration 30
  let a_30 := round30.a             -- loop iteration 30 output
  let cnt_30 := round30.cnt         -- loop iteration 30 output
  let b_30 := round30.b             -- loop iteration 30 output
  let f0_30 := round30.f0           -- loop iteration 30 output
  let g0_30 := round30.g0           -- loop iteration 30 output
  let f1_30 := round30.f1           -- loop iteration 30 output
  let g1_30 := round30.g1           -- loop iteration 30 output
  let round31 := divsteps47Round ⟨a_30, cnt_30, b_30, f0_30, g0_30, f1_30, g1_30⟩  -- loop iteration 31
  let a_31 := round31.a             -- loop iteration 31 output
  let cnt_31 := round31.cnt         -- loop iteration 31 output
  let b_31 := round31.b             -- loop iteration 31 output
  let f0_31 := round31.f0           -- loop iteration 31 output
  let g0_31 := round31.g0           -- loop iteration 31 output
  let f1_31 := round31.f1           -- loop iteration 31 output
  let g1_31 := round31.g1           -- loop iteration 31 output
  let round32 := divsteps47Round ⟨a_31, cnt_31, b_31, f0_31, g0_31, f1_31, g1_31⟩  -- loop iteration 32
  let a_32 := round32.a             -- loop iteration 32 output
  let cnt_32 := round32.cnt         -- loop iteration 32 output
  let b_32 := round32.b             -- loop iteration 32 output
  let f0_32 := round32.f0           -- loop iteration 32 output
  let g0_32 := round32.g0           -- loop iteration 32 output
  let f1_32 := round32.f1           -- loop iteration 32 output
  let g1_32 := round32.g1           -- loop iteration 32 output
  let round33 := divsteps47Round ⟨a_32, cnt_32, b_32, f0_32, g0_32, f1_32, g1_32⟩  -- loop iteration 33
  let a_33 := round33.a             -- loop iteration 33 output
  let cnt_33 := round33.cnt         -- loop iteration 33 output
  let b_33 := round33.b             -- loop iteration 33 output
  let f0_33 := round33.f0           -- loop iteration 33 output
  let g0_33 := round33.g0           -- loop iteration 33 output
  let f1_33 := round33.f1           -- loop iteration 33 output
  let g1_33 := round33.g1           -- loop iteration 33 output
  let round34 := divsteps47Round ⟨a_33, cnt_33, b_33, f0_33, g0_33, f1_33, g1_33⟩  -- loop iteration 34
  let a_34 := round34.a             -- loop iteration 34 output
  let cnt_34 := round34.cnt         -- loop iteration 34 output
  let b_34 := round34.b             -- loop iteration 34 output
  let f0_34 := round34.f0           -- loop iteration 34 output
  let g0_34 := round34.g0           -- loop iteration 34 output
  let f1_34 := round34.f1           -- loop iteration 34 output
  let g1_34 := round34.g1           -- loop iteration 34 output
  let round35 := divsteps47Round ⟨a_34, cnt_34, b_34, f0_34, g0_34, f1_34, g1_34⟩  -- loop iteration 35
  let a_35 := round35.a             -- loop iteration 35 output
  let cnt_35 := round35.cnt         -- loop iteration 35 output
  let b_35 := round35.b             -- loop iteration 35 output
  let f0_35 := round35.f0           -- loop iteration 35 output
  let g0_35 := round35.g0           -- loop iteration 35 output
  let f1_35 := round35.f1           -- loop iteration 35 output
  let g1_35 := round35.g1           -- loop iteration 35 output
  let round36 := divsteps47Round ⟨a_35, cnt_35, b_35, f0_35, g0_35, f1_35, g1_35⟩  -- loop iteration 36
  let a_36 := round36.a             -- loop iteration 36 output
  let cnt_36 := round36.cnt         -- loop iteration 36 output
  let b_36 := round36.b             -- loop iteration 36 output
  let f0_36 := round36.f0           -- loop iteration 36 output
  let g0_36 := round36.g0           -- loop iteration 36 output
  let f1_36 := round36.f1           -- loop iteration 36 output
  let g1_36 := round36.g1           -- loop iteration 36 output
  let round37 := divsteps47Round ⟨a_36, cnt_36, b_36, f0_36, g0_36, f1_36, g1_36⟩  -- loop iteration 37
  let a_37 := round37.a             -- loop iteration 37 output
  let cnt_37 := round37.cnt         -- loop iteration 37 output
  let b_37 := round37.b             -- loop iteration 37 output
  let f0_37 := round37.f0           -- loop iteration 37 output
  let g0_37 := round37.g0           -- loop iteration 37 output
  let f1_37 := round37.f1           -- loop iteration 37 output
  let g1_37 := round37.g1           -- loop iteration 37 output
  let round38 := divsteps47Round ⟨a_37, cnt_37, b_37, f0_37, g0_37, f1_37, g1_37⟩  -- loop iteration 38
  let a_38 := round38.a             -- loop iteration 38 output
  let cnt_38 := round38.cnt         -- loop iteration 38 output
  let b_38 := round38.b             -- loop iteration 38 output
  let f0_38 := round38.f0           -- loop iteration 38 output
  let g0_38 := round38.g0           -- loop iteration 38 output
  let f1_38 := round38.f1           -- loop iteration 38 output
  let g1_38 := round38.g1           -- loop iteration 38 output
  let round39 := divsteps47Round ⟨a_38, cnt_38, b_38, f0_38, g0_38, f1_38, g1_38⟩  -- loop iteration 39
  let a_39 := round39.a             -- loop iteration 39 output
  let cnt_39 := round39.cnt         -- loop iteration 39 output
  let b_39 := round39.b             -- loop iteration 39 output
  let f0_39 := round39.f0           -- loop iteration 39 output
  let g0_39 := round39.g0           -- loop iteration 39 output
  let f1_39 := round39.f1           -- loop iteration 39 output
  let g1_39 := round39.g1           -- loop iteration 39 output
  let round40 := divsteps47Round ⟨a_39, cnt_39, b_39, f0_39, g0_39, f1_39, g1_39⟩  -- loop iteration 40
  let a_40 := round40.a             -- loop iteration 40 output
  let cnt_40 := round40.cnt         -- loop iteration 40 output
  let b_40 := round40.b             -- loop iteration 40 output
  let f0_40 := round40.f0           -- loop iteration 40 output
  let g0_40 := round40.g0           -- loop iteration 40 output
  let f1_40 := round40.f1           -- loop iteration 40 output
  let g1_40 := round40.g1           -- loop iteration 40 output
  let round41 := divsteps47Round ⟨a_40, cnt_40, b_40, f0_40, g0_40, f1_40, g1_40⟩  -- loop iteration 41
  let a_41 := round41.a             -- loop iteration 41 output
  let cnt_41 := round41.cnt         -- loop iteration 41 output
  let b_41 := round41.b             -- loop iteration 41 output
  let f0_41 := round41.f0           -- loop iteration 41 output
  let g0_41 := round41.g0           -- loop iteration 41 output
  let f1_41 := round41.f1           -- loop iteration 41 output
  let g1_41 := round41.g1           -- loop iteration 41 output
  let round42 := divsteps47Round ⟨a_41, cnt_41, b_41, f0_41, g0_41, f1_41, g1_41⟩  -- loop iteration 42
  let a_42 := round42.a             -- loop iteration 42 output
  let cnt_42 := round42.cnt         -- loop iteration 42 output
  let b_42 := round42.b             -- loop iteration 42 output
  let f0_42 := round42.f0           -- loop iteration 42 output
  let g0_42 := round42.g0           -- loop iteration 42 output
  let f1_42 := round42.f1           -- loop iteration 42 output
  let g1_42 := round42.g1           -- loop iteration 42 output
  let round43 := divsteps47Round ⟨a_42, cnt_42, b_42, f0_42, g0_42, f1_42, g1_42⟩  -- loop iteration 43
  let a_43 := round43.a             -- loop iteration 43 output
  let cnt_43 := round43.cnt         -- loop iteration 43 output
  let b_43 := round43.b             -- loop iteration 43 output
  let f0_43 := round43.f0           -- loop iteration 43 output
  let g0_43 := round43.g0           -- loop iteration 43 output
  let f1_43 := round43.f1           -- loop iteration 43 output
  let g1_43 := round43.g1           -- loop iteration 43 output
  let round44 := divsteps47Round ⟨a_43, cnt_43, b_43, f0_43, g0_43, f1_43, g1_43⟩  -- loop iteration 44
  let a_44 := round44.a             -- loop iteration 44 output
  let cnt_44 := round44.cnt         -- loop iteration 44 output
  let b_44 := round44.b             -- loop iteration 44 output
  let f0_44 := round44.f0           -- loop iteration 44 output
  let g0_44 := round44.g0           -- loop iteration 44 output
  let f1_44 := round44.f1           -- loop iteration 44 output
  let g1_44 := round44.g1           -- loop iteration 44 output
  let round45 := divsteps47Round ⟨a_44, cnt_44, b_44, f0_44, g0_44, f1_44, g1_44⟩  -- loop iteration 45
  let a_45 := round45.a             -- loop iteration 45 output
  let cnt_45 := round45.cnt         -- loop iteration 45 output
  let b_45 := round45.b             -- loop iteration 45 output
  let f0_45 := round45.f0           -- loop iteration 45 output
  let g0_45 := round45.g0           -- loop iteration 45 output
  let f1_45 := round45.f1           -- loop iteration 45 output
  let g1_45 := round45.g1           -- loop iteration 45 output
  let round46 := divsteps47Round ⟨a_45, cnt_45, b_45, f0_45, g0_45, f1_45, g1_45⟩  -- loop iteration 46
  let a_46 := round46.a             -- loop iteration 46 output
  let cnt_46 := round46.cnt         -- loop iteration 46 output
  let b_46 := round46.b             -- loop iteration 46 output
  let f0_46 := round46.f0           -- loop iteration 46 output
  let g0_46 := round46.g0           -- loop iteration 46 output
  let f1_46 := round46.f1           -- loop iteration 46 output
  let g1_46 := round46.g1           -- loop iteration 46 output
  let round47 := divsteps47Round ⟨a_46, cnt_46, b_46, f0_46, g0_46, f1_46, g1_46⟩  -- loop iteration 47
  let f1_47 := round47.f1           -- loop iteration 47 output
  let g1_47 := round47.g1           -- loop iteration 47 output
  ⟨f1_47, g1_47⟩

/-- The final signed coefficient adjustment; the low half is unchanged and the adjusted high half is
returned. -/
def normalizeCoefficient (value : WideLimbs) (modulus : Limbs) : CoefficientSplit :=
  let p0 := modulus.l0              -- argument
  let p1 := modulus.l1              -- argument
  let w4 := value.l4                -- argument
  let w5 := value.l5                -- argument
  let w6 := value.l6                -- argument
  let w7 := value.l7                -- argument
  let w8 := value.l8                -- argument
  let sign := asr w8 63             -- asr sign,w8,#63
  let m4 := lsl p0 1                -- lsl m4,p0,#1
  let tmp := lsr p0 63              -- lsr tmp,p0,#63
  let m5 := orr tmp (lsl p1 1)      -- orr m5,tmp,p1,lsl #1
  let m6 := lsr p1 63               -- lsr m6,p1,#63
  let m7 := 9223372036854775808     -- mov m7,#0x8000000000000000
  let tmp := bitAnd m4 sign         -- and tmp,m4,sign
  let s := addc w4 tmp 0            -- adds w4,w4,tmp
  let w4 := s.1                     --   `-> w4
  let c := s.2                      --   `-> carry
  let tmp := bitAnd m5 sign         -- and tmp,m5,sign
  let s := addc w5 tmp c            -- adcs w5,w5,tmp
  let w5 := s.1                     --   `-> w5
  let c := s.2                      --   `-> carry
  let tmp := bitAnd m6 sign         -- and tmp,m6,sign
  let s := addc w6 tmp c            -- adcs w6,w6,tmp
  let w6 := s.1                     --   `-> w6
  let c := s.2                      --   `-> carry
  let tmp := bitAnd m7 sign         -- and tmp,m7,sign
  let s := addc w7 tmp c            -- adcs w7,w7,tmp
  let w7 := s.1                     --   `-> w7
  let c := s.2                      --   `-> carry
  let w8 := (addc w8 0 c).1         -- adc w8,w8,xzr
  let sign := neg w8                -- neg sign,w8
  let excess := orr w8 sign         -- orr excess,w8,sign
  let sign := asr sign 63           -- asr sign,sign,#63
  let m4 := bitAnd m4 excess        -- and m4,m4,excess
  let m5 := bitAnd m5 excess        -- and m5,m5,excess
  let m6 := bitAnd m6 excess        -- and m6,m6,excess
  let m7 := bitAnd m7 excess        -- and m7,m7,excess
  let m4 := eor m4 sign             -- eor m4,m4,sign
  let m5 := eor m5 sign             -- eor m5,m5,sign
  let s := addc m4 (lsr sign 63) 0  -- adds m4,m4,sign,lsr #63
  let m4 := s.1                     --   `-> m4
  let c := s.2                      --   `-> carry
  let m6 := eor m6 sign             -- eor m6,m6,sign
  let s := addc m5 0 c              -- adcs m5,m5,xzr
  let m5 := s.1                     --   `-> m5
  let c := s.2                      --   `-> carry
  let m7 := eor m7 sign             -- eor m7,m7,sign
  let s := addc m6 0 c              -- adcs m6,m6,xzr
  let m6 := s.1                     --   `-> m6
  let c := s.2                      --   `-> carry
  let m7 := (addc m7 0 c).1         -- adc m7,m7,xzr
  let s := addc w4 m4 0             -- adds w4,w4,m4
  let w4 := s.1                     --   `-> w4
  let c := s.2                      --   `-> carry
  let s := addc w5 m5 c             -- adcs w5,w5,m5
  let w5 := s.1                     --   `-> w5
  let c := s.2                      --   `-> carry
  let s := addc w6 m6 c             -- adcs w6,w6,m6
  let w6 := s.1                     --   `-> w6
  let c := s.2                      --   `-> carry
  let w7 := (addc w7 m7 c).1        -- adc w7,w7,m7
  ⟨⟨value.l0, value.l1, value.l2, value.l3⟩, ⟨w4, w5, w6, w7⟩⟩

/-- One conditional subtraction of the modulus from a value known to be below twice it. -/
def reduceOnce (value modulus : Limbs) : Limbs :=
  let r0 := value.l0                -- argument
  let r1 := value.l1                -- argument
  let r2 := value.l2                -- argument
  let r3 := value.l3                -- argument
  let p0 := modulus.l0              -- argument
  let p1 := modulus.l1              -- argument
  let p2 := modulus.l2              -- argument
  let p3 := modulus.l3              -- argument
  let s := subc r0 p0 1             -- subs t0,r0,p0
  let t0 := s.1                     --   `-> t0
  let c := s.2                      --   `-> carry
  let s := subc r1 p1 c             -- sbcs t1,r1,p1
  let t1 := s.1                     --   `-> t1
  let c := s.2                      --   `-> carry
  let s := subc r2 p2 c             -- sbcs t2,r2,p2
  let t2 := s.1                     --   `-> t2
  let c := s.2                      --   `-> carry
  let s := subc r3 p3 c             -- sbcs t3,r3,p3
  let t3 := s.1                     --   `-> t3
  let c := s.2                      --   `-> carry
  let r0 := cselCs c t0 r0          -- csel r0,t0,r0,cs
  let r1 := cselCs c t1 r1          -- csel r1,t1,r1,cs
  let r2 := cselCs c t2 r2          -- csel r2,t2,r2,cs
  let r3 := cselCs c t3 r3          -- csel r3,t3,r3,cs
  ⟨r0, r1, r2, r3⟩

end PastaAsm.AArch64
