/-
Copyright (c) 2026 the pasta-asm contributors.
Released under the Apache License, Version 2.0, as described in the file LICENSE.
-/
import PastaAsm.X86_64.Spec.Invert.Arithmetic
import Mathlib.Tactic.ClearExcept

/-!
# Remaining x86-64 inversion arithmetic helper proofs

The instruction traces in this file are generated by
`lean/scripts/gen.py --skeleton X86_64:<name>`. Only theorem statements and delimited annotation
blocks are handwritten.
-/

namespace PastaAsm.X86_64

set_option linter.constructorNameAsVariable false

-- BEGIN normalizeExcess_spec statement
/-- The second normalization helper constructs a four-word adjustment and adds it to `high`.
The witnesses expose both the exact adjustment bitpattern and the exact full-width output addition,
including the carry discarded above bit 255. The final conjunct records the important zero-excess
case used by normalization: no adjustment is made. -/
theorem normalizeExcess_spec (high modulus2 : Limbs) (excess : Nat)
    (hhigh : high.Bounded) (hmodulus2 : modulus2.Bounded) (hexcess : excess < 2^64) :
    ∀ r, r = normalizeExcess high modulus2 excess →
      r.Bounded ∧
        ∃ adjustment carry,
          adjustment < 2^256 ∧ carry ≤ 1 ∧
          r.toNat + 2^256 * carry = high.toNat + adjustment ∧
          (excess = 0 → adjustment = 0 ∧ r.toNat = high.toNat) := by
  intro r hr
-- END normalizeExcess_spec statement
  -- generated skeleton for `normalizeExcess`: do not edit between the annotations
  unfold normalizeExcess at hr
  lift_lets at hr
  -- h0: input h0
  extract_lets +onlyGivenNames h0 at hr
  have e_h0 : h0 = high.l0 := rfl
  have b_h0 : h0 < 2^64 := by rw [e_h0]; exact hhigh.1
  -- h1: input h1
  extract_lets +onlyGivenNames h1 at hr
  have e_h1 : h1 = high.l1 := rfl
  have b_h1 : h1 < 2^64 := by rw [e_h1]; exact hhigh.2.1
  -- h2: input h2
  extract_lets +onlyGivenNames h2 at hr
  have e_h2 : h2 = high.l2 := rfl
  have b_h2 : h2 < 2^64 := by rw [e_h2]; exact hhigh.2.2.1
  -- h3: input h3
  extract_lets +onlyGivenNames h3 at hr
  have e_h3 : h3 = high.l3 := rfl
  have b_h3 : h3 < 2^64 := by rw [e_h3]; exact hhigh.2.2.2
  -- m0: input m0
  extract_lets +onlyGivenNames m0 at hr
  have e_m0 : m0 = modulus2.l0 := rfl
  have b_m0 : m0 < 2^64 := by rw [e_m0]; exact hmodulus2.1
  -- m1: input m1
  extract_lets +onlyGivenNames m1 at hr
  have e_m1 : m1 = modulus2.l1 := rfl
  have b_m1 : m1 < 2^64 := by rw [e_m1]; exact hmodulus2.2.1
  -- m2: input m2
  extract_lets +onlyGivenNames m2 at hr
  have e_m2 : m2 = modulus2.l2 := rfl
  have b_m2 : m2 < 2^64 := by rw [e_m2]; exact hmodulus2.2.2.1
  -- m3: input m3
  extract_lets +onlyGivenNames m3 at hr
  have e_m3 : m3 = modulus2.l3 := rfl
  have b_m3 : m3 < 2^64 := by rw [e_m3]; exact hmodulus2.2.2.2
  -- excess': input excess
  extract_lets +onlyGivenNames excess' at hr
  have e_excess' : excess' = excess := rfl
  have b_excess' : excess' < 2^64 := by rw [e_excess']; exact hexcess
  -- nonzero_mask: mov {nonzero_mask}, {excess}
  extract_lets +onlyGivenNames nonzero_mask at hr
  have e_nonzero_mask : nonzero_mask = excess' := rfl
  have b_nonzero_mask : nonzero_mask < 2^64 := by rw [e_nonzero_mask]; exact b_excess'
  -- s: neg {negative_excess}
  extract_lets +onlyGivenNames s negative_excess_1 cf at hr
  have e_negative_excess_1 : negative_excess_1 = (neg nonzero_mask).1 := rfl
  have e_cf : cf = (neg nonzero_mask).2 := rfl
  have b_negative_excess_1 : negative_excess_1 < 2^64 := by rw [e_negative_excess_1]; exact sbb_value_lt 0 nonzero_mask 0
  have b_cf : cf ≤ 1 := by
    rw [e_cf]; simp only [neg]; split <;> omega
  -- nonzero_mask_1: or {nonzero_mask}, {negative_excess}
  extract_lets +onlyGivenNames nonzero_mask_1 cf_1 zf at hr
  have e_nonzero_mask_1 : nonzero_mask_1 = bitOr nonzero_mask negative_excess_1 := rfl
  have e_cf_1 : cf_1 = 0 := rfl
  have e_zf : zf = zeroFlag nonzero_mask_1 := rfl
  have b_nonzero_mask_1 : nonzero_mask_1 < 2^64 := by rw [e_nonzero_mask_1]; exact bitOr_lt _ _
  have b_cf_1 : cf_1 ≤ 1 := by rw [e_cf_1]; decide
  have b_zf : zf ≤ 1 := by rw [e_zf]; exact zeroFlag_le_one _
  -- negative_excess_2: sar {negative_excess}, 63
  extract_lets +onlyGivenNames negative_excess_2 at hr
  have e_negative_excess_2 : negative_excess_2 = sar negative_excess_1 63 := rfl
  have b_negative_excess_2 : negative_excess_2 < 2^64 := by rw [e_negative_excess_2]; exact sar_lt _ _
  -- m0_1: and {m0}, {nonzero_mask}
  extract_lets +onlyGivenNames m0_1 zf_1 at hr
  have e_m0_1 : m0_1 = bitAnd m0 nonzero_mask_1 := rfl
  have e_zf_1 : zf_1 = zeroFlag m0_1 := rfl
  have b_m0_1 : m0_1 < 2^64 := by rw [e_m0_1]; exact bitAnd_lt _ _
  have b_zf_1 : zf_1 ≤ 1 := by rw [e_zf_1]; exact zeroFlag_le_one _
  -- m1_1: and {m1}, {nonzero_mask}
  extract_lets +onlyGivenNames m1_1 zf_2 at hr
  have e_m1_1 : m1_1 = bitAnd m1 nonzero_mask_1 := rfl
  have e_zf_2 : zf_2 = zeroFlag m1_1 := rfl
  have b_m1_1 : m1_1 < 2^64 := by rw [e_m1_1]; exact bitAnd_lt _ _
  have b_zf_2 : zf_2 ≤ 1 := by rw [e_zf_2]; exact zeroFlag_le_one _
  -- m2_1: and {m2}, {nonzero_mask}
  extract_lets +onlyGivenNames m2_1 zf_3 at hr
  have e_m2_1 : m2_1 = bitAnd m2 nonzero_mask_1 := rfl
  have e_zf_3 : zf_3 = zeroFlag m2_1 := rfl
  have b_m2_1 : m2_1 < 2^64 := by rw [e_m2_1]; exact bitAnd_lt _ _
  have b_zf_3 : zf_3 ≤ 1 := by rw [e_zf_3]; exact zeroFlag_le_one _
  -- m3_1: and {m3}, {nonzero_mask}
  extract_lets +onlyGivenNames m3_1 zf_4 at hr
  have e_m3_1 : m3_1 = bitAnd m3 nonzero_mask_1 := rfl
  have e_zf_4 : zf_4 = zeroFlag m3_1 := rfl
  have b_m3_1 : m3_1 < 2^64 := by rw [e_m3_1]; exact bitAnd_lt _ _
  have b_zf_4 : zf_4 ≤ 1 := by rw [e_zf_4]; exact zeroFlag_le_one _
  -- m0_2: xor {m0}, {negative_excess}
  extract_lets +onlyGivenNames m0_2 zf_5 at hr
  have e_m0_2 : m0_2 = bitXor m0_1 negative_excess_2 := rfl
  have e_zf_5 : zf_5 = zeroFlag m0_2 := rfl
  have b_m0_2 : m0_2 < 2^64 := by rw [e_m0_2]; exact bitXor_lt _ _
  have b_zf_5 : zf_5 ≤ 1 := by rw [e_zf_5]; exact zeroFlag_le_one _
  -- zero: xor {zero:e}, {zero:e}
  extract_lets +onlyGivenNames zero zf_6 at hr
  have e_zero : zero = bitXor32 0 0 := rfl
  have e_zf_6 : zf_6 = zeroFlag zero := rfl
  have b_zero : zero < 2^64 := by rw [e_zero]; exact bitXor32_lt _ _
  have b_zf_6 : zf_6 ≤ 1 := by rw [e_zf_6]; exact zeroFlag_le_one _
  -- m1_2: xor {m1}, {negative_excess}
  extract_lets +onlyGivenNames m1_2 zf_7 at hr
  have e_m1_2 : m1_2 = bitXor m1_1 negative_excess_2 := rfl
  have e_zf_7 : zf_7 = zeroFlag m1_2 := rfl
  have b_m1_2 : m1_2 < 2^64 := by rw [e_m1_2]; exact bitXor_lt _ _
  have b_zf_7 : zf_7 ≤ 1 := by rw [e_zf_7]; exact zeroFlag_le_one _
  -- zero_1: sub {zero}, {negative_excess}
  extract_lets +onlyGivenNames s_1 zero_1 cf_9 at hr
  have e_zero_1 : zero_1 = (sbb zero negative_excess_2 0).1 := rfl
  have e_cf_9 : cf_9 = (sbb zero negative_excess_2 0).2 := rfl
  have l_zero_1 : zero_1 + negative_excess_2 + 0 = zero + 2^64 * cf_9 := by
    rw [e_zero_1, e_cf_9]; exact sbb_lin zero negative_excess_2 0 b_zero b_negative_excess_2 (by decide)
  have b_zero_1 : zero_1 < 2^64 := by rw [e_zero_1]; exact sbb_value_lt zero negative_excess_2 0
  have b_cf_9 : cf_9 ≤ 1 := by rw [e_cf_9]; exact sbb_borrow_le_one zero negative_excess_2 0
  clear e_zero_1 e_cf_9
  -- m2_2: xor {m2}, {negative_excess}
  extract_lets +onlyGivenNames m2_2 zf_8 at hr
  have e_m2_2 : m2_2 = bitXor m2_1 negative_excess_2 := rfl
  have e_zf_8 : zf_8 = zeroFlag m2_2 := rfl
  have b_m2_2 : m2_2 < 2^64 := by rw [e_m2_2]; exact bitXor_lt _ _
  have b_zf_8 : zf_8 ≤ 1 := by rw [e_zf_8]; exact zeroFlag_le_one _
  -- m3_2: xor {m3}, {negative_excess}
  extract_lets +onlyGivenNames m3_2 zf_9 at hr
  have e_m3_2 : m3_2 = bitXor m3_1 negative_excess_2 := rfl
  have e_zf_9 : zf_9 = zeroFlag m3_2 := rfl
  have b_m3_2 : m3_2 < 2^64 := by rw [e_m3_2]; exact bitXor_lt _ _
  have b_zf_9 : zf_9 ≤ 1 := by rw [e_zf_9]; exact zeroFlag_le_one _
  -- m0_3: add {m0}, {zero}
  extract_lets +onlyGivenNames s_2 m0_3 cf_12 at hr
  have e_m0_3 : m0_3 = (addc m0_2 zero_1 0).1 := rfl
  have e_cf_12 : cf_12 = (addc m0_2 zero_1 0).2 := rfl
  have l_m0_3 : m0_3 + 2^64 * cf_12 = m0_2 + zero_1 + 0 := by
    rw [e_m0_3, e_cf_12]; exact addc_lin m0_2 zero_1 0
  have b_m0_3 : m0_3 < 2^64 := by rw [e_m0_3]; exact addc_value_lt m0_2 zero_1 0
  have b_cf_12 : cf_12 ≤ 1 := by rw [e_cf_12]; exact addc_carry_le_one m0_2 zero_1 0 b_m0_2 b_zero_1 (by decide)
  clear e_m0_3 e_cf_12
  -- m1_3: adc {m1}, 0
  extract_lets +onlyGivenNames s_3 m1_3 cf_13 at hr
  have e_m1_3 : m1_3 = (addc m1_2 0 cf_12).1 := rfl
  have e_cf_13 : cf_13 = (addc m1_2 0 cf_12).2 := rfl
  have l_m1_3 : m1_3 + 2^64 * cf_13 = m1_2 + 0 + cf_12 := by
    rw [e_m1_3, e_cf_13]; exact addc_lin m1_2 0 cf_12
  have b_m1_3 : m1_3 < 2^64 := by rw [e_m1_3]; exact addc_value_lt m1_2 0 cf_12
  have b_cf_13 : cf_13 ≤ 1 := by rw [e_cf_13]; exact addc_carry_le_one m1_2 0 cf_12 b_m1_2 (by decide) b_cf_12
  clear e_m1_3 e_cf_13
  -- m2_3: adc {m2}, 0
  extract_lets +onlyGivenNames s_4 m2_3 cf_14 at hr
  have e_m2_3 : m2_3 = (addc m2_2 0 cf_13).1 := rfl
  have e_cf_14 : cf_14 = (addc m2_2 0 cf_13).2 := rfl
  have l_m2_3 : m2_3 + 2^64 * cf_14 = m2_2 + 0 + cf_13 := by
    rw [e_m2_3, e_cf_14]; exact addc_lin m2_2 0 cf_13
  have b_m2_3 : m2_3 < 2^64 := by rw [e_m2_3]; exact addc_value_lt m2_2 0 cf_13
  have b_cf_14 : cf_14 ≤ 1 := by rw [e_cf_14]; exact addc_carry_le_one m2_2 0 cf_13 b_m2_2 (by decide) b_cf_13
  clear e_m2_3 e_cf_14
  -- m3_3: adc {m3}, 0
  extract_lets +onlyGivenNames s_5 m3_3 cf_15 at hr
  have e_m3_3 : m3_3 = (addc m3_2 0 cf_14).1 := rfl
  have e_cf_15 : cf_15 = (addc m3_2 0 cf_14).2 := rfl
  have l_m3_3 : m3_3 + 2^64 * cf_15 = m3_2 + 0 + cf_14 := by
    rw [e_m3_3, e_cf_15]; exact addc_lin m3_2 0 cf_14
  have b_m3_3 : m3_3 < 2^64 := by rw [e_m3_3]; exact addc_value_lt m3_2 0 cf_14
  have b_cf_15 : cf_15 ≤ 1 := by rw [e_cf_15]; exact addc_carry_le_one m3_2 0 cf_14 b_m3_2 (by decide) b_cf_14
  clear e_m3_3 e_cf_15
  -- h0_1: add {h0}, {m0}
  extract_lets +onlyGivenNames s_6 h0_1 cf_16 at hr
  have e_h0_1 : h0_1 = (addc h0 m0_3 0).1 := rfl
  have e_cf_16 : cf_16 = (addc h0 m0_3 0).2 := rfl
  have l_h0_1 : h0_1 + 2^64 * cf_16 = h0 + m0_3 + 0 := by
    rw [e_h0_1, e_cf_16]; exact addc_lin h0 m0_3 0
  have b_h0_1 : h0_1 < 2^64 := by rw [e_h0_1]; exact addc_value_lt h0 m0_3 0
  have b_cf_16 : cf_16 ≤ 1 := by rw [e_cf_16]; exact addc_carry_le_one h0 m0_3 0 b_h0 b_m0_3 (by decide)
  clear e_h0_1 e_cf_16
  -- h1_1: adc {h1}, {m1}
  extract_lets +onlyGivenNames s_7 h1_1 cf_17 at hr
  have e_h1_1 : h1_1 = (addc h1 m1_3 cf_16).1 := rfl
  have e_cf_17 : cf_17 = (addc h1 m1_3 cf_16).2 := rfl
  have l_h1_1 : h1_1 + 2^64 * cf_17 = h1 + m1_3 + cf_16 := by
    rw [e_h1_1, e_cf_17]; exact addc_lin h1 m1_3 cf_16
  have b_h1_1 : h1_1 < 2^64 := by rw [e_h1_1]; exact addc_value_lt h1 m1_3 cf_16
  have b_cf_17 : cf_17 ≤ 1 := by rw [e_cf_17]; exact addc_carry_le_one h1 m1_3 cf_16 b_h1 b_m1_3 b_cf_16
  clear e_h1_1 e_cf_17
  -- h2_1: adc {h2}, {m2}
  extract_lets +onlyGivenNames s_8 h2_1 cf_18 at hr
  have e_h2_1 : h2_1 = (addc h2 m2_3 cf_17).1 := rfl
  have e_cf_18 : cf_18 = (addc h2 m2_3 cf_17).2 := rfl
  have l_h2_1 : h2_1 + 2^64 * cf_18 = h2 + m2_3 + cf_17 := by
    rw [e_h2_1, e_cf_18]; exact addc_lin h2 m2_3 cf_17
  have b_h2_1 : h2_1 < 2^64 := by rw [e_h2_1]; exact addc_value_lt h2 m2_3 cf_17
  have b_cf_18 : cf_18 ≤ 1 := by rw [e_cf_18]; exact addc_carry_le_one h2 m2_3 cf_17 b_h2 b_m2_3 b_cf_17
  clear e_h2_1 e_cf_18
  -- h3_1: adc {h3}, {m3}
  extract_lets +onlyGivenNames s_9 h3_1 cf_19 at hr
  have e_h3_1 : h3_1 = (addc h3 m3_3 cf_18).1 := rfl
  have e_cf_19 : cf_19 = (addc h3 m3_3 cf_18).2 := rfl
  have l_h3_1 : h3_1 + 2^64 * cf_19 = h3 + m3_3 + cf_18 := by
    rw [e_h3_1, e_cf_19]; exact addc_lin h3 m3_3 cf_18
  have b_h3_1 : h3_1 < 2^64 := by rw [e_h3_1]; exact addc_value_lt h3 m3_3 cf_18
  have b_cf_19 : cf_19 ≤ 1 := by rw [e_cf_19]; exact addc_carry_le_one h3 m3_3 cf_18 b_h3 b_m3_3 b_cf_18
  clear e_h3_1 e_cf_19
  subst hr
  -- BEGIN normalizeExcess_spec conclusion
  let adjustment := m0_3 + 2^64 * m1_3 + 2^128 * m2_3 + 2^192 * m3_3
  have hadjustment : adjustment < 2^256 := by
    simp only [adjustment]
    clear * - b_m0_3 b_m1_3 b_m2_3 b_m3_3
    omega
  have hout : h0_1 + 2^64 * h1_1 + 2^128 * h2_1 + 2^192 * h3_1 + 2^256 * cf_19 =
      high.toNat + adjustment := by
    simp only [Limbs.toNat, adjustment]
    rw [← e_h0, ← e_h1, ← e_h2, ← e_h3]
    clear * - l_h0_1 l_h1_1 l_h2_1 l_h3_1
    omega
  refine ⟨⟨b_h0_1, b_h1_1, b_h2_1, b_h3_1⟩,
    adjustment, cf_19, hadjustment, b_cf_19, hout, ?_⟩
  intro hexcessZero
  have he' : excess' = 0 := by omega
  have hmask0 : nonzero_mask = 0 := by omega
  have hneg0 : negative_excess_1 = 0 := by
    rw [e_negative_excess_1, hmask0]
    rfl
  have hnz0 : nonzero_mask_1 = 0 := by
    rw [e_nonzero_mask_1, hmask0, hneg0]
    rfl
  have hsign0 : negative_excess_2 = 0 := by
    rw [e_negative_excess_2, hneg0]
    rfl
  have hm0_1 : m0_1 = 0 := by rw [e_m0_1, hnz0]; simp [bitAnd, word]
  have hm1_1 : m1_1 = 0 := by rw [e_m1_1, hnz0]; simp [bitAnd, word]
  have hm2_1 : m2_1 = 0 := by rw [e_m2_1, hnz0]; simp [bitAnd, word]
  have hm3_1 : m3_1 = 0 := by rw [e_m3_1, hnz0]; simp [bitAnd, word]
  have hm0_2 : m0_2 = 0 := by rw [e_m0_2, hm0_1, hsign0]; rfl
  have hm1_2 : m1_2 = 0 := by rw [e_m1_2, hm1_1, hsign0]; rfl
  have hm2_2 : m2_2 = 0 := by rw [e_m2_2, hm2_1, hsign0]; rfl
  have hm3_2 : m3_2 = 0 := by rw [e_m3_2, hm3_1, hsign0]; rfl
  have hzero : zero = 0 := by rw [e_zero]; rfl
  have hzero1 : zero_1 = 0 := by
    clear * - l_zero_1 hzero hsign0 b_zero_1
    omega
  have ha0 : m0_3 = 0 := by omega
  have ha1 : m1_3 = 0 := by omega
  have ha2 : m2_3 = 0 := by omega
  have ha3 : m3_3 = 0 := by omega
  have hhigh_lt := Limbs.toNat_lt high hhigh
  constructor
  · simp only [adjustment, ha0, ha1, ha2, ha3, mul_zero, add_zero]
  · have hc : cf_19 = 0 := by
      clear * - hout hadjustment ha0 ha1 ha2 ha3 hhigh_lt
      simp only [adjustment, ha0, ha1, ha2, ha3, mul_zero, add_zero] at hout
      omega
    change h0_1 + 2^64 * h1_1 + 2^128 * h2_1 + 2^192 * h3_1 = high.toNat
    clear * - hout hc ha0 ha1 ha2 ha3
    simp only [adjustment, ha0, ha1, ha2, ha3, mul_zero, add_zero] at hout
    omega
  -- END normalizeExcess_spec conclusion

-- BEGIN updateAbShift_spec statement
/-- The `update_ab` helper shifts the low five-word input right by 31 and then applies the
wordwise two's-complement absolute-value transform selected by the fifth word's sign.  The
returned row coefficients use the same sign mask and corrected parenthesized XOR-plus expression.
The theorem exposes both exact intermediate words and the final four-word carry chain. -/
theorem updateAbShift_spec (value : PastaAsm.WideLimbs) (f g : Nat) (hv : value.Bounded) :
    ∀ r, r = updateAbShift value f g →
      r.value.Bounded ∧
        ∃ q0 q1 q2 q3 mask signBit carry,
          q0 = shrd value.l0 value.l1 31 ∧
          q1 = shrd value.l1 value.l2 31 ∧
          q2 = shrd value.l2 value.l3 31 ∧
          q3 = shrd value.l3 value.l4 31 ∧
          mask = sar value.l4 63 ∧ signBit = bitAnd mask 1 ∧ carry ≤ 1 ∧
          r.value.toNat + 2^256 * carry =
            bitXor q0 mask + 2^64 * bitXor q1 mask +
              2^128 * bitXor q2 mask + 2^192 * bitXor q3 mask + signBit ∧
          r.f = word ((word f ^^^ mask) + signBit) ∧
          r.g = word ((word g ^^^ mask) + signBit) := by
  intro r hr
-- END updateAbShift_spec statement
  -- generated skeleton for `updateAbShift`: do not edit between the annotations
  unfold updateAbShift at hr
  lift_lets at hr
  -- r0: input r0
  extract_lets +onlyGivenNames r0 at hr
  have e_r0 : r0 = value.l0 := rfl
  have b_r0 : r0 < 2^64 := by rw [e_r0]; exact hv.1
  -- r1: input r1
  extract_lets +onlyGivenNames r1 at hr
  have e_r1 : r1 = value.l1 := rfl
  have b_r1 : r1 < 2^64 := by rw [e_r1]; exact hv.2.1
  -- r2: input r2
  extract_lets +onlyGivenNames r2 at hr
  have e_r2 : r2 = value.l2 := rfl
  have b_r2 : r2 < 2^64 := by rw [e_r2]; exact hv.2.2.1
  -- r3: input r3
  extract_lets +onlyGivenNames r3 at hr
  have e_r3 : r3 = value.l3 := rfl
  have b_r3 : r3 < 2^64 := by rw [e_r3]; exact hv.2.2.2.1
  -- r4: input r4
  extract_lets +onlyGivenNames r4 at hr
  have e_r4 : r4 = value.l4 := rfl
  have b_r4 : r4 < 2^64 := by rw [e_r4]; exact hv.2.2.2.2.1
  -- r0_1: shrd {r0}, {r1}, 31
  extract_lets +onlyGivenNames r0_1 at hr
  have e_r0_1 : r0_1 = shrd r0 r1 31 := rfl
  have b_r0_1 : r0_1 < 2^64 := by rw [e_r0_1]; exact shrd_lt _ _ _
  -- r1_1: shrd {r1}, {r2}, 31
  extract_lets +onlyGivenNames r1_1 at hr
  have e_r1_1 : r1_1 = shrd r1 r2 31 := rfl
  have b_r1_1 : r1_1 < 2^64 := by rw [e_r1_1]; exact shrd_lt _ _ _
  -- r2_1: shrd {r2}, {r3}, 31
  extract_lets +onlyGivenNames r2_1 at hr
  have e_r2_1 : r2_1 = shrd r2 r3 31 := rfl
  have b_r2_1 : r2_1 < 2^64 := by rw [e_r2_1]; exact shrd_lt _ _ _
  -- r3_1: shrd {r3}, {r4}, 31
  extract_lets +onlyGivenNames r3_1 at hr
  have e_r3_1 : r3_1 = shrd r3 r4 31 := rfl
  have b_r3_1 : r3_1 < 2^64 := by rw [e_r3_1]; exact shrd_lt _ _ _
  -- mask: mov {mask}, {r4}
  extract_lets +onlyGivenNames mask at hr
  have e_mask : mask = r4 := rfl
  have b_mask : mask < 2^64 := by rw [e_mask]; exact b_r4
  -- mask_1: sar {mask}, 63
  extract_lets +onlyGivenNames mask_1 at hr
  have e_mask_1 : mask_1 = sar mask 63 := rfl
  have b_mask_1 : mask_1 < 2^64 := by rw [e_mask_1]; exact sar_lt _ _
  -- bit: mov {bit}, {mask}
  extract_lets +onlyGivenNames bit at hr
  have e_bit : bit = mask_1 := rfl
  have b_bit : bit < 2^64 := by rw [e_bit]; exact b_mask_1
  -- bit_1: and {bit}, 1
  extract_lets +onlyGivenNames bit_1 cf zf at hr
  have e_bit_1 : bit_1 = bitAnd bit 1 := rfl
  have e_cf : cf = 0 := rfl
  have e_zf : zf = zeroFlag bit_1 := rfl
  have b_bit_1 : bit_1 < 2^64 := by rw [e_bit_1]; exact bitAnd_lt _ _
  have b_cf : cf ≤ 1 := by rw [e_cf]; decide
  have b_zf : zf ≤ 1 := by rw [e_zf]; exact zeroFlag_le_one _
  -- r0_2: xor {r0}, {mask}
  extract_lets +onlyGivenNames r0_2 zf_1 at hr
  have e_r0_2 : r0_2 = bitXor r0_1 mask_1 := rfl
  have e_zf_1 : zf_1 = zeroFlag r0_2 := rfl
  have b_r0_2 : r0_2 < 2^64 := by rw [e_r0_2]; exact bitXor_lt _ _
  have b_zf_1 : zf_1 ≤ 1 := by rw [e_zf_1]; exact zeroFlag_le_one _
  -- r1_2: xor {r1}, {mask}
  extract_lets +onlyGivenNames r1_2 zf_2 at hr
  have e_r1_2 : r1_2 = bitXor r1_1 mask_1 := rfl
  have e_zf_2 : zf_2 = zeroFlag r1_2 := rfl
  have b_r1_2 : r1_2 < 2^64 := by rw [e_r1_2]; exact bitXor_lt _ _
  have b_zf_2 : zf_2 ≤ 1 := by rw [e_zf_2]; exact zeroFlag_le_one _
  -- r2_2: xor {r2}, {mask}
  extract_lets +onlyGivenNames r2_2 zf_3 at hr
  have e_r2_2 : r2_2 = bitXor r2_1 mask_1 := rfl
  have e_zf_3 : zf_3 = zeroFlag r2_2 := rfl
  have b_r2_2 : r2_2 < 2^64 := by rw [e_r2_2]; exact bitXor_lt _ _
  have b_zf_3 : zf_3 ≤ 1 := by rw [e_zf_3]; exact zeroFlag_le_one _
  -- r3_2: xor {r3}, {mask}
  extract_lets +onlyGivenNames r3_2 zf_4 at hr
  have e_r3_2 : r3_2 = bitXor r3_1 mask_1 := rfl
  have e_zf_4 : zf_4 = zeroFlag r3_2 := rfl
  have b_r3_2 : r3_2 < 2^64 := by rw [e_r3_2]; exact bitXor_lt _ _
  have b_zf_4 : zf_4 ≤ 1 := by rw [e_zf_4]; exact zeroFlag_le_one _
  -- r0_3: add {r0}, {bit}
  extract_lets +onlyGivenNames s r0_3 cf_5 at hr
  have e_r0_3 : r0_3 = (addc r0_2 bit_1 0).1 := rfl
  have e_cf_5 : cf_5 = (addc r0_2 bit_1 0).2 := rfl
  have l_r0_3 : r0_3 + 2^64 * cf_5 = r0_2 + bit_1 + 0 := by
    rw [e_r0_3, e_cf_5]; exact addc_lin r0_2 bit_1 0
  have b_r0_3 : r0_3 < 2^64 := by rw [e_r0_3]; exact addc_value_lt r0_2 bit_1 0
  have b_cf_5 : cf_5 ≤ 1 := by rw [e_cf_5]; exact addc_carry_le_one r0_2 bit_1 0 b_r0_2 b_bit_1 (by decide)
  clear e_r0_3 e_cf_5
  -- r1_3: adc {r1}, 0
  extract_lets +onlyGivenNames s_1 r1_3 cf_6 at hr
  have e_r1_3 : r1_3 = (addc r1_2 0 cf_5).1 := rfl
  have e_cf_6 : cf_6 = (addc r1_2 0 cf_5).2 := rfl
  have l_r1_3 : r1_3 + 2^64 * cf_6 = r1_2 + 0 + cf_5 := by
    rw [e_r1_3, e_cf_6]; exact addc_lin r1_2 0 cf_5
  have b_r1_3 : r1_3 < 2^64 := by rw [e_r1_3]; exact addc_value_lt r1_2 0 cf_5
  have b_cf_6 : cf_6 ≤ 1 := by rw [e_cf_6]; exact addc_carry_le_one r1_2 0 cf_5 b_r1_2 (by decide) b_cf_5
  clear e_r1_3 e_cf_6
  -- r2_3: adc {r2}, 0
  extract_lets +onlyGivenNames s_2 r2_3 cf_7 at hr
  have e_r2_3 : r2_3 = (addc r2_2 0 cf_6).1 := rfl
  have e_cf_7 : cf_7 = (addc r2_2 0 cf_6).2 := rfl
  have l_r2_3 : r2_3 + 2^64 * cf_7 = r2_2 + 0 + cf_6 := by
    rw [e_r2_3, e_cf_7]; exact addc_lin r2_2 0 cf_6
  have b_r2_3 : r2_3 < 2^64 := by rw [e_r2_3]; exact addc_value_lt r2_2 0 cf_6
  have b_cf_7 : cf_7 ≤ 1 := by rw [e_cf_7]; exact addc_carry_le_one r2_2 0 cf_6 b_r2_2 (by decide) b_cf_6
  clear e_r2_3 e_cf_7
  -- r3_3: adc {r3}, 0
  extract_lets +onlyGivenNames s_3 r3_3 cf_8 at hr
  have e_r3_3 : r3_3 = (addc r3_2 0 cf_7).1 := rfl
  have e_cf_8 : cf_8 = (addc r3_2 0 cf_7).2 := rfl
  have l_r3_3 : r3_3 + 2^64 * cf_8 = r3_2 + 0 + cf_7 := by
    rw [e_r3_3, e_cf_8]; exact addc_lin r3_2 0 cf_7
  have b_r3_3 : r3_3 < 2^64 := by rw [e_r3_3]; exact addc_value_lt r3_2 0 cf_7
  have b_cf_8 : cf_8 ≤ 1 := by rw [e_cf_8]; exact addc_carry_le_one r3_2 0 cf_7 b_r3_2 (by decide) b_cf_7
  clear e_r3_3 e_cf_8
  subst hr
  -- BEGIN updateAbShift_spec conclusion
  refine ⟨⟨b_r0_3, b_r1_3, b_r2_3, b_r3_3⟩,
    r0_1, r1_1, r2_1, r3_1, mask_1, bit_1, cf_8, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩
  · rw [e_r0_1, e_r0, e_r1]
  · rw [e_r1_1, e_r1, e_r2]
  · rw [e_r2_1, e_r2, e_r3]
  · rw [e_r3_1, e_r3, e_r4]
  · rw [e_mask_1, e_mask, e_r4]
  · rw [e_bit_1, e_bit]
  · exact b_cf_8
  · change r0_3 + 2^64 * r1_3 + 2^128 * r2_3 + 2^192 * r3_3 + 2^256 * cf_8 =
      bitXor r0_1 mask_1 + 2^64 * bitXor r1_1 mask_1 +
        2^128 * bitXor r2_1 mask_1 + 2^192 * bitXor r3_1 mask_1 + bit_1
    rw [e_r0_2] at l_r0_3
    rw [e_r1_2] at l_r1_3
    rw [e_r2_2] at l_r2_3
    rw [e_r3_2] at l_r3_3
    clear * - l_r0_3 l_r1_3 l_r2_3 l_r3_3
    omega
  · rfl
  · rfl
  -- END updateAbShift_spec conclusion

end PastaAsm.X86_64
