/-
Copyright (c) 2026 the pasta-asm contributors.
Released under the Apache License, Version 2.0, as described in the file LICENSE.
-/
import PastaAsm.X86_64.Spec.Arithmetic
import PastaAsm.X86_64.Transcription
import Mathlib.Tactic.ClearExcept

/-!
# Arithmetic helper blocks for x86-64 inversion

These proofs cover the small assembly helpers used by the Rust inversion compositions.  Each
instruction trace is generated by `lean/scripts/gen.py --skeleton X86_64:<name>`; only the theorem
statements and delimited annotation blocks are handwritten.
-/

namespace PastaAsm.X86_64

-- BEGIN generated-name lint
-- Generated x86 traces intentionally preserve source operand names such as `zero`.
set_option linter.constructorNameAsVariable false
-- END generated-name lint

-- BEGIN addWordsLimb_spec statement
/-- One `add_words` iteration returns the low word and the exact carry of adding its two input
words and the low bit loaded from the loop's carry variable. -/
theorem addWordsLimb_spec (lhs rhs carry : Nat) (hlhs : lhs < 2^64) (hrhs : rhs < 2^64)
    (hcarry : carry < 2^64) :
    ∀ r, r = addWordsLimb lhs rhs carry →
      r.value < 2^64 ∧ r.carry ≤ 1 ∧
        r.value + 2^64 * r.carry = lhs + rhs + bt carry 0 := by
  intro r hr
-- END addWordsLimb_spec statement
  -- generated skeleton for `addWordsLimb`: do not edit between the annotations
  unfold addWordsLimb at hr
  lift_lets at hr
  -- lhs': input lhs[i]
  extract_lets +onlyGivenNames lhs' at hr
  have e_lhs' : lhs' = lhs := rfl
  have b_lhs' : lhs' < 2^64 := by rw [e_lhs']; exact hlhs
  -- rhs': input rhs[i]
  extract_lets +onlyGivenNames rhs' at hr
  have e_rhs' : rhs' = rhs := rfl
  have b_rhs' : rhs' < 2^64 := by rw [e_rhs']; exact hrhs
  -- carry': input carry
  extract_lets +onlyGivenNames carry' at hr
  have e_carry' : carry' = carry := rfl
  have b_carry' : carry' < 2^64 := by rw [e_carry']; exact hcarry
  -- cf: bt {carry}, 0
  extract_lets +onlyGivenNames cf at hr
  have e_cf : cf = bt carry' 0 := rfl
  have b_cf : cf ≤ 1 := by rw [e_cf]; exact bt_le_one _ _
  -- lhs_1: adc {lhs}, {rhs}
  extract_lets +onlyGivenNames s lhs_1 cf_1 at hr
  have e_lhs_1 : lhs_1 = (addc lhs' rhs' cf).1 := rfl
  have e_cf_1 : cf_1 = (addc lhs' rhs' cf).2 := rfl
  have l_lhs_1 : lhs_1 + 2^64 * cf_1 = lhs' + rhs' + cf := by
    rw [e_lhs_1, e_cf_1]; exact addc_lin lhs' rhs' cf
  have b_lhs_1 : lhs_1 < 2^64 := by rw [e_lhs_1]; exact addc_value_lt lhs' rhs' cf
  have b_cf_1 : cf_1 ≤ 1 := by rw [e_cf_1]; exact addc_carry_le_one lhs' rhs' cf b_lhs' b_rhs' b_cf
  clear e_lhs_1 e_cf_1
  -- carry_1: sbb {carry}, {carry}
  extract_lets +onlyGivenNames s_1 carry_1 cf_2 at hr
  have e_carry_1 : carry_1 = (sbb carry' carry' cf_1).1 := rfl
  have e_cf_2 : cf_2 = (sbb carry' carry' cf_1).2 := rfl
  have l_carry_1 : carry_1 + carry' + cf_1 = carry' + 2^64 * cf_2 := by
    rw [e_carry_1, e_cf_2]; exact sbb_lin carry' carry' cf_1 b_carry' b_carry' b_cf_1
  have b_carry_1 : carry_1 < 2^64 := by rw [e_carry_1]; exact sbb_value_lt carry' carry' cf_1
  have b_cf_2 : cf_2 ≤ 1 := by rw [e_cf_2]; exact sbb_borrow_le_one carry' carry' cf_1
  clear e_carry_1 e_cf_2
  -- s_2: neg {carry}
  extract_lets +onlyGivenNames s_2 carry_2 cf_3 at hr
  have e_carry_2 : carry_2 = (neg carry_1).1 := rfl
  have e_cf_3 : cf_3 = (neg carry_1).2 := rfl
  have b_carry_2 : carry_2 < 2^64 := by rw [e_carry_2]; exact sbb_value_lt 0 carry_1 0
  have b_cf_3 : cf_3 ≤ 1 := by
    rw [e_cf_3]; simp only [neg]; split <;> omega
  subst hr
  -- BEGIN addWordsLimb_spec conclusion
  have hcarryOut : carry_2 = cf_1 := by
    obtain hcf | hcf : cf_1 = 0 ∨ cf_1 = 1 := by omega
    · have hc : carry_1 = 0 := by omega
      rw [e_carry_2, hc, hcf]
      rfl
    · have hc : carry_1 = 2^64 - 1 := by omega
      rw [e_carry_2, hc, hcf]
      norm_num [neg, sbb, regMod]
  refine ⟨b_lhs_1, ?_, ?_⟩
  · rw [hcarryOut]
    exact b_cf_1
  · change lhs_1 + 2^64 * carry_2 = lhs + rhs + bt carry 0
    rw [hcarryOut]
    rw [e_lhs', e_rhs', e_cf, e_carry'] at l_lhs_1
    exact l_lhs_1
  -- END addWordsLimb_spec conclusion

-- BEGIN mulSignedLimb_spec statement
/-- One modeled `mul_signed` iteration first transforms its input limb with the supplied sign mask
and negation carry, then multiplies that word by the magnitude and adds the incoming product carry.
The witnesses expose both exact base-`2^64` equations; `topCarry` is the carry discarded above the
returned high word.  This theorem is local to the generated helper transcription and does not assume
that a caller supplied a coherent signed-scalar state. -/
theorem mulSignedLimb_spec (limb sign negateCarry magnitude productCarry : Nat)
    (hlimb : limb < 2^64) (hsign : sign < 2^64) (hnegateCarry : negateCarry < 2^64)
    (hmagnitude : magnitude < 2^64) (hproductCarry : productCarry < 2^64) :
    ∀ r, r = mulSignedLimb limb sign negateCarry magnitude productCarry →
      r.low < 2^64 ∧ r.high < 2^64 ∧ r.negateCarry ≤ 1 ∧
        ∃ transformed topCarry,
          transformed < 2^64 ∧ topCarry ≤ 1 ∧
          transformed + 2^64 * r.negateCarry = bitXor limb sign + negateCarry ∧
          r.low + 2^64 * r.high + 2^128 * topCarry =
            transformed * magnitude + productCarry := by
  intro r hr
-- END mulSignedLimb_spec statement
  -- generated skeleton for `mulSignedLimb`: do not edit between the annotations
  unfold mulSignedLimb at hr
  lift_lets at hr
  -- limb': input limb
  extract_lets +onlyGivenNames limb' at hr
  have e_limb' : limb' = limb := rfl
  have b_limb' : limb' < 2^64 := by rw [e_limb']; exact hlimb
  -- sign': input sign
  extract_lets +onlyGivenNames sign' at hr
  have e_sign' : sign' = sign := rfl
  have b_sign' : sign' < 2^64 := by rw [e_sign']; exact hsign
  -- negate_carry: input negate_carry
  extract_lets +onlyGivenNames negate_carry at hr
  have e_negate_carry : negate_carry = negateCarry := rfl
  have b_negate_carry : negate_carry < 2^64 := by rw [e_negate_carry]; exact hnegateCarry
  -- magnitude': input magnitude
  extract_lets +onlyGivenNames magnitude' at hr
  have e_magnitude' : magnitude' = magnitude := rfl
  have b_magnitude' : magnitude' < 2^64 := by rw [e_magnitude']; exact hmagnitude
  -- product_carry: input product_carry
  extract_lets +onlyGivenNames product_carry at hr
  have e_product_carry : product_carry = productCarry := rfl
  have b_product_carry : product_carry < 2^64 := by rw [e_product_carry]; exact hproductCarry
  -- limb_1: xor {limb}, {sign}
  extract_lets +onlyGivenNames limb_1 cf zf at hr
  have e_limb_1 : limb_1 = bitXor limb' sign' := rfl
  have e_cf : cf = 0 := rfl
  have e_zf : zf = zeroFlag limb_1 := rfl
  have b_limb_1 : limb_1 < 2^64 := by rw [e_limb_1]; exact bitXor_lt _ _
  have b_cf : cf ≤ 1 := by rw [e_cf]; decide
  have b_zf : zf ≤ 1 := by rw [e_zf]; exact zeroFlag_le_one _
  -- limb_2: add {limb}, {negate_carry}
  extract_lets +onlyGivenNames s limb_2 cf_1 at hr
  have e_limb_2 : limb_2 = (addc limb_1 negate_carry 0).1 := rfl
  have e_cf_1 : cf_1 = (addc limb_1 negate_carry 0).2 := rfl
  have l_limb_2 : limb_2 + 2^64 * cf_1 = limb_1 + negate_carry + 0 := by
    rw [e_limb_2, e_cf_1]; exact addc_lin limb_1 negate_carry 0
  have b_limb_2 : limb_2 < 2^64 := by rw [e_limb_2]; exact addc_value_lt limb_1 negate_carry 0
  have b_cf_1 : cf_1 ≤ 1 := by rw [e_cf_1]; exact addc_carry_le_one limb_1 negate_carry 0 b_limb_1 b_negate_carry (by decide)
  clear e_limb_2 e_cf_1
  -- next_negate_carry: setc {next_negate_carry}
  extract_lets +onlyGivenNames next_negate_carry at hr
  have e_next_negate_carry : next_negate_carry = setc cf_1 := rfl
  have b_next_negate_carry : next_negate_carry ≤ 1 := by rw [e_next_negate_carry]; exact setc_le_one _
  -- rax: mov rax, {limb}
  extract_lets +onlyGivenNames rax at hr
  have e_rax : rax = limb_2 := rfl
  have b_rax : rax < 2^64 := by rw [e_rax]; exact b_limb_2
  -- rdx: mul {magnitude}
  extract_lets +onlyGivenNames rdx at hr
  have e_rdx : rdx = rax * magnitude' / 2^64 := rfl
  have p_rdx : rax * magnitude' < 2^64 * 2^64 := Nat.mul_lt_mul'' b_rax b_magnitude'
  have b_rdx : rdx < 2^64 := by rw [e_rdx]; exact Nat.div_lt_of_lt_mul p_rdx
  obtain ⟨lo_rdx, b_lo_rdx, d_rdx⟩ :
      ∃ lo, lo < 2^64 ∧ lo + 2^64 * rdx = rax * magnitude' :=
    ⟨rax * magnitude' % 2^64, Nat.mod_lt _ (Nat.two_pow_pos _),
      by rw [e_rdx]; exact Nat.mod_add_div _ _⟩
  clear e_rdx
  -- rax_1: None
  extract_lets +onlyGivenNames rax_1 at hr
  have e_rax_1 : rax_1 = rax * magnitude' % 2^64 := rfl
  have b_rax_1 : rax_1 < 2^64 := by rw [e_rax_1]; exact Nat.mod_lt _ (Nat.two_pow_pos _)
  -- rax_2: add rax, {product_carry}
  extract_lets +onlyGivenNames s_1 rax_2 cf_2 at hr
  have e_rax_2 : rax_2 = (addc rax_1 product_carry 0).1 := rfl
  have e_cf_2 : cf_2 = (addc rax_1 product_carry 0).2 := rfl
  have l_rax_2 : rax_2 + 2^64 * cf_2 = rax_1 + product_carry + 0 := by
    rw [e_rax_2, e_cf_2]; exact addc_lin rax_1 product_carry 0
  have b_rax_2 : rax_2 < 2^64 := by rw [e_rax_2]; exact addc_value_lt rax_1 product_carry 0
  have b_cf_2 : cf_2 ≤ 1 := by rw [e_cf_2]; exact addc_carry_le_one rax_1 product_carry 0 b_rax_1 b_product_carry (by decide)
  clear e_rax_2 e_cf_2
  -- rdx_1: adc rdx, 0
  extract_lets +onlyGivenNames s_2 rdx_1 cf_3 at hr
  have e_rdx_1 : rdx_1 = (addc rdx 0 cf_2).1 := rfl
  have e_cf_3 : cf_3 = (addc rdx 0 cf_2).2 := rfl
  have l_rdx_1 : rdx_1 + 2^64 * cf_3 = rdx + 0 + cf_2 := by
    rw [e_rdx_1, e_cf_3]; exact addc_lin rdx 0 cf_2
  have b_rdx_1 : rdx_1 < 2^64 := by rw [e_rdx_1]; exact addc_value_lt rdx 0 cf_2
  have b_cf_3 : cf_3 ≤ 1 := by rw [e_cf_3]; exact addc_carry_le_one rdx 0 cf_2 b_rdx (by decide) b_cf_2
  clear e_rdx_1 e_cf_3
  subst hr
  -- BEGIN mulSignedLimb_spec conclusion
  have hnegateCarry : next_negate_carry = cf_1 := by
    rw [e_next_negate_carry, setc]
    exact Nat.mod_eq_of_lt (by omega)
  have hproduct : rax_1 + 2^64 * rdx = rax * magnitude' := by
    rw [e_rax_1]
    exact Nat.mod_add_div _ _
  refine ⟨b_rax_2, b_rdx_1, b_next_negate_carry, limb_2, cf_3,
    b_limb_2, b_cf_3, ?_, ?_⟩
  · change limb_2 + 2^64 * next_negate_carry = bitXor limb sign + negateCarry
    rw [hnegateCarry]
    rw [e_limb_1, e_limb', e_sign', e_negate_carry] at l_limb_2
    exact l_limb_2
  · change rax_2 + 2^64 * rdx_1 + 2^128 * cf_3 = limb_2 * magnitude + productCarry
    rw [e_rax, e_magnitude'] at hproduct
    rw [e_product_carry] at l_rax_2
    clear * - hproduct l_rax_2 l_rdx_1
    omega
  -- END mulSignedLimb_spec conclusion

-- BEGIN x86 inversion mask lemmas
/-- Arithmetic shift by 63 produces the 64-bit sign mask. -/
theorem sar63_eq_signMask {a : Nat} (ha : a < 2^64) :
    sar a 63 = if a < 2^63 then 0 else 2^64 - 1 := by
  unfold sar bit lsr
  norm_num
  rw [word_eq_of_lt ha]
  have hsplit := Nat.mod_add_div a (2^63)
  have hquot : a / 2^63 ≤ 1 := by omega
  obtain hq | hq : a / 2^63 = 0 ∨ a / 2^63 = 1 := by omega
  · have hlt : a < 2^63 := by omega
    have hq' : a / 9223372036854775808 = 0 := by simpa only [Nat.reducePow] using hq
    have hlt' : a < 9223372036854775808 := by simpa only [Nat.reducePow] using hlt
    rw [hq', if_pos hlt']
    norm_num [word, regMod]
  · have hnlt : ¬a < 2^63 := by omega
    have hq' : a / 9223372036854775808 = 1 := by simpa only [Nat.reducePow] using hq
    have hnlt' : ¬a < 9223372036854775808 := by simpa only [Nat.reducePow] using hnlt
    rw [hq', if_neg hnlt']
    norm_num [word, regMod]

/-- AND with the 64-bit all-ones mask preserves a bounded register. -/
theorem bitAnd_allOnes {a : Nat} (ha : a < 2^64) : bitAnd a (2^64 - 1) = a := by
  unfold bitAnd
  rw [word_eq_of_lt ha]
  rw [word_eq_of_lt (by simp only [regMod]; omega : 2^64 - 1 < regMod)]
  rw [Nat.and_two_pow_sub_one_eq_mod, Nat.mod_eq_of_lt ha, word_eq_of_lt ha]
-- END x86 inversion mask lemmas

-- BEGIN normalizeNegative_spec statement
/-- The first normalization block adds the four-limb `modulus2` to the high half exactly when the
excess word has its sign bit set.  The returned five words and a one-bit discarded carry reconstruct
that selected five-word addition. -/
theorem normalizeNegative_spec (value : PastaAsm.WideLimbs) (modulus2 : Limbs)
    (hv : value.Bounded) (hmodulus2 : modulus2.Bounded) :
    ∀ r, r = normalizeNegative value modulus2 →
      r.h0 < 2^64 ∧ r.h1 < 2^64 ∧ r.h2 < 2^64 ∧ r.h3 < 2^64 ∧ r.excess < 2^64 ∧
        ∃ carry, carry ≤ 1 ∧
          r.h0 + 2^64 * r.h1 + 2^128 * r.h2 + 2^192 * r.h3 + 2^256 * r.excess +
              2^320 * carry =
            value.l4 + 2^64 * value.l5 + 2^128 * value.l6 + 2^192 * value.l7 +
              2^256 * value.l8 +
              (if value.l8 < 2^63 then 0 else modulus2.toNat) := by
  intro r hr
-- END normalizeNegative_spec statement
  -- generated skeleton for `normalizeNegative`: do not edit between the annotations
  unfold normalizeNegative at hr
  lift_lets at hr
  -- h0: input h0
  extract_lets +onlyGivenNames h0 at hr
  have e_h0 : h0 = value.l4 := rfl
  have b_h0 : h0 < 2^64 := by rw [e_h0]; exact hv.2.2.2.2.1
  -- h1: input h1
  extract_lets +onlyGivenNames h1 at hr
  have e_h1 : h1 = value.l5 := rfl
  have b_h1 : h1 < 2^64 := by rw [e_h1]; exact hv.2.2.2.2.2.1
  -- h2: input h2
  extract_lets +onlyGivenNames h2 at hr
  have e_h2 : h2 = value.l6 := rfl
  have b_h2 : h2 < 2^64 := by rw [e_h2]; exact hv.2.2.2.2.2.2.1
  -- h3: input h3
  extract_lets +onlyGivenNames h3 at hr
  have e_h3 : h3 = value.l7 := rfl
  have b_h3 : h3 < 2^64 := by rw [e_h3]; exact hv.2.2.2.2.2.2.2.1
  -- excess: input excess
  extract_lets +onlyGivenNames excess at hr
  have e_excess : excess = value.l8 := rfl
  have b_excess : excess < 2^64 := by rw [e_excess]; exact hv.2.2.2.2.2.2.2.2
  -- m0: input m0
  extract_lets +onlyGivenNames m0 at hr
  have e_m0 : m0 = modulus2.l0 := rfl
  have b_m0 : m0 < 2^64 := by rw [e_m0]; exact hmodulus2.1
  -- m1: input m1
  extract_lets +onlyGivenNames m1 at hr
  have e_m1 : m1 = modulus2.l1 := rfl
  have b_m1 : m1 < 2^64 := by rw [e_m1]; exact hmodulus2.2.1
  -- m2: input m2
  extract_lets +onlyGivenNames m2 at hr
  have e_m2 : m2 = modulus2.l2 := rfl
  have b_m2 : m2 < 2^64 := by rw [e_m2]; exact hmodulus2.2.2.1
  -- m3: input m3
  extract_lets +onlyGivenNames m3 at hr
  have e_m3 : m3 = modulus2.l3 := rfl
  have b_m3 : m3 < 2^64 := by rw [e_m3]; exact hmodulus2.2.2.2
  -- mask: mov {mask}, {excess}
  extract_lets +onlyGivenNames mask at hr
  have e_mask : mask = excess := rfl
  have b_mask : mask < 2^64 := by rw [e_mask]; exact b_excess
  -- mask_1: sar {mask}, 63
  extract_lets +onlyGivenNames mask_1 at hr
  have e_mask_1 : mask_1 = sar mask 63 := rfl
  have b_mask_1 : mask_1 < 2^64 := by rw [e_mask_1]; exact sar_lt _ _
  -- m0_1: and {m0}, {mask}
  extract_lets +onlyGivenNames m0_1 cf zf at hr
  have e_m0_1 : m0_1 = bitAnd m0 mask_1 := rfl
  have e_cf : cf = 0 := rfl
  have e_zf : zf = zeroFlag m0_1 := rfl
  have b_m0_1 : m0_1 < 2^64 := by rw [e_m0_1]; exact bitAnd_lt _ _
  have b_cf : cf ≤ 1 := by rw [e_cf]; decide
  have b_zf : zf ≤ 1 := by rw [e_zf]; exact zeroFlag_le_one _
  -- m1_1: and {m1}, {mask}
  extract_lets +onlyGivenNames m1_1 zf_1 at hr
  have e_m1_1 : m1_1 = bitAnd m1 mask_1 := rfl
  have e_zf_1 : zf_1 = zeroFlag m1_1 := rfl
  have b_m1_1 : m1_1 < 2^64 := by rw [e_m1_1]; exact bitAnd_lt _ _
  have b_zf_1 : zf_1 ≤ 1 := by rw [e_zf_1]; exact zeroFlag_le_one _
  -- m2_1: and {m2}, {mask}
  extract_lets +onlyGivenNames m2_1 zf_2 at hr
  have e_m2_1 : m2_1 = bitAnd m2 mask_1 := rfl
  have e_zf_2 : zf_2 = zeroFlag m2_1 := rfl
  have b_m2_1 : m2_1 < 2^64 := by rw [e_m2_1]; exact bitAnd_lt _ _
  have b_zf_2 : zf_2 ≤ 1 := by rw [e_zf_2]; exact zeroFlag_le_one _
  -- m3_1: and {m3}, {mask}
  extract_lets +onlyGivenNames m3_1 zf_3 at hr
  have e_m3_1 : m3_1 = bitAnd m3 mask_1 := rfl
  have e_zf_3 : zf_3 = zeroFlag m3_1 := rfl
  have b_m3_1 : m3_1 < 2^64 := by rw [e_m3_1]; exact bitAnd_lt _ _
  have b_zf_3 : zf_3 ≤ 1 := by rw [e_zf_3]; exact zeroFlag_le_one _
  -- h0_1: add {h0}, {m0}
  extract_lets +onlyGivenNames s h0_1 cf_4 at hr
  have e_h0_1 : h0_1 = (addc h0 m0_1 0).1 := rfl
  have e_cf_4 : cf_4 = (addc h0 m0_1 0).2 := rfl
  have l_h0_1 : h0_1 + 2^64 * cf_4 = h0 + m0_1 + 0 := by
    rw [e_h0_1, e_cf_4]; exact addc_lin h0 m0_1 0
  have b_h0_1 : h0_1 < 2^64 := by rw [e_h0_1]; exact addc_value_lt h0 m0_1 0
  have b_cf_4 : cf_4 ≤ 1 := by rw [e_cf_4]; exact addc_carry_le_one h0 m0_1 0 b_h0 b_m0_1 (by decide)
  clear e_h0_1 e_cf_4
  -- h1_1: adc {h1}, {m1}
  extract_lets +onlyGivenNames s_1 h1_1 cf_5 at hr
  have e_h1_1 : h1_1 = (addc h1 m1_1 cf_4).1 := rfl
  have e_cf_5 : cf_5 = (addc h1 m1_1 cf_4).2 := rfl
  have l_h1_1 : h1_1 + 2^64 * cf_5 = h1 + m1_1 + cf_4 := by
    rw [e_h1_1, e_cf_5]; exact addc_lin h1 m1_1 cf_4
  have b_h1_1 : h1_1 < 2^64 := by rw [e_h1_1]; exact addc_value_lt h1 m1_1 cf_4
  have b_cf_5 : cf_5 ≤ 1 := by rw [e_cf_5]; exact addc_carry_le_one h1 m1_1 cf_4 b_h1 b_m1_1 b_cf_4
  clear e_h1_1 e_cf_5
  -- h2_1: adc {h2}, {m2}
  extract_lets +onlyGivenNames s_2 h2_1 cf_6 at hr
  have e_h2_1 : h2_1 = (addc h2 m2_1 cf_5).1 := rfl
  have e_cf_6 : cf_6 = (addc h2 m2_1 cf_5).2 := rfl
  have l_h2_1 : h2_1 + 2^64 * cf_6 = h2 + m2_1 + cf_5 := by
    rw [e_h2_1, e_cf_6]; exact addc_lin h2 m2_1 cf_5
  have b_h2_1 : h2_1 < 2^64 := by rw [e_h2_1]; exact addc_value_lt h2 m2_1 cf_5
  have b_cf_6 : cf_6 ≤ 1 := by rw [e_cf_6]; exact addc_carry_le_one h2 m2_1 cf_5 b_h2 b_m2_1 b_cf_5
  clear e_h2_1 e_cf_6
  -- h3_1: adc {h3}, {m3}
  extract_lets +onlyGivenNames s_3 h3_1 cf_7 at hr
  have e_h3_1 : h3_1 = (addc h3 m3_1 cf_6).1 := rfl
  have e_cf_7 : cf_7 = (addc h3 m3_1 cf_6).2 := rfl
  have l_h3_1 : h3_1 + 2^64 * cf_7 = h3 + m3_1 + cf_6 := by
    rw [e_h3_1, e_cf_7]; exact addc_lin h3 m3_1 cf_6
  have b_h3_1 : h3_1 < 2^64 := by rw [e_h3_1]; exact addc_value_lt h3 m3_1 cf_6
  have b_cf_7 : cf_7 ≤ 1 := by rw [e_cf_7]; exact addc_carry_le_one h3 m3_1 cf_6 b_h3 b_m3_1 b_cf_6
  clear e_h3_1 e_cf_7
  -- excess_1: adc {excess}, 0
  extract_lets +onlyGivenNames s_4 excess_1 cf_8 at hr
  have e_excess_1 : excess_1 = (addc excess 0 cf_7).1 := rfl
  have e_cf_8 : cf_8 = (addc excess 0 cf_7).2 := rfl
  have l_excess_1 : excess_1 + 2^64 * cf_8 = excess + 0 + cf_7 := by
    rw [e_excess_1, e_cf_8]; exact addc_lin excess 0 cf_7
  have b_excess_1 : excess_1 < 2^64 := by rw [e_excess_1]; exact addc_value_lt excess 0 cf_7
  have b_cf_8 : cf_8 ≤ 1 := by rw [e_cf_8]; exact addc_carry_le_one excess 0 cf_7 b_excess (by decide) b_cf_7
  clear e_excess_1 e_cf_8
  subst hr
  -- BEGIN normalizeNegative_spec conclusion
  have hmask : mask_1 = if value.l8 < 2^63 then 0 else 2^64 - 1 := by
    rw [e_mask_1, e_mask, e_excess]
    exact sar63_eq_signMask hv.2.2.2.2.2.2.2.2
  by_cases hsign : value.l8 < 2^63
  · rw [if_pos hsign] at hmask ⊢
    have hm0 : m0_1 = 0 := by simp only [e_m0_1, hmask, bitAnd, word_zero, Nat.and_zero]
    have hm1 : m1_1 = 0 := by simp only [e_m1_1, hmask, bitAnd, word_zero, Nat.and_zero]
    have hm2 : m2_1 = 0 := by simp only [e_m2_1, hmask, bitAnd, word_zero, Nat.and_zero]
    have hm3 : m3_1 = 0 := by simp only [e_m3_1, hmask, bitAnd, word_zero, Nat.and_zero]
    refine ⟨b_h0_1, b_h1_1, b_h2_1, b_h3_1, b_excess_1, cf_8, b_cf_8, ?_⟩
    change h0_1 + 2^64 * h1_1 + 2^128 * h2_1 + 2^192 * h3_1 +
        2^256 * excess_1 + 2^320 * cf_8 =
      value.l4 + 2^64 * value.l5 + 2^128 * value.l6 + 2^192 * value.l7 +
        2^256 * value.l8 + 0
    rw [e_h0] at l_h0_1
    rw [e_h1] at l_h1_1
    rw [e_h2] at l_h2_1
    rw [e_h3] at l_h3_1
    rw [e_excess] at l_excess_1
    clear * - l_h0_1 l_h1_1 l_h2_1 l_h3_1 l_excess_1 hm0 hm1 hm2 hm3
    omega
  · rw [if_neg hsign] at hmask ⊢
    have hm0 : m0_1 = m0 := by rw [e_m0_1, hmask]; exact bitAnd_allOnes b_m0
    have hm1 : m1_1 = m1 := by rw [e_m1_1, hmask]; exact bitAnd_allOnes b_m1
    have hm2 : m2_1 = m2 := by rw [e_m2_1, hmask]; exact bitAnd_allOnes b_m2
    have hm3 : m3_1 = m3 := by rw [e_m3_1, hmask]; exact bitAnd_allOnes b_m3
    refine ⟨b_h0_1, b_h1_1, b_h2_1, b_h3_1, b_excess_1, cf_8, b_cf_8, ?_⟩
    change h0_1 + 2^64 * h1_1 + 2^128 * h2_1 + 2^192 * h3_1 +
        2^256 * excess_1 + 2^320 * cf_8 =
      value.l4 + 2^64 * value.l5 + 2^128 * value.l6 + 2^192 * value.l7 +
        2^256 * value.l8 +
          (modulus2.l0 + 2^64 * modulus2.l1 + 2^128 * modulus2.l2 +
            2^192 * modulus2.l3)
    rw [e_h0] at l_h0_1
    rw [e_h1] at l_h1_1
    rw [e_h2] at l_h2_1
    rw [e_h3] at l_h3_1
    rw [e_excess] at l_excess_1
    rw [e_m0] at hm0
    rw [e_m1] at hm1
    rw [e_m2] at hm2
    rw [e_m3] at hm3
    clear * - l_h0_1 l_h1_1 l_h2_1 l_h3_1 l_excess_1 hm0 hm1 hm2 hm3
    omega
  -- END normalizeNegative_spec conclusion

-- BEGIN reduceOnce_spec statement
/-- The inversion epilogue's reduction helper performs one exact conditional subtraction.  The
assembly hard-codes the third modulus limb as zero, matching the Pasta modulus shape. -/
theorem reduceOnce_spec (value modulus : Limbs) (hv : value.Bounded) (hm : modulus.Bounded)
    (hshape : modulus.l2 = 0) :
    ∀ r, r = reduceOnce value modulus →
      r.Bounded ∧
        ((value.toNat < modulus.toNat ∧ r.toNat = value.toNat) ∨
          (modulus.toNat ≤ value.toNat ∧ r.toNat + modulus.toNat = value.toNat)) := by
  intro r hr
-- END reduceOnce_spec statement
  -- generated skeleton for `reduceOnce`: do not edit between the annotations
  unfold reduceOnce at hr
  lift_lets at hr
  -- r0: input value[0]
  extract_lets +onlyGivenNames r0 at hr
  have e_r0 : r0 = value.l0 := rfl
  have b_r0 : r0 < 2^64 := by rw [e_r0]; exact hv.1
  -- r1: input value[1]
  extract_lets +onlyGivenNames r1 at hr
  have e_r1 : r1 = value.l1 := rfl
  have b_r1 : r1 < 2^64 := by rw [e_r1]; exact hv.2.1
  -- r2: input value[2]
  extract_lets +onlyGivenNames r2 at hr
  have e_r2 : r2 = value.l2 := rfl
  have b_r2 : r2 < 2^64 := by rw [e_r2]; exact hv.2.2.1
  -- r3: input value[3]
  extract_lets +onlyGivenNames r3 at hr
  have e_r3 : r3 = value.l3 := rfl
  have b_r3 : r3 < 2^64 := by rw [e_r3]; exact hv.2.2.2
  -- p0: input p0
  extract_lets +onlyGivenNames p0 at hr
  have e_p0 : p0 = modulus.l0 := rfl
  have b_p0 : p0 < 2^64 := by rw [e_p0]; exact hm.1
  -- p1: input p1
  extract_lets +onlyGivenNames p1 at hr
  have e_p1 : p1 = modulus.l1 := rfl
  have b_p1 : p1 < 2^64 := by rw [e_p1]; exact hm.2.1
  -- p3: input p3
  extract_lets +onlyGivenNames p3 at hr
  have e_p3 : p3 = modulus.l3 := rfl
  have b_p3 : p3 < 2^64 := by rw [e_p3]; exact hm.2.2.2
  -- r0_1: sub {r0}, {p0}
  extract_lets +onlyGivenNames s r0_1 cf at hr
  have e_r0_1 : r0_1 = (sbb r0 p0 0).1 := rfl
  have e_cf : cf = (sbb r0 p0 0).2 := rfl
  have l_r0_1 : r0_1 + p0 + 0 = r0 + 2^64 * cf := by
    rw [e_r0_1, e_cf]; exact sbb_lin r0 p0 0 b_r0 b_p0 (by decide)
  have b_r0_1 : r0_1 < 2^64 := by rw [e_r0_1]; exact sbb_value_lt r0 p0 0
  have b_cf : cf ≤ 1 := by rw [e_cf]; exact sbb_borrow_le_one r0 p0 0
  clear e_r0_1 e_cf
  -- r1_1: sbb {r1}, {p1}
  extract_lets +onlyGivenNames s_1 r1_1 cf_1 at hr
  have e_r1_1 : r1_1 = (sbb r1 p1 cf).1 := rfl
  have e_cf_1 : cf_1 = (sbb r1 p1 cf).2 := rfl
  have l_r1_1 : r1_1 + p1 + cf = r1 + 2^64 * cf_1 := by
    rw [e_r1_1, e_cf_1]; exact sbb_lin r1 p1 cf b_r1 b_p1 b_cf
  have b_r1_1 : r1_1 < 2^64 := by rw [e_r1_1]; exact sbb_value_lt r1 p1 cf
  have b_cf_1 : cf_1 ≤ 1 := by rw [e_cf_1]; exact sbb_borrow_le_one r1 p1 cf
  clear e_r1_1 e_cf_1
  -- r2_1: sbb {r2}, 0
  extract_lets +onlyGivenNames s_2 r2_1 cf_2 at hr
  have e_r2_1 : r2_1 = (sbb r2 0 cf_1).1 := rfl
  have e_cf_2 : cf_2 = (sbb r2 0 cf_1).2 := rfl
  have l_r2_1 : r2_1 + 0 + cf_1 = r2 + 2^64 * cf_2 := by
    rw [e_r2_1, e_cf_2]; exact sbb_lin r2 0 cf_1 b_r2 (by decide) b_cf_1
  have b_r2_1 : r2_1 < 2^64 := by rw [e_r2_1]; exact sbb_value_lt r2 0 cf_1
  have b_cf_2 : cf_2 ≤ 1 := by rw [e_cf_2]; exact sbb_borrow_le_one r2 0 cf_1
  clear e_r2_1 e_cf_2
  -- r3_1: sbb {r3}, {p3}
  extract_lets +onlyGivenNames s_3 r3_1 cf_3 at hr
  have e_r3_1 : r3_1 = (sbb r3 p3 cf_2).1 := rfl
  have e_cf_3 : cf_3 = (sbb r3 p3 cf_2).2 := rfl
  have l_r3_1 : r3_1 + p3 + cf_2 = r3 + 2^64 * cf_3 := by
    rw [e_r3_1, e_cf_3]; exact sbb_lin r3 p3 cf_2 b_r3 b_p3 b_cf_2
  have b_r3_1 : r3_1 < 2^64 := by rw [e_r3_1]; exact sbb_value_lt r3 p3 cf_2
  have b_cf_3 : cf_3 ≤ 1 := by rw [e_cf_3]; exact sbb_borrow_le_one r3 p3 cf_2
  clear e_r3_1 e_cf_3
  -- zero: mov {zero:e}, 0
  extract_lets +onlyGivenNames zero at hr
  have e_zero : zero = word32 0 := rfl
  have b_zero : zero < 2^64 := by rw [e_zero]; exact Nat.lt_trans (word32_lt _) (by decide)
  -- p0_1: cmovnc {p0}, {zero}
  extract_lets +onlyGivenNames p0_1 at hr
  have e_p0_1 : p0_1 = (if cf_3 = 0 then zero else p0) := rfl
  have b_p0_1 : p0_1 < 2^64 := by
    rw [e_p0_1]; split <;> first | exact b_zero | exact b_p0
  -- p1_1: cmovnc {p1}, {zero}
  extract_lets +onlyGivenNames p1_1 at hr
  have e_p1_1 : p1_1 = (if cf_3 = 0 then zero else p1) := rfl
  have b_p1_1 : p1_1 < 2^64 := by
    rw [e_p1_1]; split <;> first | exact b_zero | exact b_p1
  -- p3_1: cmovnc {p3}, {zero}
  extract_lets +onlyGivenNames p3_1 at hr
  have e_p3_1 : p3_1 = (if cf_3 = 0 then zero else p3) := rfl
  have b_p3_1 : p3_1 < 2^64 := by
    rw [e_p3_1]; split <;> first | exact b_zero | exact b_p3
  -- r0_2: add {r0}, {p0}
  extract_lets +onlyGivenNames s_4 r0_2 cf_4 at hr
  have e_r0_2 : r0_2 = (addc r0_1 p0_1 0).1 := rfl
  have e_cf_4 : cf_4 = (addc r0_1 p0_1 0).2 := rfl
  have l_r0_2 : r0_2 + 2^64 * cf_4 = r0_1 + p0_1 + 0 := by
    rw [e_r0_2, e_cf_4]; exact addc_lin r0_1 p0_1 0
  have b_r0_2 : r0_2 < 2^64 := by rw [e_r0_2]; exact addc_value_lt r0_1 p0_1 0
  have b_cf_4 : cf_4 ≤ 1 := by rw [e_cf_4]; exact addc_carry_le_one r0_1 p0_1 0 b_r0_1 b_p0_1 (by decide)
  clear e_r0_2 e_cf_4
  -- r1_2: adc {r1}, {p1}
  extract_lets +onlyGivenNames s_5 r1_2 cf_5 at hr
  have e_r1_2 : r1_2 = (addc r1_1 p1_1 cf_4).1 := rfl
  have e_cf_5 : cf_5 = (addc r1_1 p1_1 cf_4).2 := rfl
  have l_r1_2 : r1_2 + 2^64 * cf_5 = r1_1 + p1_1 + cf_4 := by
    rw [e_r1_2, e_cf_5]; exact addc_lin r1_1 p1_1 cf_4
  have b_r1_2 : r1_2 < 2^64 := by rw [e_r1_2]; exact addc_value_lt r1_1 p1_1 cf_4
  have b_cf_5 : cf_5 ≤ 1 := by rw [e_cf_5]; exact addc_carry_le_one r1_1 p1_1 cf_4 b_r1_1 b_p1_1 b_cf_4
  clear e_r1_2 e_cf_5
  -- r2_2: adc {r2}, 0
  extract_lets +onlyGivenNames s_6 r2_2 cf_6 at hr
  have e_r2_2 : r2_2 = (addc r2_1 0 cf_5).1 := rfl
  have e_cf_6 : cf_6 = (addc r2_1 0 cf_5).2 := rfl
  have l_r2_2 : r2_2 + 2^64 * cf_6 = r2_1 + 0 + cf_5 := by
    rw [e_r2_2, e_cf_6]; exact addc_lin r2_1 0 cf_5
  have b_r2_2 : r2_2 < 2^64 := by rw [e_r2_2]; exact addc_value_lt r2_1 0 cf_5
  have b_cf_6 : cf_6 ≤ 1 := by rw [e_cf_6]; exact addc_carry_le_one r2_1 0 cf_5 b_r2_1 (by decide) b_cf_5
  clear e_r2_2 e_cf_6
  -- r3_2: adc {r3}, {p3}
  extract_lets +onlyGivenNames s_7 r3_2 cf_7 at hr
  have e_r3_2 : r3_2 = (addc r3_1 p3_1 cf_6).1 := rfl
  have e_cf_7 : cf_7 = (addc r3_1 p3_1 cf_6).2 := rfl
  have l_r3_2 : r3_2 + 2^64 * cf_7 = r3_1 + p3_1 + cf_6 := by
    rw [e_r3_2, e_cf_7]; exact addc_lin r3_1 p3_1 cf_6
  have b_r3_2 : r3_2 < 2^64 := by rw [e_r3_2]; exact addc_value_lt r3_1 p3_1 cf_6
  have b_cf_7 : cf_7 ≤ 1 := by rw [e_cf_7]; exact addc_carry_le_one r3_1 p3_1 cf_6 b_r3_1 b_p3_1 b_cf_6
  clear e_r3_2 e_cf_7
  subst hr
  -- BEGIN reduceOnce_spec conclusion
  have hV : value.toNat = r0 + 2^64 * r1 + 2^128 * r2 + 2^192 * r3 := by
    rw [e_r0, e_r1, e_r2, e_r3]
    rfl
  have hP : modulus.toNat = p0 + 2^64 * p1 + 2^192 * p3 := by
    rw [e_p0, e_p1, e_p3]
    simp only [Limbs.toNat, hshape, mul_zero, add_zero]
  have hD : r0_1 + 2^64 * r1_1 + 2^128 * r2_1 + 2^192 * r3_1 + modulus.toNat =
      value.toNat + 2^256 * cf_3 := by
    rw [hV, hP]
    clear * - l_r0_1 l_r1_1 l_r2_1 l_r3_1
    omega
  have hD_lt : r0_1 + 2^64 * r1_1 + 2^128 * r2_1 + 2^192 * r3_1 < 2^256 := by
    clear * - b_r0_1 b_r1_1 b_r2_1 b_r3_1
    omega
  have hOut : r0_2 + 2^64 * r1_2 + 2^128 * r2_2 + 2^192 * r3_2 + 2^256 * cf_7 =
      r0_1 + 2^64 * r1_1 + 2^128 * r2_1 + 2^192 * r3_1 +
        (p0_1 + 2^64 * p1_1 + 2^192 * p3_1) := by
    clear * - l_r0_2 l_r1_2 l_r2_2 l_r3_2
    omega
  refine ⟨⟨b_r0_2, b_r1_2, b_r2_2, b_r3_2⟩, ?_⟩
  obtain hborrow | hborrow : cf_3 = 0 ∨ cf_3 = 1 := by
    clear * - b_cf_3
    omega
  · rw [if_pos hborrow] at e_p0_1 e_p1_1 e_p3_1
    have hselected : p0_1 + 2^64 * p1_1 + 2^192 * p3_1 = 0 := by
      clear * - e_zero e_p0_1 e_p1_1 e_p3_1
      norm_num [word32] at e_zero ⊢
      omega
    have hOut' : r0_2 + 2^64 * r1_2 + 2^128 * r2_2 + 2^192 * r3_2 + 2^256 * cf_7 =
        r0_1 + 2^64 * r1_1 + 2^128 * r2_1 + 2^192 * r3_1 := by
      clear * - hOut hselected
      omega
    have hfinal : cf_7 = 0 := by
      clear * - hOut' hD_lt
      omega
    right
    change modulus.toNat ≤ value.toNat ∧
      r0_2 + 2^64 * r1_2 + 2^128 * r2_2 + 2^192 * r3_2 + modulus.toNat = value.toNat
    clear * - hD hborrow hOut' hfinal
    omega
  · rw [if_neg (by omega)] at e_p0_1 e_p1_1 e_p3_1
    have hselected : p0_1 + 2^64 * p1_1 + 2^192 * p3_1 = modulus.toNat := by
      clear * - e_p0_1 e_p1_1 e_p3_1 hP
      omega
    have hOut' : r0_2 + 2^64 * r1_2 + 2^128 * r2_2 + 2^192 * r3_2 + 2^256 * cf_7 =
        r0_1 + 2^64 * r1_1 + 2^128 * r2_1 + 2^192 * r3_1 + modulus.toNat := by
      clear * - hOut hselected
      omega
    have hvalue_lt : value.toNat < 2^256 := Limbs.toNat_lt value hv
    have hOut_lt : r0_2 + 2^64 * r1_2 + 2^128 * r2_2 + 2^192 * r3_2 < 2^256 := by
      clear * - b_r0_2 b_r1_2 b_r2_2 b_r3_2
      omega
    have hfinal : cf_7 = 1 := by
      clear * - hD hborrow hOut' hvalue_lt hOut_lt b_cf_7
      omega
    left
    change value.toNat < modulus.toNat ∧
      r0_2 + 2^64 * r1_2 + 2^128 * r2_2 + 2^192 * r3_2 = value.toNat
    clear * - hD hD_lt hborrow hOut' hfinal
    omega
  -- END reduceOnce_spec conclusion

end PastaAsm.X86_64
