#!/usr/bin/env python3
# Copyright (c) 2026 the pasta-asm contributors.
# SPDX-License-Identifier: Apache-2.0
"""Architecture-specific x86-64 emitter for the unified Lean generator.

The shared :mod:`asm_source` parser extracts and validates the Rust function, asm
templates, declarations, options, locals, and source result order. This module
validates x86-64 instruction semantics, register initialization, memory reads, and
CF/OF use, then emits the mechanical SSA-style Lean transcription. The two full
internal multiplication rounds are factored only after their flattened binding IRs
match under the source's accumulator-register rotation and RHS-limb substitution.
Invoke it via ``python3 lean/scripts/gen.py`` or use ``--check`` for a non-writing
comparison.
"""

import dataclasses
import re
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Set, Tuple

import asm_source
import gen
from asm_source import Declaration, GenerationError, ParsedFunction


ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "src/x86_64.rs"
INVERT_SOURCE = ROOT / "src/x86_64/invert.rs"
VECTORS = gen.VECTORS
OUTPUT = ROOT / "lean/PastaAsm/X86_64/Transcription.lean"
OUTPUT_VECTORS = ROOT / "lean/PastaAsm/X86_64/Vectors.lean"
OUTPUT_INVERT_VECTORS = ROOT / "lean/PastaAsm/X86_64/InvertVectors.lean"
PASTA_HIGH_LIMB = 1 << 62

HEADER = """/-
Copyright Supranational LLC (the routines, transcribed from Semolina v0.1.4).
Copyright (c) 2026 the pasta-asm contributors (the transcription).
Released under the Apache License, Version 2.0, as described in the file LICENSE.
-/
import PastaAsm.Inversion
import PastaAsm.X86_64.Semantics

/-!
# The crate's inline x86-64 Pasta field blocks, transcribed

GENERATED by `lean/scripts/gen.py` from the six `asm!` blocks in
`src/x86_64.rs`; do not edit by hand. Each source instruction occurs in a trailing
comment on the let binding that models it. Registers are lexically rebound after
each write. The two identical full internal multiplication rounds are represented by
a generated helper after their flattened IRs have been compared modulo the source's
register rotation. `cf` and `ofl` model x86 CF and OF independently; the generator
rejects a read after an instruction that invalidates the corresponding flag.

Pointer operands are represented only by reads of their four input limbs. The
generator accepts no stores, no address other than a declared read-only pointer
plus 0, 8, 16, or 24 bytes, and no register read before an input or instruction has
written it. The fixed RDX operand, 32-bit `:e` XOR-zero idiom, operand outputs, and
Rust return-tuple order are parsed from the source rather than inferred here.
-/

namespace PastaAsm.X86_64

-- A mechanical transcription intentionally retains dead architectural results and source
-- operand names such as `zero`.
set_option linter.unusedVariables false
set_option linter.constructorNameAsVariable false

"""

FOOTER = "\nend PastaAsm.X86_64\n"


@dataclasses.dataclass(frozen=True)
class RoutineConfig:
    rust_name: str
    lean_name: str
    args: Tuple[Tuple[str, str], ...]
    result_type: str
    result_count: int
    doc: str


RESERVED_OPERAND_NAMES = {"rdx", "cf", "ofl", "s", "d", "m", "n"}


def validate_high_limb(source: str) -> None:
    matches = re.findall(
        r"^\s*const\s+PASTA_HIGH_LIMB\s*:\s*u64\s*=\s*([^;]+);",
        source,
        re.MULTILINE,
    )
    if len(matches) != 1:
        raise GenerationError("expected exactly one PASTA_HIGH_LIMB declaration")
    expression = re.sub(r"\s+", "", matches[0])
    if expression != "1<<62" or PASTA_HIGH_LIMB != 0x4000000000000000:
        raise GenerationError(
            "PASTA_HIGH_LIMB must be `1 << 62` (0x4000000000000000)"
        )


def parse_declaration(text: str) -> Declaration:
    return asm_source.parse_declaration(
        text,
        reserved_names=RESERVED_OPERAND_NAMES,
        fixed_registers={"rdx"},
        const_operands={"PASTA_HIGH_LIMB"},
    )


MUL_ROUND_RANGES = ((28, 63), (64, 99))
MUL_ROUND_ROTATIONS = (
    {"be": "r0", "ce": "r1", "de": "r2", "ee": "r3", "ae": "r4"},
    {"ce": "r0", "de": "r1", "ee": "r2", "ae": "r3", "be": "r4"},
)
MUL_ACC_FIELDS = ("r0", "r1", "r2", "r3", "r4", "q")


ROUTINES = (
    RoutineConfig(
        "add", "addMod",
        (("lhs", "Limbs"), ("rhs", "Limbs"), ("modulus", "Limbs")),
        "Limbs", 4,
        "The inline `asm!` block of `add`: modular addition followed by its conditional reduction.",
    ),
    RoutineConfig(
        "sub", "subMod",
        (("lhs", "Limbs"), ("rhs", "Limbs"), ("modulus", "Limbs")),
        "Limbs", 4,
        "The inline `asm!` block of `sub`: modular subtraction and conditional modulus addition.",
    ),
    RoutineConfig(
        "mul", "mulMont",
        (("lhs", "Limbs"), ("rhs", "Limbs"), ("modulus", "Limbs"), ("inv", "Nat")),
        "Limbs", 4,
        "The inline `asm!` block of `mul`: Montgomery multiplication and conditional reduction.",
    ),
    RoutineConfig(
        "square_lo", "squareLo", (("value", "Limbs"),), "WideLimbs", 8,
        "The inline `asm!` block of `square_lo`: the unreduced 512-bit square.",
    ),
    RoutineConfig(
        "square_hi", "squareHi",
        (("product", "WideLimbs"), ("modulus", "Limbs"), ("inv", "Nat")),
        "Limbs", 4,
        "The inline `asm!` block of `square_hi`: Montgomery reduction of `squareLo`'s product.",
    ),
    RoutineConfig(
        "from_mont", "fromMont",
        (("value", "Limbs"), ("modulus", "Limbs"), ("inv", "Nat")),
        "Limbs", 4,
        "The inline `asm!` block of `from_mont`: Montgomery reduction of a four-limb value.",
    ),
)


@dataclasses.dataclass(frozen=True)
class InvertRoutineConfig:
    rust_name: str
    lean_name: str
    signature: str
    rust_regions: Tuple[Tuple[str, str], ...]
    block_count: int = 1


INVERT_ROUTINES = (
    InvertRoutineConfig(
        "divsteps_31", "divsteps31",
        "fn divsteps_31(a: &Limbs, b: &Limbs) -> Matrix",
        (
            ("inputs", """
                let mut a0 = a[0]; let mut a1 = a[1]; let mut a2 = a[2]; let a3 = a[3];
                let mut b0 = b[0]; let b1 = b[1]; let b2 = b[2]; let b3 = b[3];
                unsafe {
            """),
            ("result", """
                ; }
                Matrix { f0: a0 as i64, g0: a1 as i64, f1: b0 as i64, g1: a2 as i64, }
            """),
        ),
    ),
    InvertRoutineConfig(
        "update_ab", "updateAb",
        "fn update_ab(a: &Limbs, b: &Limbs, f: i64, g: i64) -> (Limbs, i64, i64)",
        (
            ("inputs", """
                let aa = [a[0], a[1], a[2], a[3], 0];
                let bb = [b[0], b[1], b[2], b[3], 0];
                let [mut r0, mut r1, mut r2, mut r3, r4] = lincomb(&aa, &bb, f, g);
                let mask: u64; let bit: u64;
                unsafe {
            """),
            ("result", """
                ; }
                let corrected_f = ((f as u64) ^ mask).wrapping_add(bit) as i64;
                let corrected_g = ((g as u64) ^ mask).wrapping_add(bit) as i64;
                ([r0, r1, r2, r3], corrected_f, corrected_g)
            """),
        ),
    ),
    InvertRoutineConfig(
        "add_words", "addWordsLimb",
        "fn add_words<const N: usize>(mut lhs: [u64; N], rhs: &[u64; N]) -> [u64; N]",
        (
            ("loop", """
                let mut carry = 0u64;
                for i in 0..N { unsafe {
            """),
            ("result", "; } } lhs"),
        ),
    ),
    InvertRoutineConfig(
        "mul_signed", "mulSignedLimb",
        "fn mul_signed<const N: usize>(value: &[u64; N], scalar: i64) -> [u64; N]",
        (
            ("loop", """
                let scalar = scalar as u64;
                let sign = (scalar as i64 >> 63) as u64;
                let sign_bit = sign & 1;
                let magnitude = (scalar ^ sign).wrapping_add(sign_bit);
                let mut out = [0; N];
                let mut negate_carry = sign_bit;
                let mut product_carry = 0u64;
                for i in 0..N {
                    let limb = value[i];
                    let next_negate_carry: u8; let low: u64; let high: u64;
                    unsafe {
            """),
            ("result", """
                ; }
                out[i] = low;
                negate_carry = u64::from(next_negate_carry);
                product_carry = high;
                }
                out
            """),
        ),
    ),
    InvertRoutineConfig(
        "divsteps_47", "divsteps47",
        "fn divsteps_47(a: u64, b: u64) -> Matrix",
        (
            ("inputs", """
                let mut f0 = 1u64; let mut g0 = 0u64;
                let mut f1 = 0u64; let mut g1 = 1u64;
                unsafe {
            """),
            ("result", """
                ; }
                Matrix { f0: f0 as i64, g0: g0 as i64, f1: f1 as i64, g1: g1 as i64, }
            """),
        ),
    ),
    InvertRoutineConfig(
        "normalize", "normalize",
        "fn normalize(mut value: [u64; 9], modulus: &Limbs) -> [u64; 8]",
        (
            ("first-inputs", """
                let modx = [
                    modulus[0] << 1,
                    (modulus[1] << 1) | (modulus[0] >> 63),
                    (modulus[2] << 1) | (modulus[1] >> 63),
                    (modulus[3] << 1) | (modulus[2] >> 63),
                ];
                let [mut h0, mut h1, mut h2, mut h3] = [value[4], value[5], value[6], value[7]];
                let mut excess = value[8];
                let [m0, m1, m2, m3] = modx;
                unsafe {
            """),
            ("second-inputs", """
                ; }
                let [m0, m1, m2, m3] = modx;
                unsafe {
            """),
            ("result", """
                ; }
                value[4] = h0; value[5] = h1; value[6] = h2; value[7] = h3;
                [value[0], value[1], value[2], value[3], value[4], value[5], value[6], value[7],]
            """),
        ),
        block_count=2,
    ),
    InvertRoutineConfig(
        "reduce_once", "reduceOnce",
        "fn reduce_once(mut value: Limbs, modulus: &Limbs) -> Limbs",
        (
            ("inputs", """
                let p0 = modulus[0]; let p1 = modulus[1]; let p3 = modulus[3];
                unsafe {
            """),
            ("result", "; } value"),
        ),
    ),
)



EXPECTED_INVERT_DECLARATIONS = {
    ("divsteps_31", 0): (
        Declaration("a0", "inout", "a0", "a0"),
        Declaration("a1", "inout", "a1", "a1"),
        Declaration("a2", "inout", "a2", "a2"),
        Declaration("a3", "inout", "a3", "_"),
        Declaration("b0", "inout", "b0", "b0"),
        Declaration("b1", "inout", "b1", "_"),
        Declaration("b2", "inout", "b2", "_"),
        Declaration("b3", "inout", "b3", "_"),
        Declaration("t", "out", "_", "_"),
        Declaration("rcx", "out", "_", None, fixed=True, constraint="rcx"),
    ),
    ("update_ab", 0): (
        *(Declaration(f"r{i}", "inout", f"r{i}", f"r{i}") for i in range(4)),
        Declaration("r4", "in", "r4", None),
        Declaration("mask", "lateout", "mask", "mask"),
        Declaration("bit", "lateout", "bit", "bit"),
    ),
    ("add_words", 0): (
        Declaration("lhs", "inout", "lhs[i]", "lhs[i]"),
        Declaration("rhs", "in", "rhs[i]", None),
        Declaration("carry", "inout", "carry", "carry"),
    ),
    ("mul_signed", 0): (
        Declaration("limb", "inout", "limb", "_"),
        Declaration("sign", "in", "sign", None),
        Declaration("negate_carry", "in", "negate_carry", None),
        Declaration("next_negate_carry", "out", "next_negate_carry", "next_negate_carry",
                    constraint="reg_byte"),
        Declaration("magnitude", "in", "magnitude", None),
        Declaration("product_carry", "in", "product_carry", None),
        Declaration("rax", "out", "low", "low", fixed=True, constraint="rax"),
        Declaration("rdx", "out", "high", "high", fixed=True, constraint="rdx"),
    ),
    ("divsteps_47", 0): (
        Declaration("a", "inout", "a", "_"),
        Declaration("b", "inout", "b", "_"),
        Declaration("f0", "inout", "f0", "f0"),
        Declaration("g0", "inout", "g0", "g0"),
        Declaration("f1", "inout", "f1", "f1"),
        Declaration("g1", "inout", "g1", "g1"),
        Declaration("t0", "out", "_", "_"),
        Declaration("t1", "out", "_", "_"),
        Declaration("t2", "out", "_", "_"),
        Declaration("count", "out", "_", "_"),
    ),
    ("normalize", 0): (
        *(Declaration(f"h{i}", "inout", f"h{i}", f"h{i}") for i in range(4)),
        Declaration("excess", "inout", "excess", "excess"),
        *(Declaration(f"m{i}", "inout", f"m{i}", "_") for i in range(4)),
        Declaration("mask", "out", "_", "_"),
    ),
    ("normalize", 1): (
        *(Declaration(f"h{i}", "inout", f"h{i}", f"h{i}") for i in range(4)),
        *(Declaration(f"m{i}", "inout", f"m{i}", "_") for i in range(4)),
        Declaration("excess", "in", "excess", None),
        Declaration("nonzero_mask", "out", "_", "_"),
        Declaration("negative_excess", "out", "_", "_"),
        Declaration("zero", "out", "_", "_"),
    ),
    ("reduce_once", 0): (
        *(Declaration(f"r{i}", "inout", f"value[{i}]", f"value[{i}]") for i in range(4)),
        Declaration("p0", "inout", "p0", "_"),
        Declaration("p1", "inout", "p1", "_"),
        Declaration("p3", "inout", "p3", "_"),
        Declaration("zero", "out", "_", "_"),
    ),
}


def parse_invert_helper(source: str, config: InvertRoutineConfig):
    parsed = asm_source.parse_helper_function(
        source, config.rust_name, config.signature, config.rust_regions,
        reserved_names=RESERVED_OPERAND_NAMES,
        fixed_registers={"rax", "rcx", "rdx"},
        allowed_options={"pure", "nomem", "nostack"},
        required_options={"pure", "nomem", "nostack"},
        allowed_kinds={"in", "out", "inout", "lateout"},
        allowed_constraints={"reg", "reg_byte"},
        named_fixed_outputs={"rax", "rdx"},
        inout_expression_outputs={
            "lhs[i]", "value[0]", "value[1]", "value[2]", "value[3]",
        },
    )
    if len(parsed.blocks) != config.block_count:
        raise GenerationError(
            f"{config.rust_name}: expected {config.block_count} asm blocks, "
            f"found {len(parsed.blocks)}"
        )
    for index, block in enumerate(parsed.blocks):
        key = (config.rust_name, index)
        if key not in EXPECTED_INVERT_DECLARATIONS:
            raise GenerationError(f"{config.rust_name}: missing declaration schema for block {index}")
        asm_source.validate_declarations(
            block.declarations,
            EXPECTED_INVERT_DECLARATIONS[key],
            f"{config.rust_name} block {index}",
        )
    return parsed


def parse_function(source: str, config: RoutineConfig) -> ParsedFunction:
    return asm_source.parse_function(
        source,
        config.rust_name,
        [name for name, _ in config.args],
        config.result_count,
        reserved_names=RESERVED_OPERAND_NAMES,
        fixed_registers={"rdx"},
        const_operands={"PASTA_HIGH_LIMB"},
    )


@dataclasses.dataclass(frozen=True)
class RegisterToken:
    name: str
    modifier: Optional[str] = None


class Emitter(gen.Emitter):
    """Validate x86-64 instructions and record them in the shared binding IR."""

    def __init__(self, directions: Dict[str, str], pointers: Dict[str, str], *, inversion=False):
        super().__init__()
        self.directions = dict(directions)
        self.pointers = dict(pointers)
        self.inversion = inversion
        self.cf_valid = False
        self.of_valid = False
        self.zf_valid = False
        self.used_memory = False

    @staticmethod
    def _fact_for_input(register: str, expression: str):
        field = re.fullmatch(r"([A-Za-z_]\w*)\.(l[0-8])", expression)
        if field:
            return ("load", field.group(1), field.group(2))
        if expression == "inv":
            return ("inv",)
        return ("mov", expression)

    @staticmethod
    def _reads(*operands: str) -> Set[str]:
        reads = set()
        for operand in operands:
            if re.fullmatch(r"[A-Za-z_]\w*", operand) and not operand.isdigit():
                reads.add(operand)
            elif found := re.fullmatch(r"\(word32 ([A-Za-z_]\w*)\)", operand):
                reads.add(found.group(1))
        return reads

    def bind_argument(
        self, register: str, expression: str, description: str, *, bound: Optional[str] = None,
    ) -> None:
        self._check_declared(register)
        if register in self.known or register in self.pointers:
            raise GenerationError(f"duplicate initial binding for {register}")
        fact = (("x86_input", expression, bound) if self.inversion and bound is not None
                else self._fact_for_input(register, expression))
        self.bind(
            register, expression, description, reads=(), load="." in expression, fact=fact,
        )

    def bind_pointer(self, register: str, argument: str) -> None:
        self._check_declared(register)
        if register in self.known or register in self.pointers:
            raise GenerationError(f"duplicate initial binding for {register}")
        self.pointers[register] = argument

    def _check_declared(self, register: str) -> None:
        if register not in self.directions:
            raise GenerationError(f"undeclared register {register}")

    def _check_readable(self, register: str) -> None:
        self._check_declared(register)
        if self.directions[register] not in ("in", "inout"):
            raise GenerationError(f"output-only register {register} read before being written")

    def _check_writable(self, register: str) -> None:
        self._check_declared(register)
        if self.directions[register] not in ("out", "lateout", "inout"):
            raise GenerationError(f"input-only register {register} cannot be written")

    @staticmethod
    def parse_register(token: str) -> RegisterToken:
        token = token.strip()
        if token.startswith("qword ptr") or token.startswith("["):
            raise GenerationError(f"memory write is unsupported: {token}")
        if token in ("rax", "rcx", "rdx"):
            return RegisterToken(token)
        if token == "ecx":
            return RegisterToken("rcx", "e")
        match = re.fullmatch(r"\{([A-Za-z_]\w*)(?::([A-Za-z_]\w*))?\}", token)
        if not match:
            raise GenerationError(f"unsupported register operand {token}")
        return RegisterToken(match.group(1), match.group(2))

    def read_register(self, token: str, allow_modifier: bool = False) -> str:
        parsed = self.parse_register(token)
        self._check_declared(parsed.name)
        if parsed.modifier and not allow_modifier:
            raise GenerationError(f"unsupported register modifier :{parsed.modifier} in {token}")
        if parsed.modifier not in (None, "e"):
            raise GenerationError(f"unsupported register modifier :{parsed.modifier} in {token}")
        if parsed.name in self.pointers:
            raise GenerationError(f"pointer register {parsed.name} used outside an address")
        if parsed.name not in self.known:
            self._check_readable(parsed.name)
            raise GenerationError(f"register {parsed.name} read before being written")
        return f"(word32 {parsed.name})" if parsed.modifier == "e" else parsed.name

    def write_register(self, token: str, allow_modifier: bool = False) -> RegisterToken:
        parsed = self.parse_register(token)
        self._check_writable(parsed.name)
        if parsed.modifier and not allow_modifier:
            raise GenerationError(f"unsupported register modifier :{parsed.modifier} in {token}")
        if parsed.name in self.pointers:
            raise GenerationError(f"cannot overwrite pointer operand {parsed.name}")
        self.known.add(parsed.name)
        return parsed

    def read_value(self, token: str) -> str:
        token = token.strip()
        if re.fullmatch(r"(?:0|[1-9][0-9]*|0x[0-9A-Fa-f]+)", token):
            return str(int(token, 0))
        memory = re.fullmatch(
            r"qword\s+ptr\s*\[\s*\{([A-Za-z_]\w*)\}\s*(?:\+\s*([0-9]+))?\s*\]",
            token,
        )
        if memory:
            base, displacement_text = memory.groups()
            self._check_declared(base)
            if base not in self.pointers:
                raise GenerationError(f"address base {base} is not a read-only pointer operand")
            displacement = int(displacement_text or "0")
            if displacement not in (0, 8, 16, 24):
                raise GenerationError(f"unsupported memory offset {displacement}")
            self.used_memory = True
            return f"{self.pointers[base]}.l{displacement // 8}"
        return self.read_register(token, allow_modifier=self.inversion)

    @staticmethod
    def split_instruction(text: str) -> Tuple[str, List[str]]:
        found = re.fullmatch(r"\s*([A-Za-z][A-Za-z0-9]*)\s*(.*?)\s*", text)
        if not found:
            raise GenerationError(f"cannot parse instruction {text!r}")
        op, rest = found.groups()
        operands = [part.strip() for part in rest.split(",")] if rest else []
        if any(not operand for operand in operands):
            raise GenerationError(f"empty operand in instruction {text!r}")
        return op.lower(), operands

    @staticmethod
    def require_count(op: str, operands: Sequence[str], count: int) -> None:
        if len(operands) != count:
            raise GenerationError(f"{op} expects {count} operands, got {len(operands)}")

    @staticmethod
    def immediate(token: str) -> int:
        if not re.fullmatch(r"(?:0|[1-9][0-9]*)", token.strip()):
            raise GenerationError(f"unsupported immediate {token}")
        return int(token)

    def require_cf(self, text: str) -> None:
        if not self.cf_valid:
            raise GenerationError(f"CF read while invalid: {text}")

    def require_of(self, text: str) -> None:
        if not self.of_valid:
            raise GenerationError(f"OF read while invalid: {text}")

    def require_zf(self, text: str) -> None:
        if not self.zf_valid:
            raise GenerationError(f"ZF read while invalid: {text}")

    def invalidate_arithmetic_flags(self) -> None:
        self.cf_valid = False
        self.of_valid = False
        self.zf_valid = False

    def emit(self, name: str, expr: str, comment: Optional[str] = None,
             *, reads=(), fact=None, note=None) -> None:
        self.bind(name, expr, comment, reads=reads, fact=fact, note=note)

    def emit_pair_result(
        self, dst: str, semantic: str, operands: Sequence[str], text: str, fact,
    ) -> None:
        """Bind an existing value/CF pair; unused OF and ZF remain fail-closed."""
        reads = self._reads(*operands)
        self.emit("s", f"{semantic} {' '.join(operands)}", text, reads=reads, fact=fact)
        self.emit(dst, "s.1", reads=("s",), fact=("fst",), note=f"  `-> {dst}")
        self.emit("cf", "s.2", reads=("s",), fact=("snd",), note="  `-> cf")
        self.cf_valid = True
        self.of_valid = self.zf_valid = False

    def emit_logic(self, op: str, operands: Sequence[str], text: str) -> None:
        self.require_count(op, operands, 2)
        left_token = self.parse_register(operands[0])
        right_token = self.parse_register(operands[1]) if op == "xor" else None
        xor_self = right_token is not None and left_token == right_token
        if xor_self:
            self._check_declared(left_token.name)
            old = src = "0"
        else:
            old = self.read_register(operands[0], allow_modifier=True)
            src = self.read_value(operands[1])
        parsed = self.write_register(operands[0], allow_modifier=True)
        if parsed.modifier not in (None, "e"):
            raise GenerationError(f"unsupported {op} register modifier :{parsed.modifier}")
        semantic = {"and": "bitAnd", "or": "bitOr", "xor": "bitXor"}[op]
        if parsed.modifier == "e":
            if op != "xor":
                raise GenerationError(f"32-bit {op} is unsupported")
            semantic += "32"
        self.emit(
            parsed.name, f"{semantic} {old} {src}", text,
            reads=self._reads(old, src), fact=("x86_logic", semantic, old, src),
        )
        self.emit("cf", "0", reads=(), fact=("zero_cf",), note="  `-> cf")
        self.emit("ofl", "0", reads=(), fact=("zero_of",), note="  `-> ofl")
        self.emit(
            "zf", f"zeroFlag {parsed.name}", reads=(parsed.name,),
            fact=("zero_flag", parsed.name), note="  `-> zf",
        )
        self.cf_valid = self.of_valid = self.zf_valid = True

    def emit_cmov(self, op: str, operands: Sequence[str], text: str) -> None:
        self.require_count(op, operands, 2)
        if op in ("cmovz", "cmovnz"):
            self.require_zf(text)
            flag = "zf"
        else:
            self.require_cf(text)
            flag = "cf"
        old = self.read_register(operands[0])
        src = self.read_value(operands[1])
        dst = self.write_register(operands[0]).name
        semantic = "cmovc" if op in ("cmovb", "cmovc") else op
        zero_branch, nonzero_branch = (
            (old, src) if op in ("cmovz", "cmovb", "cmovc") else (src, old)
        )
        self.emit(
            dst, f"{semantic} {flag} {old} {src}", text,
            reads=self._reads(flag, old, src),
            fact=("select", flag, zero_branch, nonzero_branch),
        )

    def render(self, result_names):
        """Retain every architectural result in the mechanical x86 transcription."""
        return [(f"  let {e['name']} := {e['expr']}", e.get("note") or e["comment"]) for e in self.entries]

    def render_ssa(self, result_names):
        """Render unique Lean binders while preserving the architectural instruction IR.

        This is used by factored helpers: after ``lift_lets`` inlines an instruction's pair
        wrapper, unique projection binders ensure that both projections still reference the same
        pre-instruction operands instead of one projection seeing the other's shadowing write.
        """
        names = gen.ssa_names(self.entries)
        current = {}
        lines = []
        pending_instruction_comment = None
        pending_first_projection = None
        for entry, name in zip(self.entries, names):
            expression = entry["expr"]
            for read in sorted(entry["reads"], key=len, reverse=True):
                if read in current:
                    expression = re.sub(
                        rf"(?<![A-Za-z0-9_']){re.escape(read)}(?![A-Za-z0-9_'])",
                        current[read],
                        expression,
                    )
            if entry.get("helper_wrapper"):
                # The architectural IR keeps this pair so its two projections are mechanically
                # tied to one instruction. Render the projections directly: ``lift_lets`` would
                # inline a projection-only wrapper anyway, and the SSA operands above make both
                # direct expressions refer to the same pre-instruction values.
                current[entry["name"]] = f"({expression})"
                pending_instruction_comment = entry["comment"]
                continue
            line = f"  let {name} := {expression}"
            if pending_instruction_comment is not None:
                if pending_first_projection is None:
                    # Emit the second projection first. Its expression is thereby elaborated before
                    # the value-result binder can shadow an in-place instruction operand.
                    pending_first_projection = (line, entry.get("note") or entry["comment"])
                    current[entry["name"]] = name
                    continue
                lines.append((line, pending_instruction_comment))
                lines.append(pending_first_projection)
                pending_instruction_comment = None
                pending_first_projection = None
            else:
                lines.append((line, entry.get("note") or entry["comment"]))
            current[entry["name"]] = name
        if pending_instruction_comment is not None or pending_first_projection is not None:
            raise GenerationError("incomplete helper instruction projection pair")
        return lines, [current[name] for name in result_names]

    def binary_add(self, op: str, operands: Sequence[str], text: str) -> None:
        self.require_count(op, operands, 2)
        dst_old = self.read_register(operands[0])
        src = self.read_value(operands[1])
        carry = "0"
        if op in ("adc", "adcx"):
            self.require_cf(text)
            carry = "cf"
        elif op == "adox":
            self.require_of(text)
            carry = "ofl"
        dst = self.write_register(operands[0]).name
        if self.inversion:
            if op in ("adcx", "adox"):
                raise GenerationError(f"{op} is unsupported in inversion helpers")
            self.emit_pair_result(
                dst, "addc", (dst_old, src, carry), text,
                ("x86_adds", dst_old, src, carry),
            )
            return
        flag = "ofl" if op == "adox" else "cf"
        self.emit("s", f"addc {dst_old} {src} {carry}", text,
                  reads=self._reads(dst_old, src, carry), fact=("x86_adds", dst_old, src, carry))
        self.emit(dst, "s.1", reads=("s",), fact=("fst",), note=f"  `-> {dst}")
        self.emit(flag, "s.2", reads=("s",), fact=("snd",), note=f"  `-> {flag}")
        if op == "adox":
            self.of_valid = True
        else:
            self.cf_valid = True
            if op in ("add", "adc"):
                self.of_valid = False

    def binary_sub(self, op: str, operands: Sequence[str], text: str) -> None:
        self.require_count(op, operands, 2)
        dst_old = self.read_register(operands[0], allow_modifier=self.inversion)
        src = self.read_value(operands[1])
        borrow = "0"
        if op == "sbb":
            self.require_cf(text)
            borrow = "cf"
        parsed = self.write_register(operands[0], allow_modifier=self.inversion)
        if parsed.modifier not in (None, "e"):
            raise GenerationError(f"unsupported {op} register modifier :{parsed.modifier}")
        dst = parsed.name
        if self.inversion:
            if parsed.modifier == "e":
                raise GenerationError("32-bit subtraction is loop control and must be factored")
            self.emit_pair_result(
                dst, "sbb", (dst_old, src, borrow), text,
                ("x86_subs", dst_old, src, borrow),
            )
            return
        self.emit("d", f"sbb {dst_old} {src} {borrow}", text,
                  reads=self._reads(dst_old, src, borrow), fact=("x86_subs", dst_old, src, borrow))
        self.emit(dst, "d.1", reads=("d",), fact=("fst",), note=f"  `-> {dst}")
        self.emit("cf", "d.2", reads=("d",), fact=("snd",), note="  `-> cf")
        self.cf_valid = True
        self.of_valid = False

    def emit_instruction(self, text: str) -> None:
        op, operands = self.split_instruction(text)
        try:
            if op in ("mov", "movabs"):
                self.require_count(op, operands, 2)
                src = self.read_value(operands[1])
                parsed = self.write_register(operands[0], allow_modifier=self.inversion)
                if parsed.modifier not in (None, "e"):
                    raise GenerationError(f"unsupported mov register modifier :{parsed.modifier}")
                expression = f"word32 {src}" if parsed.modifier == "e" else src
                self.emit(
                    parsed.name, expression, text, reads=self._reads(src),
                    fact=("word32" if parsed.modifier == "e" else "mov", src),
                )
            elif op == "mulx":
                self.require_count(op, operands, 3)
                rdx = self.read_register("rdx")
                src = self.read_value(operands[2])
                high = self.write_register(operands[0]).name
                low = self.write_register(operands[1]).name
                if high == low:
                    raise GenerationError("mulx destinations must be distinct")
                self.emit("m", f"mulx {rdx} {src}", text,
                          reads=self._reads(rdx, src), fact=("x86_mulx", rdx, src))
                self.emit(high, "m.1", reads=("m",), fact=("fst",), note=f"  `-> {high}")
                self.emit(low, "m.2", reads=("m",), fact=("snd",), note=f"  `-> {low}")
            elif op == "imul":
                self.require_count(op, operands, 2)
                old = self.read_register(operands[0])
                src = self.read_value(operands[1])
                dst = self.write_register(operands[0]).name
                self.emit(dst, f"mulLo {old} {src}", text,
                          reads=self._reads(old, src), fact=("mul", old, src))
                self.cf_valid = False
                self.of_valid = False
            elif op in ("shl", "shr", "sar"):
                self.require_count(op, operands, 2)
                old = self.read_register(operands[0])
                amount = self.immediate(operands[1])
                if not 1 <= amount < 64:
                    raise GenerationError("only unmasked nonzero 64-bit shift counts are supported")
                dst = self.write_register(operands[0]).name
                if self.inversion:
                    semantic = {"shl": "lsl", "shr": "lsr", "sar": "sar"}[op]
                    fact = (semantic, old, amount) if op != "sar" else ("x86_sar", old, amount)
                    self.emit(dst, f"{semantic} {old} {amount}", text, reads=(old,), fact=fact)
                    self.invalidate_arithmetic_flags()
                else:
                    if op == "sar":
                        raise GenerationError("sar is supported only in inversion helpers")
                    operation = "lsl" if op == "shl" else "lsr"
                    self.emit(dst, f"{operation} {old} {amount}", text,
                              reads=(old,), fact=(operation, old, amount))
                    self.cf_valid = False
                    self.of_valid = False
            elif op in ("add", "adc", "adcx", "adox"):
                self.binary_add(op, operands, text)
            elif op in ("sub", "sbb"):
                self.binary_sub(op, operands, text)
            elif op == "bsr":
                if not self.inversion:
                    raise GenerationError("bsr is supported only in inversion helpers")
                self.require_count(op, operands, 2)
                src = self.read_value(operands[1])
                dst = self.write_register(operands[0]).name
                self.emit(
                    dst, f"(bsr {src}).getD 0", text,
                    reads=self._reads(src), fact=("x86_bsr", src),
                )
                self.emit(
                    "zf", f"zeroFlag {src}", reads=self._reads(src),
                    fact=("zero_flag", src), note="  `-> zf",
                )
                self.zf_valid = True
                self.cf_valid = self.of_valid = False
            elif op in ("shld", "shrd"):
                if not self.inversion:
                    raise GenerationError(f"{op} is supported only in inversion helpers")
                self.require_count(op, operands, 3)
                old = self.read_register(operands[0])
                src = self.read_register(operands[1])
                count_token = operands[2]
                if count_token == "cl":
                    count = self.read_register("rcx")
                else:
                    count = str(self.immediate(count_token))
                dst = self.write_register(operands[0]).name
                self.emit(
                    dst, f"{op} {old} {src} {count}", text,
                    reads=self._reads(old, src, count),
                    fact=("x86_double_shift", op, old, src, count),
                )
                self.invalidate_arithmetic_flags()
            elif op == "mul":
                if not self.inversion:
                    raise GenerationError("one-operand mul is supported only in inversion helpers")
                self.require_count(op, operands, 1)
                rax = self.read_register("rax")
                src = self.read_value(operands[0])
                self.write_register("rax")
                self.write_register("rdx")
                self.emit(
                    "rdx", f"umulh {rax} {src}", text,
                    reads=self._reads(rax, src), fact=("umulh", rax, src),
                )
                self.emit(
                    "rax", f"mulLo {rax} {src}", reads=self._reads(rax, src),
                    fact=("mul", rax, src), note="  `-> rax",
                )
                self.invalidate_arithmetic_flags()
            elif op == "neg":
                self.require_count(op, operands, 1)
                old = self.read_register(operands[0])
                dst = self.write_register(operands[0]).name
                if self.inversion:
                    self.emit_pair_result(dst, "neg", (old,), text, ("x86_neg", old))
                else:
                    self.emit("n", f"neg {old}", text, reads=(old,), fact=("x86_neg", old))
                    self.emit(dst, "n.1", reads=("n",), fact=("fst",), note=f"  `-> {dst}")
                    self.emit("cf", "n.2", reads=("n",), fact=("snd",), note="  `-> cf")
                    self.cf_valid = True
                    self.of_valid = False
            elif op in ("cmp", "test"):
                if not self.inversion:
                    raise GenerationError(f"{op} is supported only in inversion helpers")
                self.require_count(op, operands, 2)
                left = self.read_value(operands[0])
                right = self.read_value(operands[1])
                if op == "cmp":
                    self.emit(
                        "cf", f"(sbb {left} {right} 0).2", text,
                        reads=self._reads(left, right), fact=("x86_cmp", left, right),
                    )
                    self.cf_valid = True
                    self.of_valid = self.zf_valid = False
                else:
                    self.emit("test", f"bitAnd {left} {right}", text,
                              reads=self._reads(left, right), fact=("x86_logic", "bitAnd", left, right))
                    self.emit("cf", "0", reads=(), fact=("mov", "0"), note="  `-> cf")
                    self.emit("ofl", "0", reads=(), fact=("mov", "0"), note="  `-> ofl")
                    self.emit("zf", "zeroFlag test", reads=("test",),
                              fact=("zero_flag", "test"), note="  `-> zf")
                    self.cf_valid = self.of_valid = self.zf_valid = True
            elif op == "not":
                if not self.inversion:
                    raise GenerationError("not is supported only in inversion helpers")
                self.require_count(op, operands, 1)
                old = self.read_register(operands[0])
                dst = self.write_register(operands[0]).name
                self.emit(dst, f"bitNot {old}", text, reads=(old,), fact=("x86_not", old))
            elif op == "lea":
                if not self.inversion:
                    raise GenerationError("lea is supported only in inversion helpers")
                self.require_count(op, operands, 2)
                address = re.fullmatch(r"\[\s*([^+\]]+)\s*\+\s*([0-9]+)\s*\]", operands[1])
                if not address:
                    raise GenerationError(f"unsupported lea address {operands[1]}")
                src = self.read_register(address.group(1).strip())
                offset = int(address.group(2))
                dst = self.write_register(operands[0]).name
                self.emit(dst, f"lea {src} {offset}", text, reads=(src,), fact=("x86_lea", src, offset))
            elif op == "bt":
                if not self.inversion:
                    raise GenerationError("bt is supported only in inversion helpers")
                self.require_count(op, operands, 2)
                base = self.read_value(operands[0])
                index = self.read_value(operands[1])
                self.emit("cf", f"bt {base} {index}", text,
                          reads=self._reads(base, index), fact=("bit", base, index))
                self.cf_valid = True
                self.of_valid = self.zf_valid = False
            elif op == "setc":
                if not self.inversion:
                    raise GenerationError("setc is supported only in inversion helpers")
                self.require_count(op, operands, 1)
                self.require_cf(text)
                dst = self.write_register(operands[0]).name
                self.emit(dst, "setc cf", text, reads=("cf",), fact=("x86_setc", "cf"))
            elif op in ("cmovz", "cmovnz", "cmovb", "cmovc"):
                if not self.inversion:
                    raise GenerationError(f"{op} is supported only in inversion helpers")
                self.emit_cmov(op, operands, text)
            elif op == "cmovnc":
                if self.inversion:
                    self.emit_cmov(op, operands, text)
                else:
                    self.require_count(op, operands, 2)
                    self.require_cf(text)
                    old = self.read_register(operands[0])
                    src = self.read_value(operands[1])
                    dst = self.write_register(operands[0]).name
                    self.emit(dst, f"cmovnc cf {old} {src}", text,
                              reads=self._reads("cf", old, src), fact=("select", "cf", src, old))
            elif op in ("and", "or"):
                if not self.inversion:
                    raise GenerationError(f"unsupported instruction {op}: {text}")
                self.emit_logic(op, operands, text)
            elif op == "xor" and self.inversion:
                self.emit_logic(op, operands, text)
            elif op == "xor":
                self.require_count(op, operands, 2)
                left = self.parse_register(operands[0])
                right = self.parse_register(operands[1])
                self._check_declared(left.name)
                self._check_declared(right.name)
                if left.name != right.name or left.modifier != right.modifier:
                    raise GenerationError("only XOR-self zeroing is supported")
                self._check_writable(left.name)
                if left.modifier not in (None, "e"):
                    raise GenerationError(f"unsupported XOR register modifier :{left.modifier}")
                if left.name in self.pointers:
                    raise GenerationError(f"cannot XOR pointer operand {left.name}")
                self.known.add(left.name)
                self.emit(left.name, "0", text, reads=(), fact=("x86_xor",))
                self.emit("cf", "0", reads=(), fact=("zero_cf",), note="  `-> cf")
                self.emit("ofl", "0", reads=(), fact=("zero_of",), note="  `-> ofl")
                self.cf_valid = True
                self.of_valid = True
            else:
                raise GenerationError(f"unsupported instruction {op}: {text}")
        except GenerationError as error:
            if str(error).endswith(f": {text}"):
                raise
            raise GenerationError(f"{error}: {text}") from error


def input_expression(
    value: str,
    locals_map: Dict[str, Tuple[str, int]],
    argument_types: Dict[str, str],
) -> Tuple[str, str]:
    direct = re.fullmatch(r"([A-Za-z_]\w*)\[([0-9]+)\]", value)
    if direct:
        argument, index_text = direct.groups()
        index = int(index_text)
    elif value in locals_map:
        argument, index = locals_map[value]
    elif value in argument_types and argument_types[value] == "Nat":
        return value, "scalar input"
    else:
        raise GenerationError(f"unsupported input operand expression {value}")
    if argument not in argument_types:
        raise GenerationError(f"operand reads non-argument {argument}")
    kind = argument_types[argument]
    limit = 8 if kind == "WideLimbs" else 4 if kind == "Limbs" else 0
    if index < 0 or index >= limit:
        raise GenerationError(f"limb {index} is out of range for {argument} : {kind}")
    return f"{argument}.l{index}", f"input {value}"


class SkeletonBackend(gen.SkeletonBackend):
    """x86-64 equal-let grouping and ISA proof facts for the shared traversal."""

    @staticmethod
    def _prepare_architectural(emitter):
        """The historical x86 skeleton preparation used by every non-helper routine."""
        full_entries = emitter.entries
        full_names, keep, representatives, normalized_expressions = gen.normalize_equal_lets(
            full_entries
        )
        kept_indices = [index for index, retained in enumerate(keep) if retained]
        entries = [dict(full_entries[index]) for index in kept_indices]
        triple_facts = {
            "x86_adds", "x86_subs", "x86_mulx", "x86_neg", "x86_xor", "x86_logic",
        }
        groups = {}
        for index, full_entry in enumerate(full_entries):
            if full_entry["fact"][0] in triple_facts:
                groups[index] = [
                    (full_entries[j], full_names[j], keep[j])
                    for j in range(index, min(index + 3, len(full_entries)))
                ]
        history = []
        previous_full_index = -1
        for entry, index in zip(entries, kept_indices):
            entry["proof_name"] = full_names[index]
            history.append([
                (full_entries[full_index]["name"], full_names[representatives[full_index]])
                for full_index in range(previous_full_index + 1, index)
            ])
            previous_full_index = index
            for start, group in groups.items():
                if start <= index < start + len(group):
                    entry["group"] = group
                    entry["group_fact"] = group[0][0]["fact"]
                    if entry["group_fact"][0] in ("x86_adds", "x86_subs"):
                        entry["group_label"] = group[1][1]
                    break
        names = [entry["proof_name"] for entry in entries]
        zero_names = {
            full_names[index] for index in kept_indices
            if normalized_expressions[index] == "0"
        }
        return gen.SkeletonPreparation(
            entries, names, zero_names=zero_names, history=history,
        )

    def prepare(self, emitter, live_entries):
        if not getattr(emitter, "helper_proof_mode", False):
            prepared = self._prepare_architectural(emitter)
            prepared.clear_values = not getattr(emitter, "phase_clear_values", False)
            return prepared
        full_entries = emitter.entries
        full_names, keep, representatives, normalized_expressions = gen.normalize_equal_lets(
            full_entries
        )
        # The helper renderer emits pair projections directly while retaining wrappers in this
        # validated architectural IR. Omit those proof-only wrappers from extraction; the emitted
        # SSA projection expressions share the same pre-instruction operands.
        for index, entry in enumerate(full_entries):
            if entry.get("helper_wrapper"):
                keep[index] = False
        # x86 intentionally renders every instruction binding. `lift_lets` preserves that stream,
        # but shares definitionally equal values (for example all three results of `xor r, r` are
        # zero). Mirror that common-subexpression pass using canonical SSA definitions for reads.
        kept_indices = [index for index, retained in enumerate(keep) if retained]
        entries = [dict(full_entries[index]) for index in kept_indices]
        triple_facts = {
            "x86_adds", "x86_subs", "x86_mulx", "x86_neg", "x86_xor", "x86_logic",
        }
        groups = {}
        group_for_index = {}
        for index, full_entry in enumerate(full_entries):
            if full_entry["fact"][0] in triple_facts:
                # Every architectural instruction's result bindings share its source PC. Do not
                # group by raw adjacency: an immediately preceding definitionally-equal binding
                # may be removed by ``lift_lets`` CSE (as in ``mov rdx, b`` at a factored round's
                # entry), leaving the next instruction's first retained binding at that index.
                member_indices = [
                    j for j, entry in enumerate(full_entries) if entry["pc"] == full_entry["pc"]
                ]
                group = [(full_entries[j], full_names[j], keep[j]) for j in member_indices]
                groups[index] = group
                for member_index in member_indices:
                    group_for_index[member_index] = group
        history = []
        current_proof_names = {}
        previous_full_index = -1
        for entry, index in zip(entries, kept_indices):
            entry["proof_name"] = full_names[index]
            skipped_history = []
            for full_index in range(previous_full_index + 1, index):
                register = full_entries[full_index]["name"]
                proof_name = full_names[representatives[full_index]]
                skipped_history.append((register, proof_name))
                current_proof_names[register] = proof_name
            # A 32-bit source operand is represented in the fact IR as `(word32 r)`. The shared
            # traversal renames whole operands, so record the corresponding composite alias when
            # `r` was rebound by a helper callout before a following 32-bit instruction.
            if entry["fact"][0] == "word32":
                wrapped = re.fullmatch(r"\(word32 ([A-Za-z_]\w*)\)", entry["fact"][1])
                if wrapped and wrapped.group(1) in current_proof_names:
                    register = wrapped.group(1)
                    skipped_history.append((
                        entry["fact"][1], f"(word32 {current_proof_names[register]})",
                    ))
            history.append(skipped_history)
            current_proof_names[entry["name"]] = full_names[index]
            previous_full_index = index
            if group := group_for_index.get(index):
                entry["group"] = group
                entry["group_fact"] = group[0][0]["fact"]
                # Helper projection lets are emitted second-before-first to keep in-place operands
                # unshadowed. Facts retain wrapper/value/flag order; only extraction follows source.
                if group[0][0].get("helper_wrapper") and len(group) == 3:
                    entry["extract_group"] = [group[2][1], group[1][1]]
                if entry["group_fact"][0] in ("x86_adds", "x86_subs"):
                    entry["group_label"] = group[1][1]
        names = [entry["proof_name"] for entry in entries]
        zero_names = {
            full_names[index] for index in kept_indices
            if normalized_expressions[index] == "0"
        }
        # Historical helper skeletons retain transparent values. The four divsteps helpers opt in
        # narrowly to per-extraction opacity because their handwritten conclusions otherwise keep
        # the full dependent loop trace alive and exhaust elaboration memory.
        return gen.SkeletonPreparation(
            entries, names, zero_names=zero_names, history=history,
            clear_values=getattr(emitter, "divsteps_clear_values", False),
        )

    def fact(self, kind, ops, context):
        group = context.group_entries
        group_names, group_live = context.group_names, context.group_live
        if kind == "x86_input":
            expression, bound = ops
            context.eq(context.name, expression)
            context.lines.append(
                f"  have b_{context.name} : {context.name} < 2^64 := by "
                f"rw [e_{context.name}]; exact {bound}"
            )
            context.bnd[context.name] = f"b_{context.name}"
            return True
        if kind == "word32":
            (operand,) = ops
            context.eq(context.name, f"word32 {operand}")
            context.lines.append(
                f"  have b_{context.name} : {context.name} < 2^64 := by rw [e_{context.name}]; "
                "exact Nat.lt_trans (word32_lt _) (by decide)"
            )
            context.bnd[context.name] = f"b_{context.name}"
            return True
        if kind == "zero_flag":
            (operand,) = ops
            context.eq(context.name, f"zeroFlag {operand}")
            context.lines.append(
                f"  have b_{context.name} : {context.name} ≤ 1 := by rw [e_{context.name}]; "
                "exact zeroFlag_le_one _"
            )
            context.bnd[context.name] = f"b_{context.name}"
            context.unit_bound.add(context.name)
            return True
        if kind == "x86_logic":
            semantic, a, b = ops
            value_name = group_names[0]
            if group_live[0]:
                context.eq(value_name, f"{semantic} {a} {b}")
                bound_lemma = {
                    "bitAnd": "bitAnd_lt", "bitOr": "bitOr_lt",
                    "bitXor": "bitXor_lt", "bitXor32": "bitXor32_lt",
                }[semantic]
                context.lines.append(
                    f"  have b_{value_name} : {value_name} < 2^64 := by rw [e_{value_name}]; "
                    f"exact {bound_lemma} _ _"
                )
                context.bnd[value_name] = f"b_{value_name}"
                context.ren[group[0][0]["name"]] = value_name
            for index in range(1, min(3, len(group_names))):
                if group_live[index]:
                    flag_name = group_names[index]
                    context.eq(flag_name, "0")
                    context.lines.append(
                        f"  have b_{flag_name} : {flag_name} ≤ 1 := by rw [e_{flag_name}]; decide"
                    )
                    context.bnd[flag_name] = f"b_{flag_name}"
                    context.unit_bound.add(flag_name)
                    context.ren[group[index][0]["name"]] = flag_name
            if len(group_names) > 3 and group_live[3]:
                zf_name = group_names[3]
                context.eq(zf_name, f"zeroFlag {value_name}")
                context.lines.append(
                    f"  have b_{zf_name} : {zf_name} ≤ 1 := by rw [e_{zf_name}]; "
                    "exact zeroFlag_le_one _"
                )
                context.bnd[zf_name] = f"b_{zf_name}"
                context.unit_bound.add(zf_name)
                context.ren[group[3][0]["name"]] = zf_name
            context.consumed = sum(group_live)
            return True
        if kind == "x86_cmp":
            a, b = ops
            context.eq(context.name, f"(sbb {a} {b} 0).2")
            context.lines.append(
                f"  have b_{context.name} : {context.name} ≤ 1 := by rw [e_{context.name}]; "
                f"exact sbb_borrow_le_one {a} {b} 0"
            )
            context.bnd[context.name] = f"b_{context.name}"
            context.unit_bound.add(context.name)
            return True
        if kind == "x86_sar":
            operand, count = ops
            context.eq(context.name, f"sar {operand} {count}")
            context.lines.append(
                f"  have b_{context.name} : {context.name} < 2^64 := by rw [e_{context.name}]; "
                "exact sar_lt _ _"
            )
            context.bnd[context.name] = f"b_{context.name}"
            return True
        if kind == "x86_double_shift":
            semantic, dst, src, count = ops
            context.eq(context.name, f"{semantic} {dst} {src} {count}")
            context.lines.append(
                f"  have b_{context.name} : {context.name} < 2^64 := by rw [e_{context.name}]; "
                f"exact {semantic}_lt _ _ _"
            )
            context.bnd[context.name] = f"b_{context.name}"
            return True
        if kind == "x86_bsr":
            (operand,) = ops
            context.eq(context.name, f"(bsr {operand}).getD 0")
            context.lines.append(
                f"  have b_{context.name} : {context.name} < 2^64 := by rw [e_{context.name}]; "
                "exact bsr_getD_lt _"
            )
            context.bnd[context.name] = f"b_{context.name}"
            return True
        if kind == "x86_not":
            (operand,) = ops
            context.eq(context.name, f"bitNot {operand}")
            context.lines.append(
                f"  have b_{context.name} : {context.name} < 2^64 := by rw [e_{context.name}]; "
                "exact bitNot_lt _"
            )
            context.bnd[context.name] = f"b_{context.name}"
            return True
        if kind == "x86_lea":
            operand, offset = ops
            context.eq(context.name, f"lea {operand} {offset}")
            context.lines.append(
                f"  have b_{context.name} : {context.name} < 2^64 := by rw [e_{context.name}]; "
                "exact word_lt _"
            )
            context.bnd[context.name] = f"b_{context.name}"
            return True
        if kind == "bit":
            base, index = ops
            context.eq(context.name, f"bt {base} {index}")
            context.lines.append(
                f"  have b_{context.name} : {context.name} ≤ 1 := by rw [e_{context.name}]; "
                "exact bt_le_one _ _"
            )
            context.bnd[context.name] = f"b_{context.name}"
            context.unit_bound.add(context.name)
            return True
        if kind == "x86_setc":
            (flag,) = ops
            context.eq(context.name, f"setc {flag}")
            context.lines.append(
                f"  have b_{context.name} : {context.name} ≤ 1 := by rw [e_{context.name}]; "
                "exact setc_le_one _"
            )
            context.bnd[context.name] = f"b_{context.name}"
            context.unit_bound.add(context.name)
            return True
        if kind == "x86_mulx":
            a, b = ops
            high, low = group_names[1:3]
            if group_live[1]:
                context.eq(high, f"(mulx {a} {b}).1")
                context.lines.append(
                    f"  have b_{high} : {high} < 2^64 := by rw [e_{high}]; "
                    "exact Nat.div_lt_of_lt_mul (Nat.mul_lt_mul'' "
                    f"{context.lt64(a)} {context.lt64(b)})"
                )
                context.bnd[high] = f"b_{high}"
                context.ren[group[1][0]["name"]] = high
            if group_live[2]:
                context.eq(low, f"(mulx {a} {b}).2")
                context.lines.append(
                    f"  have b_{low} : {low} < 2^64 := by rw [e_{low}]; "
                    "exact Nat.mod_lt _ (Nat.two_pow_pos _)"
                )
                context.bnd[low] = f"b_{low}"
                context.ren[group[2][0]["name"]] = low
            if group_live[1] and group_live[2]:
                context.lines.append(f"  have d_{high} : {low} + 2^64 * {high} = {a} * {b} := by")
                context.lines.append(f"    rw [e_{low}, e_{high}]; exact Nat.mod_add_div _ _")
            context.consumed = sum(group_live)
            return True
        if kind in ("x86_adds", "x86_subs"):
            a, b, carry = ops
            value_name, flag_name = group_names[1:3]
            semantic = "addc" if kind == "x86_adds" else "sbb"
            context.eq(value_name, f"({semantic} {a} {b} {carry}).1")
            if group_live[2]:
                context.eq(flag_name, f"({semantic} {a} {b} {carry}).2")
            if kind == "x86_adds":
                linear = f"{value_name} + 2^64 * {flag_name} = {a} + {b} + {carry}"
                linear_proof = f"addc_lin {a} {b} {carry}"
                value_proof = f"addc_value_lt {a} {b} {carry}"
                flag_proof = (
                    f"addc_carry_le_one {a} {b} {carry} {context.lt64(a)} {context.lt64(b)} {context.le1(carry)}"
                )
            else:
                linear = f"{value_name} + {b} + {carry} = {a} + 2^64 * {flag_name}"
                linear_proof = f"sbb_lin {a} {b} {carry} {context.lt64(a)} {context.lt64(b)} {context.le1(carry)}"
                value_proof = f"sbb_value_lt {a} {b} {carry}"
                flag_proof = f"sbb_borrow_le_one {a} {b} {carry}"
            if group_live[2]:
                context.lines.append(f"  have l_{value_name} : {linear} := by")
                context.lines.append(f"    rw [e_{value_name}, e_{flag_name}]; exact {linear_proof}")
                context.lines.append(
                    f"  have b_{value_name} : {value_name} < 2^64 := by rw [e_{value_name}]; "
                    f"exact {value_proof}"
                )
                context.lines.append(
                    f"  have b_{flag_name} : {flag_name} ≤ 1 := by rw [e_{flag_name}]; "
                    f"exact {flag_proof}"
                )
                context.lines.append(f"  clear e_{value_name} e_{flag_name}")
                context.ren[group[2][0]["name"]] = flag_name
            else:
                context.lines.append(
                    f"  have b_{value_name} : {value_name} < 2^64 := by rw [e_{value_name}]; "
                    f"exact {value_proof}"
                )
                context.lines.append(f"  obtain ⟨{flag_name}, b_{flag_name}, l_{value_name}⟩ :")
                context.lines.append(f"      ∃ flag, flag ≤ 1 ∧ {linear.replace(flag_name, 'flag')} :=")
                context.lines.append(f"    ⟨({semantic} {a} {b} {carry}).2, {flag_proof}, by")
                context.lines.append(f"      rw [e_{value_name}]; exact {linear_proof}⟩")
                context.lines.append(f"  clear e_{value_name}")
            context.ren[group[1][0]["name"]] = value_name
            context.bnd[value_name], context.bnd[flag_name] = f"b_{value_name}", f"b_{flag_name}"
            context.unit_bound.add(flag_name)
            context.consumed = sum(group_live)
            return True
        if kind == "x86_neg":
            (operand,) = ops
            value_name, flag_name = group_names[1:3]
            if group_live[1]:
                context.eq(value_name, f"(neg {operand}).1")
                context.lines.append(
                    f"  have b_{value_name} : {value_name} < 2^64 := by rw [e_{value_name}]; "
                    f"exact sbb_value_lt 0 {operand} 0"
                )
                context.ren[group[1][0]["name"]] = value_name
                context.bnd[value_name] = f"b_{value_name}"
            if group_live[2]:
                context.eq(flag_name, f"(neg {operand}).2")
                context.lines.append(f"  have b_{flag_name} : {flag_name} ≤ 1 := by")
                context.lines.append(f"    rw [e_{flag_name}]; simp only [neg]; split <;> omega")
                context.ren[group[2][0]["name"]] = flag_name
                context.bnd[flag_name] = f"b_{flag_name}"
                context.unit_bound.add(flag_name)
            context.consumed = sum(group_live)
            return True
        if kind == "x86_xor":
            data_name, cf_name, of_name = group_names
            if group_live[0]:
                context.eq(data_name, "0")
                context.lines.append(
                    f"  have b_{data_name} : {data_name} < 2^64 := by rw [e_{data_name}]; decide"
                )
                context.bnd[data_name] = f"b_{data_name}"
            if group_live[1]:
                context.eq(cf_name, "0")
                context.lines.append(f"  have b_{cf_name} : {cf_name} ≤ 1 := by rw [e_{cf_name}]; decide")
                if group[1][0]["name"] not in context.ren:
                    context.ren[group[1][0]["name"]] = cf_name
                context.bnd[cf_name] = f"b_{cf_name}"
                context.unit_bound.add(cf_name)
            if group_live[2]:
                context.eq(of_name, "0")
                context.lines.append(f"  have b_{of_name} : {of_name} ≤ 1 := by rw [e_{of_name}]; decide")
                if group[2][0]["name"] not in context.ren:
                    context.ren[group[2][0]["name"]] = of_name
                context.bnd[of_name] = f"b_{of_name}"
                context.unit_bound.add(of_name)
            context.consumed = sum(group_live)
            return True
        return False


SKELETON_BACKEND = SkeletonBackend()


class Routine(gen.Routine):
    """An x86 routine, whose source docstrings and internal lets are already line-sized."""

    architecture = "X86_64"
    skeleton_backend = SKELETON_BACKEND

    def text(self, column):
        body = []
        for code, comment in self.lines:
            if comment is None:
                body.append(code)
            else:
                body.append(
                    f"{code.ljust(column) if len(code) + 2 <= column else code + '  '}-- {comment}"
                )
        head = f"{self.struct}\n" if self.struct else ""
        return head + f"/-- {self.doc} -/\n{self.signature}\n" + "\n".join(body) + f"\n{self.result}\n"


def comment_column(routines):
    """Two spaces past the widest instruction binding in these routines."""
    return 2 + max(
        len(code) for routine in routines for code, comment in routine.lines
        if code is not None and comment is not None
    )


def emit_routine(source: str, config: RoutineConfig) -> Routine:
    """Validate and transcribe one source block into the shared routine IR."""
    parsed = parse_function(source, config)
    argument_types = dict(config.args)
    directions = asm_source.declaration_directions(parsed, config.rust_name)
    emitter = Emitter(directions, {})
    pointer_count = 0

    fixed_rdx = [decl for decl in parsed.declarations if decl.fixed]
    uses_architectural_rdx = any(
        re.search(r"(?<![A-Za-z0-9_{])rdx(?![A-Za-z0-9_}])", instruction)
        for instruction in parsed.instructions
    )
    if uses_architectural_rdx and len(fixed_rdx) != 1:
        raise GenerationError(
            f"{config.rust_name}: literal rdx requires exactly one fixed out(\"rdx\") _ operand"
        )
    if not uses_architectural_rdx and fixed_rdx:
        raise GenerationError(f"{config.rust_name}: unused fixed rdx operand")

    for declaration in parsed.declarations:
        if declaration.fixed:
            continue
        if declaration.kind == "const":
            emitter.bind_argument(
                declaration.name, str(PASTA_HIGH_LIMB),
                f"operand {declaration.name} = const PASTA_HIGH_LIMB",
            )
        elif declaration.kind in ("in", "inout"):
            pointer = re.fullmatch(r"([A-Za-z_]\w*)\.as_ptr\(\)", declaration.value)
            if pointer:
                argument = pointer.group(1)
                if argument_types.get(argument) != "Limbs":
                    raise GenerationError(
                        f"{config.rust_name}: pointer {declaration.name} is not a Limbs argument"
                    )
                emitter.bind_pointer(declaration.name, argument)
                pointer_count += 1
            else:
                expression, description = input_expression(
                    declaration.value, parsed.locals, argument_types
                )
                emitter.bind_argument(declaration.name, expression, description)
        elif declaration.kind != "out":
            raise GenerationError(
                f"{config.rust_name}: unsupported direction {declaration.kind}"
            )

    if pointer_count:
        if "readonly" not in parsed.options or "nomem" in parsed.options:
            raise GenerationError(
                f"{config.rust_name}: pointer operands require readonly and forbid nomem"
            )
    elif "nomem" not in parsed.options or "readonly" in parsed.options:
        raise GenerationError(
            f"{config.rust_name}: register-only block requires nomem and forbids readonly"
        )

    for pc, instruction in enumerate(parsed.instructions):
        emitter.pc = pc
        emitter.emit_instruction(instruction)
    if emitter.used_memory != bool(pointer_count):
        raise GenerationError(
            f"{config.rust_name}: declared pointer operands and memory reads disagree"
        )

    result_registers = list(asm_source.returned_registers(parsed, config.rust_name))
    for register in result_registers:
        if register not in emitter.known:
            raise GenerationError(
                f"{config.rust_name}: output register {register} was never written"
            )

    grouped: List[str] = []
    index = 0
    while index < len(config.args):
        name, kind = config.args[index]
        same = [name]
        index += 1
        while index < len(config.args) and config.args[index][1] == kind:
            same.append(config.args[index][0])
            index += 1
        grouped.append(f"({' '.join(same)} : {kind})")
    signature = f"def {config.lean_name} {' '.join(grouped)} : {config.result_type} :="

    result = f"  ⟨{', '.join(result_registers)}⟩"
    return Routine(
        config.doc, signature, emitter.render(result_registers), result,
        config.lean_name, emitter, result_registers,
    )


def _rename_round_value(value, rotation, rhs_limb):
    """Canonicalize one flattened multiplication round's register-valued IR."""
    if isinstance(value, str):
        if value == rhs_limb:
            return "b"
        for register, canonical in rotation.items():
            value = re.sub(
                rf"(?<![A-Za-z0-9_']){re.escape(register)}(?![A-Za-z0-9_'])",
                canonical,
                value,
            )
        return value
    if isinstance(value, tuple):
        return tuple(_rename_round_value(item, rotation, rhs_limb) for item in value)
    if isinstance(value, list):
        return [_rename_round_value(item, rotation, rhs_limb) for item in value]
    return value


def _normalized_mul_round_entries(emitter, pc_range, rotation, rhs_limb):
    """Return one full round under canonical accumulator names and a scalar RHS limb."""
    first, last = pc_range
    entries = []
    for entry in emitter.entries:
        if entry["pc"] is None or not first <= entry["pc"] <= last:
            continue
        normalized = dict(entry)
        normalized["name"] = _rename_round_value(entry["name"], rotation, rhs_limb)
        normalized["expr"] = _rename_round_value(entry["expr"], rotation, rhs_limb)
        normalized["reads"] = {
            _rename_round_value(read, rotation, rhs_limb) for read in entry["reads"]
        }
        normalized["fact"] = _rename_round_value(entry["fact"], rotation, rhs_limb)
        normalized["pc"] = entry["pc"] - first
        entries.append(normalized)
    return entries


def _round_fingerprint(entries):
    """The semantic IR fields whose equality justifies replacing a flattened round by a call."""
    return [
        (entry["name"], entry["expr"], tuple(sorted(entry["reads"])),
         entry["load"], entry["fact"], entry["pc"])
        for entry in entries
    ]


def _mul_acc_struct():
    return """/-- The rotating five-limb accumulator of `mulMont`, together with the most recent
Montgomery quotient. The next round does not read `q`; retaining it exposes the round invariant
needed by the block proof. -/
structure MulMontAcc where
  /-- accumulator limb 0 -/
  r0 : Nat
  /-- accumulator limb 1 -/
  r1 : Nat
  /-- accumulator limb 2 -/
  r2 : Nat
  /-- accumulator limb 3 -/
  r3 : Nat
  /-- accumulator limb 4 -/
  r4 : Nat
  /-- the most recent Montgomery quotient -/
  q : Nat
  deriving DecidableEq, Repr

namespace MulMontAcc

/-- Every field is below `2^64`. -/
def Bounded (s : MulMontAcc) : Prop :=
  s.r0 < 2^64 ∧ s.r1 < 2^64 ∧ s.r2 < 2^64 ∧ s.r3 < 2^64 ∧ s.r4 < 2^64 ∧ s.q < 2^64

/-- The value of the five accumulator limbs. -/
def toNat (s : MulMontAcc) : Nat :=
  s.r0 + 2^64 * s.r1 + 2^128 * s.r2 + 2^192 * s.r3 + 2^256 * s.r4

end MulMontAcc
"""


def factor_mul_rounds(routine: Routine):
    """Mechanically validate and factor the two full flattened rounds of ``mulMont``."""
    rounds = [
        _normalized_mul_round_entries(routine.emitter, pc_range, rotation, f"rhs.l{index}")
        for index, (pc_range, rotation) in enumerate(
            zip(MUL_ROUND_RANGES, MUL_ROUND_ROTATIONS), start=1
        )
    ]
    if not rounds[0] or _round_fingerprint(rounds[0]) != _round_fingerprint(rounds[1]):
        raise GenerationError(
            "mul: flattened full rounds 1 and 2 differ after accumulator rotation"
        )

    first_pc = min(entry["pc"] for entry in rounds[0])
    source_load = next(
        (entry for entry in rounds[0] if entry["name"] == "rdx" and entry["pc"] == first_pc),
        None,
    )
    if source_load is None or source_load["expr"] != "b":
        raise GenerationError("mul: factored round does not begin by loading its RHS limb into RDX")

    round_emitter = Emitter({}, {})
    round_emitter.helper_proof_mode = True
    round_emitter.bind("inv", "inv", "scalar argument", reads=(), fact=("inv",))
    round_emitter.bind("b", "b", source_load["comment"], reads=(), fact=("param", "b"))
    for field in MUL_ACC_FIELDS:
        if field == "q":
            continue
        round_emitter.bind(
            field, f"acc.{field}", "accumulator argument", reads=(), load=True,
            fact=("load", "acc", field),
        )
    # The first source instruction loads the round's scalar RHS limb into RDX. The helper already
    # receives that scalar as ``b``; substitute it into the remaining validated IR instead of
    # emitting a definitionally-equal ``let rdx := b`` that ``lift_lets`` would erase.
    helper_entries = []
    aliases = {"rdx": "b"}
    for entry in rounds[0]:
        if entry["pc"] == first_pc:
            continue
        normalized = dict(entry)
        normalized["expr"] = _rename_round_value(entry["expr"], aliases, "")
        normalized["reads"] = {
            _rename_round_value(read, aliases, "") for read in entry["reads"]
        }
        normalized["fact"] = _rename_round_value(entry["fact"], aliases, "")
        helper_entries.append(normalized)
        # The omitted entry load creates the initial alias only. Once the source writes RDX,
        # subsequent reads must see that new quotient/register value rather than the helper's b.
        aliases.pop(entry["name"], None)
    for entry in helper_entries:
        normalized = dict(entry)
        if normalized["fact"][0] in {"x86_mulx", "x86_adds", "x86_subs", "x86_neg"}:
            # The wrapper is semantically required so both projections read the same old operands.
            # ``lift_lets`` inlines these wrappers in this helper; skeleton preparation therefore
            # treats them as non-extractable while retaining them in generated Lean.
            normalized["helper_wrapper"] = True
        round_emitter.entries.append(normalized)
    round_result = ["r1", "r2", "r3", "r4", "r0", "rdx"]
    round_lines, round_result_ssa = round_emitter.render_ssa(round_result)
    round_routine = Routine(
        "One full internal round of `mulMont`: add `lhs * b` to the rotating five-limb "
        "accumulator, cancel its low limb with the Montgomery quotient, and shift by one limb. "
        "The source's flattened rounds 1 and 2 are checked to have this same binding IR modulo "
        "their accumulator-register rotation and RHS limb.",
        "def mulMontRound (lhs modulus : Limbs) (inv b : Nat) "
        "(acc : MulMontAcc) : MulMontAcc :=",
        round_lines,
        f"  ⟨{', '.join(round_result_ssa)}⟩",
        "mulMontRound", round_emitter, round_result,
        struct=_mul_acc_struct(), arg_fields={"acc": MUL_ACC_FIELDS},
    )

    main_emitter = Emitter(routine.emitter.directions, {})
    # The multiplication proof clears values at arithmetic phase boundaries, avoiding
    # repeated rechecking of its large dependent instruction tail.
    main_emitter.phase_clear_values = True
    main_emitter.entries = [
        dict(entry) for entry in routine.emitter.entries
        if entry["pc"] is None or entry["pc"] < MUL_ROUND_RANGES[0][0]
    ]
    current = ["be", "ce", "de", "ee", "ae"]
    inv_register = "inv"
    for round_number, rhs_index in ((1, 1), (2, 2)):
        call_args = [inv_register, f"rhs.l{rhs_index}"] + current + ["rdx"]
        fmt = "mulMontRound lhs modulus {0} {1} ⟨" + ", ".join(
            "{%d}" % index for index in range(2, 8)
        ) + "⟩"
        round_name = f"round{round_number}"
        main_emitter.entries.append(dict(
            name=round_name, expr=fmt.format(*call_args), comment=f"factored round {round_number}",
            note=None, reads=set([inv_register, f"rhs.l{rhs_index}"] + current + ["rdx"]), load=False,
            fact=("call", fmt, call_args), pc=None,
        ))
        next_current = current[1:] + current[:1]
        for register, field in zip(next_current + ["rdx"], MUL_ACC_FIELDS):
            main_emitter.entries.append(dict(
                name=register, expr=f"{round_name}.{field}",
                comment=f"round {round_number} output", note=None, reads={round_name}, load=False,
                fact=("callout", round_name, field), pc=None,
            ))
        current = next_current
    main_emitter.entries.extend(
        dict(entry) for entry in routine.emitter.entries
        if entry["pc"] is not None and entry["pc"] > MUL_ROUND_RANGES[-1][1]
    )
    main = Routine(
        routine.doc, routine.signature, main_emitter.render(routine.result_names), routine.result,
        routine.name, main_emitter, routine.result_names,
    )
    return [round_routine, main]



@dataclasses.dataclass(frozen=True)
class InvertBlockSpec:
    name: str
    signature: str
    args: Tuple[Tuple[str, str], ...]
    bindings: Dict[str, str]
    results: Tuple[str, ...]
    result: str
    doc: str
    struct: Optional[str] = None
    arg_fields: Optional[Dict[str, Sequence[str]]] = None


def emit_invert_block(block, instructions: Sequence[str], spec: InvertBlockSpec) -> Routine:
    directions = asm_source.declaration_directions(block, spec.name)
    emitter = Emitter(directions, {}, inversion=True)
    emitter.helper_proof_mode = True
    emitter.divsteps_clear_values = spec.name.startswith("divsteps")
    argument_types = dict(spec.args)
    for declaration in block.declarations:
        if declaration.fixed:
            continue
        if declaration.kind in ("in", "inout"):
            if declaration.name not in spec.bindings:
                raise GenerationError(f"{spec.name}: missing input binding for {declaration.name}")
            expression = spec.bindings[declaration.name]
            field = re.fullmatch(r"([A-Za-z_]\w*)\.([A-Za-z_]\w*)", expression)
            if field:
                argument, field_name = field.groups()
                if argument not in argument_types:
                    raise GenerationError(f"{spec.name}: bound input names unknown argument {argument}")
                effective_fields = dict(gen.ARG_FIELDS)
                effective_fields.update(spec.arg_fields or {})
                fields = effective_fields.get(argument)
                if fields is None and argument_types[argument] == "Limbs":
                    fields = gen.LIMB_FIELDS
                if fields is None or field_name not in fields:
                    raise GenerationError(f"{spec.name}: no bound projection for {expression}")
                hypothesis = gen.BOUND_HYPS.get(argument, f"h{argument}")
                bound = f"{hypothesis}.{gen.proj(argument, field_name, {argument: fields})}"
            else:
                bound = gen.BOUND_HYPS.get(expression, f"h{expression}")
            emitter.bind_argument(
                declaration.name, expression, f"input {declaration.value}", bound=bound,
            )
        elif declaration.kind not in ("out", "lateout"):
            raise GenerationError(f"{spec.name}: unsupported direction {declaration.kind}")
    fixed_inputs = [declaration for declaration in block.declarations if declaration.fixed
                    and declaration.kind in ("in", "inout")]
    if fixed_inputs:
        raise GenerationError(f"{spec.name}: fixed input operands are unsupported")
    for pc, instruction in enumerate(instructions):
        emitter.pc = pc
        emitter.emit_instruction(instruction)
    for register in spec.results:
        if register not in emitter.known:
            raise GenerationError(f"{spec.name}: result register {register} was never written")
    arg_fields = dict(spec.arg_fields or {})
    return Routine(
        spec.doc, spec.signature, emitter.render(spec.results), spec.result,
        spec.name, emitter, list(spec.results), struct=spec.struct,
        arg_fields=arg_fields,
    )



INVERT_STRUCTS = """/-- Outputs of the shift-and-absolute-value inversion helper block. -/
structure UpdateAbResult where
  value : Limbs
  f : Nat
  g : Nat
  deriving DecidableEq, Repr

/-- Carry state produced by one generic `add_words` assembly iteration. -/
structure AddWordsLimbResult where
  value : Nat
  carry : Nat
  deriving DecidableEq, Repr

/-- Product and carry state produced by one generic `mul_signed` assembly iteration. -/
structure MulSignedLimbResult where
  low : Nat
  high : Nat
  negateCarry : Nat
  deriving DecidableEq, Repr

/-- High-half state after the first normalization assembly block. -/
structure NormalizeNegativeResult where
  h0 : Nat
  h1 : Nat
  h2 : Nat
  h3 : Nat
  excess : Nat
  deriving DecidableEq, Repr
"""


def _config(name: str) -> InvertRoutineConfig:
    return next(config for config in INVERT_ROUTINES if config.rust_name == name)


def emit_simple_invert_routines(source: str) -> List[Routine]:
    routines: List[Routine] = []

    parsed = parse_invert_helper(source, _config("update_ab"))
    routines.append(emit_invert_block(parsed.blocks[0], parsed.blocks[0].instructions, InvertBlockSpec(
        "updateAbShift",
        "def updateAbShift (value : PastaAsm.WideLimbs) (f g : Nat) : UpdateAbResult :=",
        (("value", "PastaAsm.WideLimbs"), ("f", "Nat"), ("g", "Nat")),
        {**{f"r{i}": f"value.l{i}" for i in range(5)}, "mask": "0", "bit": "0"},
        ("r0", "r1", "r2", "r3", "mask", "bit"),
        "  ⟨⟨r0, r1, r2, r3⟩, word ((word f ^^^ mask) + bit), "
        "word ((word g ^^^ mask) + bit)⟩",
        "The `update_ab` assembly block: shift a five-word linear combination by 31, "
        "take its absolute value, and apply the sign correction to the row coefficients.",
        struct=INVERT_STRUCTS,
        arg_fields={"value": [f"l{i}" for i in range(9)]},
    )))

    parsed = parse_invert_helper(source, _config("add_words"))
    routines.append(emit_invert_block(parsed.blocks[0], parsed.blocks[0].instructions, InvertBlockSpec(
        "addWordsLimb",
        "def addWordsLimb (lhs rhs carry : Nat) : AddWordsLimbResult :=",
        (("lhs", "Nat"), ("rhs", "Nat"), ("carry", "Nat")),
        {"lhs": "lhs", "rhs": "rhs", "carry": "carry"},
        ("lhs", "carry"), "  ⟨lhs, carry⟩",
        "One iteration of the generic `add_words` assembly block. The Rust loop applies it "
        "once per public limb and discards carry above the final limb.",
    )))

    parsed = parse_invert_helper(source, _config("mul_signed"))
    routines.append(emit_invert_block(parsed.blocks[0], parsed.blocks[0].instructions, InvertBlockSpec(
        "mulSignedLimb",
        "def mulSignedLimb (limb sign negateCarry magnitude productCarry : Nat) : "
        "MulSignedLimbResult :=",
        (("limb", "Nat"), ("sign", "Nat"), ("negateCarry", "Nat"),
         ("magnitude", "Nat"), ("productCarry", "Nat")),
        {"limb": "limb", "sign": "sign", "negate_carry": "negateCarry",
         "magnitude": "magnitude", "product_carry": "productCarry"},
        ("rax", "rdx", "next_negate_carry"), "  ⟨rax, rdx, next_negate_carry⟩",
        "One iteration of the generic `mul_signed` assembly block, including conditional "
        "two's-complement negation and one unsigned multiply-with-carry step.",
    )))

    parsed = parse_invert_helper(source, _config("normalize"))
    routines.append(emit_invert_block(parsed.blocks[0], parsed.blocks[0].instructions, InvertBlockSpec(
        "normalizeNegative",
        "def normalizeNegative (value : PastaAsm.WideLimbs) (modulus2 : Limbs) : "
        "NormalizeNegativeResult :=",
        (("value", "PastaAsm.WideLimbs"), ("modulus2", "Limbs")),
        {**{f"h{i}": f"value.l{i + 4}" for i in range(4)}, "excess": "value.l8",
         **{f"m{i}": f"modulus2.l{i}" for i in range(4)}},
        ("h0", "h1", "h2", "h3", "excess"), "  ⟨h0, h1, h2, h3, excess⟩",
        "The first `normalize` assembly block: conditionally add the aligned doubled modulus "
        "when the coefficient is negative.",
        arg_fields={"value": [f"l{i}" for i in range(9)]},
    )))
    routines.append(emit_invert_block(parsed.blocks[1], parsed.blocks[1].instructions, InvertBlockSpec(
        "normalizeExcess",
        "def normalizeExcess (high modulus2 : Limbs) (excess : Nat) : Limbs :=",
        (("high", "Limbs"), ("modulus2", "Limbs"), ("excess", "Nat")),
        {**{f"h{i}": f"high.l{i}" for i in range(4)},
         **{f"m{i}": f"modulus2.l{i}" for i in range(4)}, "excess": "excess"},
        ("h0", "h1", "h2", "h3"), "  ⟨h0, h1, h2, h3⟩",
        "The second `normalize` assembly block: add or subtract one aligned doubled modulus "
        "according to the remaining signed excess word.",
    )))

    parsed = parse_invert_helper(source, _config("reduce_once"))
    routines.append(emit_invert_block(parsed.blocks[0], parsed.blocks[0].instructions, InvertBlockSpec(
        "reduceOnce",
        "def reduceOnce (value modulus : Limbs) : Limbs :=",
        (("value", "Limbs"), ("modulus", "Limbs")),
        {**{f"r{i}": f"value.l{i}" for i in range(4)},
         "p0": "modulus.l0", "p1": "modulus.l1", "p3": "modulus.l3"},
        ("r0", "r1", "r2", "r3"), "  ⟨r0, r1, r2, r3⟩",
        "The `reduce_once` assembly block: subtract one Pasta modulus and conditionally add it back.",
    )))
    return routines



DIVSTEPS_STRUCTS = """/-- Apply a mechanically transcribed fixed-loop body a public number of times. -/
def iterate {α : Type} (step : α → α) : Nat → α → α
  | 0, s => s
  | n + 1, s => iterate step n (step s)

/-- Live register state of one factored 31-divstep inner-loop iteration. -/
structure Divsteps31State where
  a0 : Nat
  a1 : Nat
  a2 : Nat
  a3 : Nat
  b0 : Nat
  b1 : Nat
  b2 : Nat
  b3 : Nat
  t : Nat
  deriving DecidableEq, Repr

/-- Live register state of one factored final divstep iteration. -/
structure Divsteps47State where
  a : Nat
  b : Nat
  f0 : Nat
  g0 : Nat
  f1 : Nat
  g1 : Nat
  t0 : Nat
  t1 : Nat
  t2 : Nat
  deriving DecidableEq, Repr
"""


def _validate_fixed_loop(instructions, *, count_init, decrement, counter_tokens,
                         label_index, body_range, decrement_index, branch_index):
    first, last = body_range
    expected = {
        label_index: "2:",
        decrement_index: decrement,
        branch_index: "jnz 2b",
    }
    if instructions[0 if label_index == 1 else label_index - 1] != count_init:
        raise GenerationError(f"fixed loop count initializer must be `{count_init}`")
    for index, instruction in expected.items():
        if instructions[index] != instruction:
            raise GenerationError(
                f"fixed loop control at instruction {index} must be `{instruction}`"
            )
    labels = [(index, instruction) for index, instruction in enumerate(instructions)
              if instruction.endswith(":")]
    branches = [(index, instruction) for index, instruction in enumerate(instructions)
                if instruction.startswith("j")]
    if labels != [(label_index, "2:")] or branches != [(branch_index, "jnz 2b")]:
        raise GenerationError("fixed loop must have exactly one `2:` label and one `jnz 2b`")
    if not (label_index < first <= last < decrement_index
            and branch_index == decrement_index + 1):
        raise GenerationError("fixed loop decrement must immediately precede its backedge")
    def uses_counter(instruction):
        return any(
            re.search(rf"\{{{re.escape(token)}(?::[A-Za-z_]\w*)?\}}", instruction)
            or re.search(rf"(?<![A-Za-z0-9_]){re.escape(token)}(?![A-Za-z0-9_])", instruction)
            for token in counter_tokens
        )

    counter_uses = [
        (index, instruction) for index, instruction in enumerate(instructions)
        if uses_counter(instruction)
    ]
    if counter_uses != [(label_index - 1, count_init), (decrement_index, decrement)]:
        raise GenerationError("fixed loop counter may appear only in its initializer and decrement")
    # `sub` writes ZF and the immediately following `jnz` is the only branch, so its condition is
    # mechanically tied to this public counter decrement rather than any data-dependent flag.
    return instructions[first:last + 1]


def emit_divsteps31_routines(source: str) -> List[Routine]:
    parsed = parse_invert_helper(source, _config("divsteps_31"))
    block = parsed.blocks[0]
    instructions = block.instructions
    body = _validate_fixed_loop(
        instructions, count_init="mov ecx, 31", decrement="sub ecx, 1",
        counter_tokens=("ecx",), label_index=36, body_range=(37, 56),
        decrement_index=57, branch_index=58,
    )
    fields = ("a0", "a1", "a2", "a3", "b0", "b1", "b2", "b3", "t")
    round_routine = emit_invert_block(block, body, InvertBlockSpec(
        "divsteps31Round", "def divsteps31Round (s : Divsteps31State) : Divsteps31State :=",
        (("s", "Divsteps31State"),), {field: f"s.{field}" for field in fields}, fields,
        "  ⟨a0, a1, a2, a3, b0, b1, b2, b3, t⟩",
        "One mechanically factored iteration of the fixed 31-step inner loop. The factorer "
        "checks the source count, label, decrement, backedge, and exact body slice.",
        struct=DIVSTEPS_STRUCTS, arg_fields={"s": list(fields)},
    ))

    prefix = list(instructions[:36])
    suffix = list(instructions[59:])
    main = emit_invert_block(block, prefix, InvertBlockSpec(
        "divsteps31", "def divsteps31 (a b : Limbs) : InvertMatrix :=",
        (("a", "Limbs"), ("b", "Limbs")),
        {**{f"a{i}": f"a.l{i}" for i in range(4)}, **{f"b{i}": f"b.l{i}" for i in range(4)}},
        (), "", "The complete 31-iteration approximation helper.",
    ))
    emitter = main.emitter
    call_args = list(fields)
    emitter.bind(
        "loop", "iterate divsteps31Round 31 ⟨" + ", ".join(call_args) + "⟩",
        "factored fixed 31-iteration loop", reads=set(call_args),
        fact=("call", "iterate divsteps31Round 31 ⟨" + ", ".join("{%d}" % i for i in range(len(call_args))) + "⟩", call_args),
    )
    for field in fields:
        emitter.bind(field, f"loop.{field}", "fixed loop output", reads={"loop"},
                     fact=("callout", "loop", field))
    for pc, instruction in enumerate(suffix, start=59):
        emitter.pc = pc
        emitter.emit_instruction(instruction)
    results = ["a0", "a1", "b0", "a2"]
    main.lines = emitter.render(results)
    main.result_names = results
    main.result = "  ⟨a0, a1, b0, a2⟩"
    return [round_routine, main]


def emit_divsteps47_routines(source: str) -> List[Routine]:
    parsed = parse_invert_helper(source, _config("divsteps_47"))
    block = parsed.blocks[0]
    instructions = block.instructions
    body = _validate_fixed_loop(
        instructions, count_init="mov {count:e}, 47", decrement="sub {count:e}, 1",
        counter_tokens=("count",), label_index=1, body_range=(2, 26),
        decrement_index=27, branch_index=28,
    )
    fields = ("a", "b", "f0", "g0", "f1", "g1", "t0", "t1", "t2")
    round_routine = emit_invert_block(block, body, InvertBlockSpec(
        "divsteps47Round", "def divsteps47Round (s : Divsteps47State) : Divsteps47State :=",
        (("s", "Divsteps47State"),), {field: f"s.{field}" for field in fields}, fields,
        "  ⟨a, b, f0, g0, f1, g1, t0, t1, t2⟩",
        "One mechanically factored iteration of the fixed final 47-step loop. The factorer "
        "checks the source count, label, decrement, backedge, and exact body slice.",
        arg_fields={"s": list(fields)},
    ))

    # The source initializes only the public loop counter in assembly. Rust initializes the row.
    emitter = Emitter(asm_source.declaration_directions(block, "divsteps47"), {}, inversion=True)
    emitter.helper_proof_mode = True
    emitter.divsteps_clear_values = True
    bindings = {"a": "a", "b": "b", "f0": "1", "g0": "0", "f1": "0", "g1": "1"}
    for declaration in block.declarations:
        if declaration.kind in ("in", "inout"):
            expression = bindings[declaration.name]
            bound = gen.BOUND_HYPS.get(expression, f"h{expression}") if not expression.isdigit() else "by decide"
            emitter.bind_argument(
                declaration.name, expression, f"input {declaration.value}", bound=bound,
            )
    emitter.pc = 0
    emitter.emit_instruction(instructions[0])
    # Scratch outputs are initialized by the loop before every read; arbitrary initial zeros expose
    # no source behavior but provide a total state value to the recursive iterator.
    for scratch in ("t0", "t1", "t2"):
        emitter.bind(scratch, "0", "unread scratch initialization", reads=(), fact=("mov", "0"))
    call_args = list(fields)
    emitter.bind(
        "loop", "iterate divsteps47Round 47 ⟨" + ", ".join(call_args) + "⟩",
        "factored fixed 47-iteration loop", reads=set(call_args),
        fact=("call", "iterate divsteps47Round 47 ⟨" + ", ".join("{%d}" % i for i in range(len(call_args))) + "⟩", call_args),
    )
    for field in fields:
        emitter.bind(field, f"loop.{field}", "fixed loop output", reads={"loop"},
                     fact=("callout", "loop", field))
    results = ["f0", "g0", "f1", "g1"]
    main = Routine(
        "The complete fixed 47-low-limb iteration helper.",
        "def divsteps47 (a b : Nat) : InvertMatrix :=",
        emitter.render(results), "  ⟨f0, g0, f1, g1⟩", "divsteps47", emitter, results,
    )
    return [round_routine, main]


def all_invert_routines(source: Optional[str] = None) -> List[Routine]:
    if source is None:
        source = INVERT_SOURCE.read_text()
    return emit_divsteps31_routines(source) + emit_simple_invert_routines(source) + \
        emit_divsteps47_routines(source)


def emit_routines(source: str, config: RoutineConfig):
    """Emit a source routine, plus its helper when repeated rounds are factored."""
    routine = emit_routine(source, config)
    return factor_mul_rounds(routine) if config.lean_name == "mulMont" else [routine]


def transcribe(source: str, config: RoutineConfig) -> str:
    """Render one x86-64 source routine and any validated factored helpers."""
    routines = emit_routines(source, config)
    return "\n".join(routine.text(comment_column([routine])) for routine in routines)


def gen_program(source: Optional[str] = None, invert_source: Optional[str] = None) -> str:
    routines = all_routines(source, invert_source)
    return HEADER + "\n".join(
        routine.text(comment_column([routine])) for routine in routines
    ) + FOOTER


def in_contract(op: str, field: str, operands: Sequence[int]) -> bool:
    """Whether a row satisfies both the public and x86-64 backend assertions."""
    if not gen.in_public_contract(op, field, operands):
        return False
    # Unlike AArch64, the x86-64 multiplication backend itself additionally
    # debug-asserts a canonical rhs, even when the public contract accepted a
    # canonical lhs with an arbitrary rhs.
    return op != "MUL" or gen.is_canonical(field, operands[1])


def gen_vectors(lines: Sequence[str]) -> str:
    """Generate x86-64 checks from the AArch64 hardware vector corpus."""
    return gen.render_vectors(
        lines,
        imports="import PastaAsm.Fields\nimport PastaAsm.X86_64.Compositions\n",
        introduction="""
/-!
# Cross-backend reference vectors for the transcribed blocks

GENERATED by `lean/scripts/gen.py` from `test-vectors/pasta_mul-armv8-vectors.txt`; do not
edit by hand. Each expected value was produced by the real AArch64 assembly (Semolina's
`mul_mont_pasta`, `sqr_mont_pasta`, and `from_mont_pasta`, as vendored by pasta_curves at
`8ad85e9fab7929f6236960e472f432a4bd9ccd74` and run on an Apple M-series machine). These
are cross-backend checks that the x86-64 transcription produces the same values on the same
operands, not captures from x86-64 hardware.

The multiplication examples exercise the standalone `mulMont` block. The squaring examples
exercise `sqrMont`, the Rust composition `squareHi (squareLo value)`. The conversion examples
exercise x86-64's standalone `fromMont` assembly block, rather than AArch64's multiplication
by one composition. A row is retained only when it satisfies both the public entry point's
contract and the backend called by that entry point. In particular, the x86-64 `mul` backend
additionally requires a canonical right operand; omitted rows are counted at the end.

The modulus limbs and `inv` are `pallasBase` and `vestaBase` from `Fields.lean`, the crate's
constants for its `Fp` (the Pallas base field) and `Fq` (the Vesta base field).
-/

namespace PastaAsm.X86_64

""",
        namespace="PastaAsm.X86_64",
        in_contract=in_contract,
        omission_scope="the combined public and x86-64 backend contracts",
    )


def gen_invert_vectors(lines: Sequence[str]) -> str:
    """Generate x86-64 inversion-composition checks from mathematical expectations."""
    return gen.render_inversion_vectors(
        lines,
        imports="import PastaAsm.Fields\nimport PastaAsm.X86_64.Compositions\n",
        introduction="""
/-!
# Mathematical reference vectors for the inversion composition

GENERATED by `lean/scripts/gen.py` from the distinct canonical operands in
`test-vectors/pasta_mul-armv8-vectors.txt`; do not edit by hand. Each example asks the
Lean kernel to evaluate the actual x86-64 `invert` composition, including all generated
assembly-block transcriptions used by the Rust driver.

Only the operands come from the AArch64 hardware corpus. The expected values are derived
independently by modular arithmetic, not captured from AArch64 or x86-64 inversion hardware:
zero maps to zero; for nonzero Montgomery residues `input * result = R^2 (mod p)`, where
`R = 2^256`. Thus these concrete examples supplement, but do not replace, a universal inversion
correctness proof.

The modulus limbs and `inv` are `pallasBase` and `vestaBase` from `Fields.lean`, the crate's
constants for its `Fp` (the Pallas base field) and `Fq` (the Vesta base field).
-/

namespace PastaAsm.X86_64

""",
        namespace="PastaAsm.X86_64",
    )


def all_routines(source: Optional[str] = None, invert_source: Optional[str] = None):
    """Return every validated x86-64 block routine and mechanically factored helper."""
    if source is None:
        source = SOURCE.read_text()
    if invert_source is None:
        invert_source = INVERT_SOURCE.read_text()
    validate_high_limb(source)
    routines = []
    for config in ROUTINES:
        routines.extend(emit_routines(source, config))
    routines.extend(all_invert_routines(invert_source))
    return routines


def generated_outputs():
    """Return the x86-64 generated paths and contents without writing files."""
    lines = VECTORS.read_text().splitlines()
    return [
        (OUTPUT, gen_program()),
        (OUTPUT_VECTORS, gen_vectors(lines)),
        (OUTPUT_INVERT_VECTORS, gen_invert_vectors(lines)),
    ]

